### ISSUE TITLE
Building a Bitcoin Game and Earning SATs for Play

### ISSUE THREAD

**Issue by JoseMoranUrena523** [TABConf/2023.tabconf.com#10]
As the former owner / former developer of 2048 Bitcoin, I would like to propose a workshop at TABConf to show attendees how to integrate an existing game into a play-to-earn platform. Using 2048 Bitcoin as a case study, I will guide attendees through the process of integrating a game into a play-to-earn platform and demonstrate how to monetize the game through earning SATs. 

Note: My workshop shouldn't be used to create a game meant for public use since this game can be hacked by players, this is just so game developers can have a simple understanding but they have to implement security for their games. 

The workshop will cover the following key points:

- Overview of the play-to-earn model and its benefits for players and developers.
- The step-by-step process of integrating 2048 Bitcoin into my new API ([Biteq by Teqquu](https://biteq.teqquu.com)), including challenges faced and solutions implemented.
- Best practices and lessons learned from the integration process.

This workshop would need to be conducted virtually as I am unable to attend the event in person.

Target Audience: Game developers interested in incorporating play-to-earn elements into their games.

Note: Prior knowledge of game development and cryptocurrency is helpful, but not required.

I look forward to the opportunity to share my experience and insights with the TABConf community.

Thank you for your time and consideration.

Best regards,
Jose Moran Urena (Coffee L. Arkoburger)

**Comment by iglesiasbrandon** [comment]
Hey, @JoseMoranUrena523, thank you for submitting a workshop issue for TABConf 2023! As we get closer to the conference, we will review all the issues, and the chosen ones will be added to the TABConf 2023 schedule: https://github.com/orgs/TABConf/projects/1.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions about your issue. Also, please update the issue description if you'd like to add anything else as we get closer to the conf.

**Comment by JoseMoranUrena523** [comment]
Ok @iglesiasbrandon, honestly I am just wondering if I will be able to do this workshop even if I get approved because I can’t go physically to TABConf.

**Comment by JoseMoranUrena523** [comment]
Hey, I had to shut down my game due to my ban on ZEBEDEE so I am going to edit the first post and I want you guys to review it of course. Thank you!

**Comment by JoseMoranUrena523** [comment]
Thank you so much for adding my workshop to the schedule! By the way, what is no day?

**Comment by JoseMoranUrena523** [comment]
Also, if I get the Accepted tag, how would I do it if I can’t go there?

**Comment by iglesiasbrandon** [comment]
Hey @JoseMoranUrena523, unfortunately, I don't think we can facilitate a non-in-person workshop.

**Comment by JoseMoranUrena523** [comment]
Dang it, and you guys can’t fly me out either of course. Is there no way like you have a projector at the conference and I can do my workshop that way or something else?

**Comment by miketwenty1** [comment]
@JoseMoranUrena523 You're always welcome to hack and share ideas during builders day (sept 6,7)

**Comment by JoseMoranUrena523** [comment]
Ok, but I just really wanted to get accepted into TabConf. I wish there was a way to put a display, login as a Zoom call, and do the workshop like that, or a way to fly me out or something like that. It has been my dream to do something like that.

**Comment by iglesiasbrandon** [comment]
@JoseMoranUrena523, we appreciate your excitement and passion! 
That's the exact type of thing we need in builders like yourself. 

I hope that you might be able to come next year and give a workshop or do some hacking with us. Unfortunately, we just don't have the capacity to facilitate non in-person presenters this year. 

Keep building and hacking. I love your attitude and drive @JoseMoranUrena523

**Comment by JoseMoranUrena523** [comment]
Is there a year that it could be possible, like next year?

**Comment by Bitc0indad** [comment]
I think it's a good idea to have Virtual Village for 2024...or TabConf Cyber Monday version...

**Comment by JoseMoranUrena523** [comment]
It is a pretty good idea, I really hope it’s available next year so I can do a workshop on Bitcoin Lightning game development.

**Comment by miketwenty1** [comment]
hope to see a submission next year. closing this issue for this years conf.
