### ISSUE TITLE
10101 Wallet Builder Day

### ISSUE THREAD

**Issue by klochowicz** [TABConf/2023.tabconf.com#100]
# Description

### What is this project about? Please give us as many details as possible.

10101 is a self-custodial wallet that allows the users to trade without counterparty risk.
The wallet part is built on top of LDK, and the trading uses rust-dlc library under the hood.
On top of that, it has a modern UI built in Flutter, which allows for deploying on all range of platforms - iOS, Android, Windows, macOS, Linux, WASM.
Currently, the app is available in closed beta on iOS (TestFlight).

### Is it a FOSS or Open Source project?

MIT

### What would an attendee learn from visiting this projects table at Builder Days?

- Rust
- Flutter
- Protocol Design

### Is there anything people should read up on before finding the table at Builder Day?

- it would be good to have some basic understanding of Rust and/or Flutter
- if possible, check out the repo and try to compile things beforehand to ensure dev environment is set up.
- what is Discreet Log Contract (DLC)

### Relevant Links

GitHub Repo: https://github.com/get10101/10101

# Project Details

### Who will run the table? Are those people current contributors or maintainers who can answer questions and get people onboarded?

One of the authors / maintainers: Mariusz Klochowicz [GitHub](https://github.com/klochowicz)

**Comment by iglesiasbrandon** [comment]
Hey @klochowicz, congratulations, this issue has been accepted for TABConf 2023. It has been added to the official GitHub Project schedule. The builder Days tables will be on all day on September 6th and 7th

**Comment by wanyidaili** [comment]
Is there a schedule/agenda for this? Would love to know the start/end times. Thanks!

**Comment by iglesiasbrandon** [comment]
hey @wanyidaili this is a builder days project so it will be happening all day today and tomorrow. in the main stage room today you will see 'pods' for each of the builder days projects
