### ISSUE TITLE
DLCs on Lightning

### ISSUE THREAD

**Issue by klochowicz** [TABConf/2023.tabconf.com#101]
# Description

### What is this talk about? Give us as many details as possible. 

Discreet Log Contracts are a way of avoiding counterparty risk necessary when using centralised services, such as exchanges. Some DLC solutions exist currently for Layer-1, but not for the lightning network.
Meanwhile, lightning network has the potential to scale DLC applications in order to create viable solution for decentralised finance on Bitcoin.

This talk will give a quick overview of Discreet Log Contracts, adaptor signatures and their applications for creating binary options and futures.
Then we'll dig deeper into DLC adaptation for the Lightning Network.

### What would an attendee learn from this talk?

Attendees will learn about DLCs, challenges and solutions for bringing them into the lightning network, and have a sneak peak at their integration into our mobile wallet (10101).

### Is there anything folks should read up on before they attend this talk?

No prerequisite knowledge needed.

### Relevant Links

- [DLC whitepaper](https://adiabat.github.io/dlc.pdf)
- [DLC specification (in progress)](https://github.com/discreetlogcontracts/dlcspecs/)
- [DLC on lightning](https://medium.com/crypto-garage/dlc-on-lightning-cb5d191f6e64)

# About the Speaker

I am one of the core contributors to 10101 app ("ten-ten-one"), which brings DLC-powered self-custodial trading to Lightning.

Before this, I have been part of the team building [ItchySats](https://itchysats.network), a p2p derivative trading software that runs on your Umbrel/Raspiblitz.

# Social Links

- [Github](https://github.com/klochowicz)
- [Twitter](https://twitter.com/klochowicz)

# Talk Details

## Length of Talk

30 minutes

## Preferred Day/Time Slot

anytime.

**Comment by iglesiasbrandon** [comment]
hey @klochowicz thank you for submitting an issue for TABConf 2023! We are reviewing submitted issues and accepting some each week. Keep an eye on this issue in case someone asks questions!

**Comment by klochowicz** [comment]
I'm closing this issue as there's too little time to prepare anything should I get accepted last-minute. Will still do the Builder Day! 😊
