### ISSUE TITLE
Mempool and Policy

### ISSUE THREAD

**Issue by murchandamus** [TABConf/2023.tabconf.com#102]
# Description
### What is this talk about? Give us as many details as possible. 

I want to talk about how the relay of unconfirmed transactions works, what incentives and limitations are at work, and what we are trying to achieve with Mempool and Mempool Policy. I will go into network-wide and node-specific goals and concerns, general limitations, and proposals currently in development.

This talk will be based on the “Waiting for Confirmation” series Gloria Zhao and I have been putting out in the Bitcoin Optech newsletter for the past months.

### What would an attendee learn from this talk?

An attendee should learn why there is no such thing as “the mempool”, but how we are trying to get as close as possible to a thing as ‘’the mempool”, why mempool policies are much stricter than the consensus rules, and where the mempool is going from here.

### Is there anything folks should read up on before they attend this talk?

It’s probably helpful if you have ever sent some Bitcoin transactions and tried to figure out when one of them confirms to appreciate this talk. ;)

### Relevant Links

- [Waiting for Confirmation](https://bitcoinops.org/en/blog/waiting-for-confirmation/)
- [instagibbs’ mempool policy zoo](https://gist.github.com/instagibbs/ee32be0126ec132213205b25b80fb3e8)

# About the Speaker

Murch has been contributing to Bitcoin Stack Exchange for over ten years and working fulltime in the Bitcoin space since 2017. He contributes to Bitcoin Core, the Bitcoin Optech Newsletter and Recap, the Chaincode Podcast, and co-host BitDevs NYC. Sometimes he writes about the mempool weather on Twitter.

### Social Links

- [GitHub](https://github.com/murchandamus)
- [Twitter](https://twitter.com/murchandamus)
- [Stack Exchange](https://bitcoin.stackexchange.com/users/5406)
- [Website](https://murch.one)

# Talk Details
### Length of Talk

I was thinking 30 minutes (20 minutes + time for questions)

### Preferred Day/Time Slot

Preferably earlier in the conference. I’ll probably also contribute a bit to the Socratic Village, especially it would be nice if the talk wouldn’t be in parallel to the Socratic Seminar in the Socratic Village.

**Comment by murchandamus** [comment]
Note that this proposal is put forth based on my understanding that the instagibbs’s proposed talk (https://github.com/TABConf/2023.tabconf.com/issues/79) is likely going to be withdrawn.

**Comment by btsea** [comment]
@murchandamus We (Socratic Village) can work around the main stage scheduling. We will have a bunch of different Seminar events, so once you have an idea of when this talk will be, we can schedule the seminar accordingly.

**Comment by briimhd** [comment]
Thank you for submitting this talk proposal! We will change the tag to accepted when we go over new issues next week :)

**Comment by iglesiasbrandon** [comment]
hey @murchandamus, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The talks will be happening on September 8th and 9th; once we accept more, we will assign the day, time, and location.

We will do our best to accommodate the day/ time you asked for!

**Comment by instagibbs** [comment]
sorry I should have withdrawn mine a while ago, @murchandamus looking forward to a recording(??)

**Comment by iglesiasbrandon** [comment]
Hey @murchandamus , We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by murchandamus** [comment]
ack

**Comment by iglesiasbrandon** [comment]
Hey @murchandamus , closing this issue since this has been completed; thank you!
