### ISSUE TITLE
Fedimint Builder Day

### ISSUE THREAD

**Issue by m1sterc001guy** [TABConf/2023.tabconf.com#103]
# Description
### What is this project about? Please give us as many details as possible.
Fedimint is an open source protocol for creating a federation that allows members to transact bitcoin within a community with a strong foundation of privacy, By default, Fedimint supports the "ecash" module (allows members of the Fedimint to transact using ecash), the "wallet" module (allows members to peg-in/peg-out of the federation), and the "lightning" module (allows members to transact over the lightning network. But Fedimint is extensible and can be augmented to run many different applications in a federated manner.

### Is it a FOSS or Open Source project?
MIT

### What would an attendee learn from visiting this projects table at Builder Days?
An attendee would learn how to setup a development environment to get started contributing, learn how to deploy a fedimint (signet or regtest), and begin learning the module structure to start developing their own module.

### Is there anything people should read up on before finding the table at Builder Day?
Ideally nix and rust, but neither should be required if they just want to deploy a fedimint and learn how it works.

### Relevant Links
GitHub Repo: https://github.com/fedimint/fedimint/

# Project Details
### Who will run the table? Are those people current contributors or maintainers who can answer questions and get people onboarded? 
At least myself (m1sterc001guy) and Justin Moon will be there to answer questions and help people get setup.

**Comment by iglesiasbrandon** [comment]
Hey @m1sterc001guy,  congratulations, this issue has been accepted for TABConf 2023. It has been added to the official GitHub Project schedule. The builder Days tables will be on all day on September 6th and 7th!

**Comment by zapdrsurge** [comment]
would love to see a demonstration of a mint launch
