### ISSUE TITLE
Are Ordinals legit? 

### ISSUE THREAD

**Issue by Isabelfoxenduke** [TABConf/2023.tabconf.com#104]
Are Ordinals legit? 
With NiftyNei, SuperTestNet, George Kaloudis and Asher Corson

This panel is aimed to address common concerns and questions about the Ordinals protocol and inscriptions from a Bitcoin Maximalist perspective. Questions will focus on challenging topics related to Ordinals within the maximalist community—including the impacts of Ordinals on the fee market, mining, fungibility, and risks to retail investors. 

The goal of this talk is to explore this new technology through an open-minded yet critical lens—while intentionally highlighting diverse opinions in the Bitcoin Maximalist community.  

Suggested pre-viewing: [Ordinals Guy Goes to Therapy](https://www.youtube.com/watch?v=CdLl1o5A9Os)

-

Confirmed panelists include: NiftyNei, SuperTestNet, and others; Currently in talks with others in the BM community - please do reach out to discuss if this sounds like a fit for the conference!

Length of the panel discussion: 30-40 mins? Open to whatever makes sense
Preferred Day/Time Slot: preference for Friday or Saturday!

**Comment by Isabelfoxenduke** [comment]
Also, I can be reached most easily on Twitter for further discussion about this! @Isabelfoxenduke

**Comment by bodily11** [comment]
Ordinals is a meta-protocol on Bitcoin that provides the perfect place to experiment without changing Bitcoin. It uses Bitcoin as a full data availability layer and uses indexers (that anyone can run) on top to manage state.

There are hundreds of Bitcoin developers building in the Ordinals ecosystem, and I would love to see a panel on Ordinals at the conference.

**Comment by JakeBlockchain** [comment]
Definitly a fan of this idea. Ordinals has been a huge catalyst for attracting developers to Bitcoin.

**Comment by miketwenty1** [comment]
@Isabelfoxenduke we are figuring out the scheduling for tabconf right now, we will try to get back to you by end of week.

**Comment by Isabelfoxenduke** [comment]
> @Isabelfoxenduke we are figuring out the scheduling for tabconf right now, we will try to get back to you by end of week.

Thank you! Excited!

**Comment by iglesiasbrandon** [comment]
Hey @Isabelfoxenduke, congrats this panel has been accepted.

**Comment by Isabelfoxenduke** [comment]
Yay! So glad to hear that - can't wait!

**Comment by iglesiasbrandon** [comment]
Hey @Isabelfoxenduke , We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by Isabelfoxenduke** [comment]
Okay! Works for me! Just to confirm - Day 4 is Friday, correct?

**Comment by iglesiasbrandon** [comment]
@Isabelfoxenduke Day 4, is Saturday the 9th.

**Comment by Isabelfoxenduke** [comment]
got it - that works thank you!

**Comment by iglesiasbrandon** [comment]
hey @Isabelfoxenduke, closing this issue since this has been completed, thank you!
