### ISSUE TITLE
Anatomy of a Bitcoin Transaction

### ISSUE THREAD

**Issue by otech47** [TABConf/2023.tabconf.com#105]
# Description

### What is this talk about? Give us as many details as possible.

This talk is a technical introduction to the mechanics & composition of bitcoin transactions. We will cover topics like:

- Inputs and Outputs
- Locking scripts & unlocking scripts
- Common bitcoin scripts & their opcodes
- Transaction (de)serialization
- How to read block explorer details
- How did Segwit & Taproot change transactions
- WTF is an inscription and why
- What future BIPs are looking to change about transactions

### What would an attendee learn from this talk?

Attendees will learn about bitcoin transaction basics first and foremost.

However, there will be progression towards deeper technical topics such that folks who are already familiar with the basics can gain a more fundamental and/or reinforced understanding.

If you're a software engineer recently learning about bitcoin or just a casual tech-savvy Bitcoin OpTech reader, this talk is made specifically to help level up your understanding of how bitcoin transactions work.

Honestly for long-time/OG bitcoin devs this talk will be very vanilla as we won't go too much into the "bleeding-edge" of bitcoin development (maybe at the end if there is time but I'm sure there will be plenty of other fun talks on all that) but I figured there should be some of this standard/general bitcoin dev content for newer folks or just anyone who gets dizzy/overwhelmed from all the talks about awesome future improvements to bitcoin :)

### Is there anything folks should read up on before they attend this talk?

Murch has done at least 2 amazing talks on bitcoin transactions in the past so will be building off things like this: 
https://pretalx.com/adopting-bitcoin-2022/talk/HJT3VT/
https://www.youtube.com/watch?v=xmvxR0FTrVE

Chapters 6+7 of Mastering Bitcoin will also be helpful for the basics
https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch06.asciidoc
https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch07.asciidoc

### Relevant Links

# About the Speaker

Currently working full-time on the engineering team at Fedi

I am a software solutions engineer operating on a #bitcoin standard and focused on solving problems involving technology education, technical skills training, and FOSS development. Other interests include information theory, thermoeconomics, and construction.

Past talks:
https://pretalx.com/adopting-bitcoin-2022/speaker/ZG3DHJ/
https://twitter.com/advbitcoin/status/1628289737596276736

### Social Links
Github: https://github.com/otech47
Twitter: https://twitter.com/oz_21m
Website: http://setlife.solutions/

### Length of Talk
45-60 mins

### Preferred Day/Time Slot
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

Cannot do the 9th

Could also convert this to a workshop if desired

**Comment by miketwenty1** [comment]
This looks like a great talk.

**Comment by miketwenty1** [comment]
@otech47 it looks like this talk wasn't accepted are you still interested in doing this? we may have some break off opportunities for this.

**Comment by otech47** [comment]
@miketwenty1 sure I could still do this I just can't make it on the 9th

**Comment by miketwenty1** [comment]
@otech47 it seems this submission failed to get accepted this year, I appreciate the submission, I personally would of liked to see this talk! One of our big criteria for accepting talks is reputation and community involvement around a topic. We also sort and order issues by 👍 emojis as one way to help understand how many people are excited to see a various talk/panel/workshop. Please consider submitting another idea next year. We'll be accepting talks for TABConf 6 in about 5-6 months.
