### ISSUE TITLE
Multiparticipant (N>=2) Offchain Mechanisms

### ISSUE THREAD

**Issue by ZmnSCPxj-jr** [TABConf/2023.tabconf.com#107]
# Description
@cdecker probably knows most of this already.

### What is this talk about? Give us as many details as possible. 
First, I will discuss a hierarchy of types and sub-types (note: types are sets):

* Cryptocurrency System
  * Blockchain
  * Multiparticipant Offchain Mechanism
    * Channel
    * Channel Factory

I then focus on the type "Multiparticipant Offchain Mechanism".

While Channels are implemented already in the Lightning Network, the constructor of a Channel accepts a Blockchain (i.e. channels are hosted inside blockchains currently).  But in theory the Channel constructor can accept a Cryptocurrency System, a super-type of Blockchain; that is, a Channel can be hosted inside a Multiparticipant Offchain Mechanism, which is itself hosted in some Blockchain.  We call such a setup a "Channel Factory", but again this is simply a concrete implementation of Multiparticipant Offchain Mechanism that is tailor-made for a specific use-case (namely, taking a Blockchain and itself hosting multiple Channels).

Given that we have mechanisms like Poon-Dryja, Decker-Wattenhofer, and Decker-Russell-Osuntokun, can we instead define a separate Multiparticipant Offchain Mechanism super-type with specific concrete operations?

For example, current Poon-Dryja implementations "infect" their hosted HTLCs with the punishment mechanism (i.e. HTLCs are not simple "(A && preimage) || (B && timeout)" but are instead "(A && B && preimage) || (A && B && timeout)" with signature-based covenants).  We can, however, "rotate" our transaction structure so that we have a separately punishable transaction which hosts "plain" HTLCs.

Decker-Wattenhofer and Decker-Russell-Osuntokun are already in this "rotated" form.  This rotated form requires that participants pre-emptively shut down the mechanism ("unilaterally close") if an absolute timeout is approaching rather than when the timeout has arrived.

However, outputs hosted in such a mechanism (backed by Poon-Dryja, Decker-Wattenhofer, or Decker-Russell-Osuntokun) would be "plain" SCRIPTs, exactly similar to Bitcoin SCRIPT.  Thus, we can enforce any contact enforceable on a Blockchain, even though it is an offchain mechanism.  In case somebody breaks consensus inside the offchain mechanism, we simply destroy the mechanism and drop it onchain, where the Blockchain then performs actual enforcement. (Decker-Russell-Osuntokun signatures would all be "infected" with the `SIGHASH_ANYPREVOUT`, though)

For example, suppose there is a Multiparticipant Offchain Mechanism where you and I are both participants (i.e. we are one of the n-of-n signatories of the mechanism). I unilaterally own funds (i.e. SCRIPT is a singlesig of a pubkey whose privkey only I know) I can offer you an HTLC spending from those funds.  That HTLC would be a transaction spending from my unilateral output and creating the HTLC contract between us, plus any change I have.  I could send this transaction to you.  However, this transaction is "unconfirmed" and thus you would not want to give me the preimage.  This is equivalent to a "mempool" transaction.

We would then negotiate with the other signatories of the mechanism so that my current UTXO is deleted, and then my change UTXO and our shared HTLC are created, in a new state of the mechanism.  Once this is done, the HTLC is "confirmed" and you can safely send the preimage with the knowledge that if something bad happens, you can destroy the mechanism ("unilaterally close") and have the Blockchain enforce the HTLC.

This "confirmation" can be done more quickly than on the Blockchain, thus allowing for higher-speed transfers.

Of course, note that we have to negotiate with the other signatories in order to "confirm" the HTLC.  If we were the only two signatories (i.e. this is a 2-of-2 or a "Channel") then we do not need to worry as both of us interacting mean both of us are online, but if there are more signatories then we have the problem of interactivity and onlineness.  We can instead create multiple layers of such mechanisms, (i.e. a n > 2 n-of-n "Channel Factory" that hosts multiple "Channels") so that we can reduce the number of participants that need to be online for particular operations by limiting the number of participants for subsections of the monetary system.

All of this also allows for any arbitrary contract.  Thus, if there is a novel Blockchain opcode, it is (generally, though caveats may apply in detail) possible to also have that same opcode also operate inside a Multiparticipant Offchain Mechanism.

### What would an attendee learn from this talk?

The design of Lightning Network Channels and Channel Factories, and abstractions on how to think about these concrete objects.

### Relevant Links
* [Burchert-Decker-Wattenhofer Channel Factories](https://royalsocietypublishing.org/doi/pdf/10.1098/rsos.180089?ref=decred-magazine)
* [Decker-Wattenhofer Channels](https://tik-old.ee.ethz.ch/file/716b955c130e6c703fac336ea17b1670/duplex-micropayment-channels.pdf)
* [Poon-Dryja Channels](https://lightning.network/lightning-network-paper.pdf)
* [Decker-Russell-Osuntokun Channels](https://blockstream.com/eltoo.pdf)

# About the Speaker
Some random cat who wandered into the wrong subreddit and got suckered into buying Bitcoin.  Now a rabid smallblocking Lightning developer cat whose scratches will infect you with Lightning Network enthusiasm.

### Social Links
Github ZmnSCPxj-jr ZmnSCPxj
Twitter `@jxpcsnmz`
Website zmnscpxj.github.io

# Talk Details
### Length of Talk
20-30 minutes

### Preferred Day/Time Slot 
August 8

***absolutely do not work***: August 6 or 7.

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment]
hey @ZmnSCPxj-jr thank you for submitting an issue for TABConf 2023! We are reviewing submitted issues and accepting some each week. Keep an eye on this issue in case someone asks questions!

**Comment by ZmnSCPxj-jr** [comment]
If there is any interest here, I prefer August 8.

**Comment by niftynei** [comment]
@iglesiasbrandon I want this for the @base58btc village

**Comment by iglesiasbrandon** [comment]
hey @niftynei this has been added to the Base 58 Village.

**Comment by niftynei** [comment]
Thanks!

Timeslot is 12-12.30p Friday (Aug 8)

**Comment by iglesiasbrandon** [comment]
Hey @ZmnSCPxj-jr , We have added a day, time slot, length, and village to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/9

Please acknowledge by commenting 'ack'.

This will confirm your talk for the Base 58 Protocol Village at TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by iglesiasbrandon** [comment]
hey @ZmnSCPxj-jr can you ack?

**Comment by ZmnSCPxj-jr** [comment]
ack

**Comment by iglesiasbrandon** [comment]
Hey @ZmnSCPxj-jr I'm closing this issue since it's been completed! Thank you!
