### ISSUE TITLE
Target Nakamoto: A Proof-of-Work Protocol Modification to Improve Security and Limit Energy Consumption

### ISSUE THREAD

**Issue by DanielAronoff** [TABConf/2023.tabconf.com#108]
# Description

We focus on the tradeoff between cost and network security at different levels of mining hashrate:

-The cost of operating a PoW blockchain increases with hashrate

-The external costs ( electricity, carbon emissions) caused by PoW blockchains **increase** with hashrate

-The vulnerability of a PoW blockchain to an attack - which is a  cost - **decreases** with hashrate

Ideally, the protocol will balance these increasing and decreasing costs by honing in on a hashrate target

**Nakamoto Protocol**:  Hashrate is a function of the exchange value \$/BTC - no bounds

**Nakamoto Hashrate Limits**

lim_{BTC --> 0}hashrate} = 0, lim_{BTC--> \infty}\hashrate  = \infty

**Target Nakamoto:** modifies the Nakamoto protocol to hone in on a hashrate interval

### What is this talk about? Give us as many details as possible. 

We demonstrate that the Bitcoin consensus protocol can be modified to keep hashrate (H) inside a chosen interval, which can optimize over the increasing energy and climate costs and the decreasing security costs, as hashrate increases. Our approach relies on 2 key insights:

1. Puzzle difficulty is a sufficient statistic for (lagged) hashrate
2. The equilibrium hashrate is an increasing function of the e.g. dollar exchange value of the mining reward. 

We design a protocol that lowers the ceiling on the portion of the block reward sent to the miner when H > interval and increases the floor block reward when H < interval. This implies a portion of the reward can be withheld from the miner when hashrate is too high and can be supplemented when hashrate is too low. Long-term monetary policy is not affected if the withheld rewards balance the supplemented rewards over time. However, there are myriad technical/miner incentive issues that must be dealt with (which will be discussed in the talk). 

Target Nakamoto adheres to design constraints that address community values, including;

- No oracles
- No hard forks
- No interference in transactions and miner incentives to order transactions in blocks
- No interference in puzzle difficulty or blockchain growth rate

### What would an attendee learn from this talk?

The key takeaways are:

1. The Bitcoin consensus protocol can be modified to reduce energy consumption without making any change that violates community core values.
2. When the mining approaches zero there is an incentive problem arising from the fact that transactors do not have an incentive to pay for network security. Their only incentive is to pay for queuing position. Therefore, the mining fees will be too low to support the level of hashrate necessary for network security. Target Nakamoto  offers a way to address this looming problem.

### Is there anything folks should read up on before they attend this talk?

I hope to post the paper on ArXiv later this summer. 

### Relevant Links

# About the Speaker

My name is Daniel Aronoff.
I am a Research Scientist at the MIT Media Lab Digital Currency Initiative. 

I have published two peer reviewed books on the economic foundations of the 2008 global financial crisis. My research on digital currencies is focused on two areas. One area is game theoretic analysis of the consensus protocols that underlie cryptocurrencies and the design of new protocols to improve security.  The other area is the design of smart contracts to improve the performance of financial markets in environments where money and securities are appended to distributed ledgers. I received a BSc in Philosophy and Economics  with first class honors from the London School of Economics and a PhD in Economics from MIT.

### Social Links

Twitter
@danaronoff

Website
https://www.media.mit.edu/people/daronoff/projects/

https://www.leadmit.com/people
# Talk Details
### Length of Talk
1 hour
### Preferred Day/Time Slot 

Sept 8 or 9
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*
[PoW Cost Graph 1.pdf](https://github.com/TABConf/2023.tabconf.com/files/12098723/PoW.Cost.Graph.1.pdf)

**Comment by DanielAronoff** [comment]
Errata: In key takeaway 2 I mistakenly wrote When the mining approaches zero ". I meant to write "when the MINTING approaches zero".

**Comment by miketwenty1** [comment]
@DanielAronoff I see your plan is to publish a paper on this soon. Is this taking the assumption that the value of bitcoin priced in USD will not use Oracles when determining the hashrate interval?

**Comment by DanielAronoff** [comment]
That is correct. The puzzle difficulty signals the hashrate and the block reward paid to the miner is adjusted without any observation of the USD/BTC (or any other)exchange rate. The USD value of the block reward pushes up (compared to what it would be wo adjustment) when the block reward is increased and the opposite when the block reward is pushed down. The adjustment to hashrate operates thru the incentive faced by miners when the block reward changes value in whatever currency the mining costs are quoted in (USD, Yen, BTC…). The code does not require any external information to move the block reward in the right direction. All the necessary information is encoded in puzzle difficulty.

Sent from my iPhone

On Jul 19, 2023, at 11:25 PM, Michael Tidwell ***@***.***> wrote:

﻿

@DanielAronoff<https://github.com/DanielAronoff> I see your plan is to publish a paper on this soon. Is this taking the assumption that the value of bitcoin priced in USD will not use Oracles when determining the hashrate interval?

**Comment by miketwenty1** [comment]
@DanielAronoff it seems this submission failed to get accepted this year, I appreciate the submission. One of our big criteria for accepting talks is reputation and community involvement around a topic. We also sort and order issues by 👍 emojis as one way to help understand how many people are excited to see a various talk/panel/workshop. Please consider submitting another idea next year. We'll be accepting talks for TABConf 6 in about 5-6 months.
