### ISSUE TITLE
 Bitcoin Merkle Tree Flaws and Existent Mitigations for SPV clients

### ISSUE THREAD

**Issue by SergioDemianLerner** [TABConf/2023.tabconf.com#109]
# Description

The Bitcoin protocol has a flaw when validating consensus in SPV mode. There is a potential type confusion between Merkle tree middle and leaf nodes. This can lead to two kinds of attacks: leaf transactions that are incorrectly parsed as middle nodes, and middle nodes that are incorrectly parsed as transactions. The vulnerability was made public in 2018 but still it has not been fixed. Correctly implementing SPV wallets require adding additional protections against this protocol flaw.
With the proliferation of validating bridges between blockchain, many SPV clients embedded in smart contracts have been deployed, protecting millions of dollars in BTC. However, it seems that very few bridges have protections against the Bitcoin vulnerability. In fact, it was observed that some bridges weaken the verifications on transactions, leading to an expansion of the attack surface. 

### What is this talk about? Give us as many details as possible. 

In this talk we aim to provide the first comprehensive presentation of all the flaws of the Bitcoin Merkle tree design, the vulnerabilities that arise from these flaws, and the potential mitigations, both by changing Bitcoin and by adding specific checks to SPV wallets. 

### What would an attendee learn from this talk?

The talk is intended for any Bitcoin developer or technical user interested in cybersecurity, but is specially important for developers of Bitcoin SPV clients or Bitcoin bridges using optimistic or SNARK based SPV validation.  
### Is there anything folks should read up on before they attend this talk?

* The SPV Clients section of the Bitcoin white paper
### Relevant Links
* [Disclosure of the vulnerability](https://bitslog.com/2018/06/09/leaf-node-weakness-in-bitcoin-merkle-tree-design/)

* [Simplest solution found](https://bitslog.com/2018/08/21/simple-change-to-the-bitcoin-merkleblock-command-to-protect-from-leaf-node-weakness-in-transaction-merkle-tree/)

* [The code that protects the Rootstock bridge against these vulnerabilities]( https://github.com/rsksmart/bitcoinj-thin/blob/ab624f09a77e48e04542a06d4a392c952b86aff2/src/main/java/co/rsk/bitcoinj/core/PartialMerkleTree.java#L230)

* [A paper describing the different flaws](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/attachments/20190225/a27d8837/attachment-0001.pdf)

# About the Speaker

My name is Sergio Demian Lerner. I'm a bitcoiner, coder, software architect, computer security and cryptocurrency researcher and serial entrepreneur. 

I graduated in Computer Science from the University of Buenos Aires and I did my final thesis on [peer-to-peer poker](https://www.dc.uba.ar/academica/tesis-de-licenciatura/2010/lerner). By 2010 I was actively researching [anonymous payment systems](https://www.mail-archive.com/cryptography@metzdowd.com/msg11146.html), in order to combine a p2p currency with my p2p mental poker protocol. In [late 2011](https://bitslog.wordpress.com/2011/08/) I discovered Bitcoin and I began contributing to its design with ideas for improvement. 

In 2012 designed a new highly efficient cryptocurrency system, [MavePay](https://bitslog.files.wordpress.com/2012/04/mavepay1.pdf), based on Guy Fawkes signatures. During 2013 I worked on  [QixCoin, ](http://qixcoin.com/)the first Turing complete cryptocurrency to support my p2p gaming platform. I proposed multiple cryptocurrency protocols such as MAVEPAY (a precursor of [Joseph Bonneau](http://jbonneau.com/)’s  [FawkesCoin](http://www.jbonneau.com/doc/BM14-SPW-fawkescoin.pdf)), [P2PTradeX](https://bitcointalk.org/index.php?topic=91843.0) (the precursor of Blockstream’s [sidechains](https://blockstream.com/sidechains.pdf) and the [second proposed atomic swap method](https://en.bitcoin.it/wiki/Atomic_cross-chain_trading)), LIMIO, [the Tick method](https://bitcointalk.org/index.php?topic=307211.msg3308565#msg3308565) (a precursor of [Emin Gün Sirer’s Covenants](https://maltemoeser.de/paper/covenants.pdf)), the [OP_PUSHSIG](https://bitcointalk.org/index.php?topic=405200.msg5681780#msg5681780) opcode (a precursor of [Segwit](https://en.wikipedia.org/wiki/SegWit)), PAMBA, MinCen, MemoHash (a precursor of [Dan Boneh](http://crypto.stanford.edu/~dabo/)’s [Ballon Hashing](https://pdfs.semanticscholar.org/f49f/8e135695937bfe03e467e215177eec79d7dc.pdf), and the scheme chosen to be a key part in Ethereum’s ETHash design), [The Collision POW](https://bitslog.files.wordpress.com/2012/04/mavepay1.pdf) (a precursor of [zCash](https://z.cash/) [EquiHash](https://en.wikipedia.org/wiki/Equihash)), the [“ECDSA” attack](https://bitcointalk.org/index.php?topic=243607.0) (a precursor [Patrick McCorry](http://www0.cs.ucl.ac.uk/staff/P.McCorry/)’s of [“Smart Contract Bribing Miner”](http://homepages.cs.ncl.ac.uk/patrick.mccorry/minerbribery.pdf) attacks) and [BlockPad](https://bitslog.wordpress.com/2014/07/05/blockpad-improved-proof-of-work-function-with-descentralization-incentives/).  I also proposed the [first proof system for public file replication](https://bitslog.wordpress.com/2014/11/03/proof-of-local-blockchain-storage/), and later applied it in a smart-contract platform to [reward full nodes having a copy of the blockchain without TTP](https://www.youtube.com/watch?v=pioxtzPxQMg) ([cited by Cecchetti, Fisch & Miers](https://eprint.iacr.org/2018/684.pdf)), Also I found the [O(N^2) hashing vulnerability](https://bitslog.wordpress.com/2017/01/08/a-bitcoin-transaction-that-takes-5-hours-to-verify/) on Bitcoin, and later the [OP_IF and Rock-and-ROLL](https://bitslog.wordpress.com/2017/04/17/new-quadratic-delays-in-bitcoin-scripts/) efficiency problems, and the first [signature malleability](https://bitcointalk.org/index.php?topic=148109.0) attack. I designed the [CoVar scheme](https://bitcointalk.org/index.php?topic=147124.msg1561612#msg1561612) to improve the blockchain fee market (a precursor of [Basu, Easley, O’Hara, and Gün Sirer fee market scheme](https://arxiv.org/pdf/1901.06830.pdf)).

In mid-2013 I designed and prototyped the [Firmcoin](https://www.coindesk.com/firmcoin-a-new-physical-form-of-bitcoin/), a Bitcoin micro-controlled banknote for off-line payments (a precursor of the [OpenDime](https://opendime.com/) and [KongCash](https://kong.cash/)), and the [DagCoin cryptocurrency](https://bitslog.wordpress.com/2015/09/11/dagcoin/) (the precursor of [Byteball](https://byteball.org/) and IOTA coins). To prevent rogue hardware attacks I created the first [anti-covert channel](https://bitcointalk.org/index.php?topic=893898.msg9841502#msg9841502) ECDSA signature scheme, which was later analyzed and found secure by [Pieter Wuille](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2020-March/017667.html) (nowadays a similar technique is used by the [Jade](https://medium.com/blockstream/anti-exfil-stopping-key-exfiltration-589f02facc2e) hardware wallet). Later I designed the [DECOR+ protocol](https://bitslog.wordpress.com/2014/05/02/decor/) as a proposal to scale Bitcoin to a 5-second block interval. In 2014 I discovered [ASICBoost](https://www.asicboost.com/) and published a second ASIC optimization technique: using [approximate adders](https://bitslog.wordpress.com/2015/02/17/faster-sha-256-asics-using-carry-reduced-adders/). This technique was later rediscovered and published by scientists from the [University of Illinois](http://rakeshk.crhc.illinois.edu/dac_16_cam.pdf).
 
In 2013 I discovered a hidden pattern in the blocks mined during the early Bitcoin years, which led to the now widely believed [hypothesis](https://bitslog.wordpress.com/2013/04/17/the-well-deserved-fortune-of-satoshi-nakamoto/) that Satoshi owns 1.1M Bitcoins. Since that initial publication, this research has been replicated by other scientists ( [2013](https://bitslog.com/2013/04/17/the-well-deserved-fortune-of-satoshi-nakamoto/), [2013, ](https://bitslog.com/2013/04/24/satoshi-s-fortune-a-more-accurate-figure/)[2013](https://bitslog.com/2013/09/03/new-mystery-about-satoshi/), [2013](https://bitslog.com/2013/09/04/satoshi-machine-one-mystery-is-solved-and-another-opens/), [2014](https://bitslog.com/2014/04/03/chain-archeology/), [2014](https://bitslog.com/2014/06/23/july-2009-mistery-solved/), [2014](https://bitslog.com/2014/06/19/how-you-will-not-uncover-satoshi/), [2019)](https://bitslog.com/2019/04/16/the-return-of-the-deniers-and-the-revenge-of-patoshi/).

In 2015 I designed the [RSK Smart Contract platform](https://eprint.iacr.org/2022/684)  (a.k.a. [Rootstock](https://www.rootstock.io/)) and then co-founded [RSK Labs](https://www.coindesk.com/smart-contract-1-million-bitcoin-rootstock/), the company that developed and launched the platform. Rootstock included the first cross-chain communication system based on SPV-proofs (cited by SoK paper by [Zamyatin](https://eprint.iacr.org/2019/1128.pdf) et al.). For Roostock, I created more than 100 [RSKIPs ](https://github.com/rsksmart/RSKIPs)(RSK Improvement Proposals). 

Also I created the first [Bitcoin drivechain BIP](https://github.com/rsksmart/bips/blob/master/BIP-R10.md) in order to increase the capabilities of Bitcoin (the currency) using sidechains without increasing Bitcoin block size, and in 2017 I presented an [improved BIP](https://github.com/rsksmart/bips/blob/master/BIP-R11.md). 
In 2020 I created [Syncchains](https://docs.rsk.co/SyncChain_WP.pdf), a new type of sidechain that is protected by design from double-spend attacks to its two-way-peg, and also performs peg-ins and peg-outs in a few confirmation blocks. Additionally I created the Universal Merge Mining Protocol, to enable other blockchains to merge-mine with Bitcoin, the [Flyover repayment protocol](https://eprint.iacr.org/2023/086), to enable faster BTC transfers between Bitcoin and RSK, the [Safe Fork-aware Merge-mining Protocol](https://medium.com/iovlabs-innovation-stories/modern-merge-mining-f294e45101a0) to improve the RSK merge-mining security, the Nakamore consensus system, to improve the decentralization of Bitcoin. 

### Social Links
Github: @SergioDemianLerner
Twitter: @SDLerner
Website: bitslog.com

# Talk Details
### Length of Talk

1 hour.
### Preferred Day/Time Slot 

Not specified at this time.

**Comment by iglesiasbrandon** [comment]
hey @SergioDemianLerner thank you for submitting an issue for TABConf 2023! We are reviewing submitted issues and accepting some each week. Keep an eye on this issue in case someone asks questions!

**Comment by SergioDemianLerner** [comment]
Any news?

**Comment by dulcedu** [comment]
Woow! It will be amazing to have Sergio Lerner, he is one of the most technical people in Bitcoin, yes he did found RSK but he also was on of the first bitcoin contributors his finding in Bitcoin Core bugs and vulnerabilities. If we can bring Sergio to the Bitcoin community  again it will be amazing. His presence in the event and in all the cryptographic talks  would be incredible valuable for the high level knowledge he has. 

https://bitslog.com/2018/06/09/leaf-node-weakness-in-bitcoin-merkle-tree-design/

**Comment by iglesiasbrandon** [comment]
hey @SergioDemianLerner we have not picked this issue up for the main stage yet but it might get picked up from one of the villages. They will comment on the issue if they have any questions.

**Comment by niftynei** [comment]
Hey @iglesiasbrandon I'd love to have this on the @base58btc protocol village stage.

Current timeslot is 3.30 - 4.30p on Saturday.

**Comment by iglesiasbrandon** [comment]
Hey @SergioDemianLerner , We have added a day, time slot, length, and village to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/9

Please acknowledge by commenting 'ack'.

This will confirm your talk for the Base 58 Protocol Village at TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by SergioDemianLerner** [comment]
Thank you! I can't confirm now my presence, but I'll confirm in a few days.

**Comment by iglesiasbrandon** [comment]
sounds good just let us know @SergioDemianLerner

**Comment by miketwenty1** [comment]
@SergioDemianLerner I hope you can come this is a very interesting topic. Socratic Bitdevs or Base58 Protocol village may want to pick up quick if you can confirm.

**Comment by SergioDemianLerner** [comment]
Because of the short notice for the confirmation of my talk, I made conflicting arrangements. Is it possible to move my talk to any day before (7th or 8th) so I can leave Atlanta on the 8th night ?

**Comment by SergioDemianLerner** [comment]
?

**Comment by SergioDemianLerner** [comment]
?

**Comment by SergioDemianLerner** [comment]
?

**Comment by SergioDemianLerner** [comment]
?

**Comment by SergioDemianLerner** [comment]
?

**Comment by SergioDemianLerner** [comment]
?

**Comment by iglesiasbrandon** [comment]
hey @SergioDemianLerner we need to wait on @niftynei  to add a comment because this is her village. I will ping her about this now.

**Comment by iglesiasbrandon** [comment]
Hey @SergioDemianLerner does 9-10 AM on Friday work for you?

**Comment by niftynei** [comment]
hi apologies for the delay, i was traveling last week.

There's a 9a-10a slot available on the schedule on day 3

**Comment by SergioDemianLerner** [comment]
For me, anything on day 3 is much better.

**Comment by SergioDemianLerner** [comment]
Is it confirmed on day 3 then ?

**Comment by iglesiasbrandon** [comment]
ill go ahead and move it to that slot ( Day 3 from 9 AM to 10 AM ET. @SergioDemianLerner @niftynei

**Comment by iglesiasbrandon** [comment]
Hey @SergioDemianLerner, I am closing this issue since it's completed. Thank you for all of the effort you put into it!
