### ISSUE TITLE
Create your first lightning plugin for eclair

### ISSUE THREAD

**Issue by t-bast** [TABConf/2023.tabconf.com#11]
# Description

### What is this workshop about? Provide as many details as possible. 

Eclair is one of the main lightning implementations, but it's also the one people generally know the least about.
Eclair has a lot to offer, especially for large nodes that want to easily handle a high volume of payments.
But large nodes generally want to add custom features to their lightning node, tailored to their specific use-case.
This is where plugins shine, when they are easy to develop and maintain.
Eclair lets developers create very powerful plugins that can deeply interact with their lightning node.

In this workshop, we will implement an eclair plugin that lets participants receive Bolt 12 payments.
Participants will then be able to work on their own eclair plugin with my help (if we still have time).

### What would an attendee learn from this workshop?

- Basics about the eclair architecture
- How to run eclair with plugins
- How to write plugins for eclair

### Is there anything attendees should read up on before they attend this talk?

We wrote a blog post explaining the architecture behind eclair: https://acinq.co/blog/eclair-architecture
I also presented this topic at Tabconf 2022: https://www.youtube.com/watch?v=VWq_TxQUehI
They are a good introduction to eclair, and I recommend participants to have a look at it before the workshop.

### Is there anything attendees should set up before the workshop?

Attendees should be able to run eclair on their machine as explained [here](https://github.com/ACINQ/eclair/blob/master/BUILD.md).
We recommend setting up a development environment using [IntelliJ](https://www.jetbrains.com/idea/) with the [Scala plugin](https://plugins.jetbrains.com/plugin/1347-scala).

Attendees should also clone the [eclair-plugins](https://github.com/ACINQ/eclair-plugins) repository and make sure they're able to compile it with `mvn package`.

### Relevant Links

- https://github.com/ACINQ/eclair
- https://github.com/ACINQ/eclair-plugins

# About the Speaker

I very actively contribute to eclair and the lightning specification.

### Social Links

Github: https://github.com/t-bast/
Twitter: https://twitter.com/realtbast
Website: https://acinq.co/

# Workshop Details

### Length of workshop

1-2 hours (flexible in length, depending on whether attendees have ideas for plugins they'd like to create)

### Preferred Day/Time Slot 

None.

**Comment by iglesiasbrandon** [comment]
Hey, @t-bast, thank you for submitting a workshop issue for TABConf 2023! As we get closer to the conference, we will review all the issues, and the chosen ones will be added to the TABConf 2023 schedule: https://github.com/orgs/TABConf/projects/1.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions about your issue. Also, please update the issue description if you'd like to add anything else as we get closer to the conf.

**Comment by iglesiasbrandon** [comment]
Hey @t-bast, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The workshops will be happening on September 6th and 7th; once we accept some more, we will assign the day, time, and location.

**Comment by t-bast** [comment]
Neat, it's going to be fun!

**Comment by iglesiasbrandon** [comment]
Hey @t-bast , We have added a day, time slot, and length to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/4

Please acknowledge by commenting 'ack'.

This will confirm your workshop for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by t-bast** [comment]
ACK, thanks!

**Comment by miketwenty1** [comment]
@t-bast 

We are about a week away from the start of the conference. I'm sending this to all accepted upcoming workshop. Please review and ensure you have a clear, up to date, high level, agenda on this GitHub issue. Please buffer in time to help with unexpected problems and questions.

TABConf workshops should aim to involve high levels participation. If you're planning to conduct a live demo, please consider that attendees will require clear instructions on how to prepare for following along, (all steps for setup should be double checked) and any presentation should be structured accordingly.
Participants should leave the workshop either with something built, (be it physical or digital), or with specific knowledge gained from the __hands on/interactive__ experience.

**Comment by t-bast** [comment]
Done!

**Comment by iglesiasbrandon** [comment]
Hey @t-bast, I am closing this issue since you have completed the workshop. Thank you for all of the effort you put into it!
