### ISSUE TITLE
Empowering Communities: The Significance of Bitcoin Third Spaces and Your Role in Their Growth

### ISSUE THREAD

**Issue by rodbitkite** [TABConf/2023.tabconf.com#111]
# Description
### What is this talk about? Give us as many details as possible. 
Bitcoin Park is a community supported campus in Nashville, TN USA focused on grassroots bitcoin adoption and a home for bitcoiners to work, learn, collaborate, and build.

What is a Third Space? From the Brookings article _Third Places as Community _Builders__ "They are locations where we exchange ideas, have a good time, and build relationships." https://www.brookings.edu/articles/third-places-as-community-builders/

This presentation will be focused on:
- the importance of creating and maintaining a Bitcoin Third Space in your local community
- from experience, the do's and don'ts of creating and maintaining a Bitcoin Third Space 
- the types of people involved in creating, building, and maintaining - hint: it is never just one person and confident that each person regardless of their skillset or economic means can contribute 
- a checklist and resources of how to get started

Please comment with any questions and I will do my best to answer beforehand and/or include in the presentation. 

Thank you in advance for your help and consideration. 

### What would an attendee learn from this talk?

Why Bitcoin Park's probability for success is 1 in 1,000 (or maybe worse) and why even with those terrible odds, you should give it a shot.

### Is there anything folks should read up on before they attend this talk?

They should either attend their local bitcoin meetup or begin thinking of starting their own bitcoin meetup. Hint: starting your own bitcoin meetup is step 1. 

### Relevant Links

# About the Speaker
[Rod](https://primal.net/rod) [@bitkite](https://twitter.com/bitkite) is the Co-Founder of Bitcoin Park.

### Social Links
Nostr - [bitcoinpark.com/rod](https://primal.net/rod)
Twitter - [twitter.com/bitkite](https://twitter.com/bitkite)
Twitter - [twitter.com/bitcoinpark_](https://twitter.com/bitcoinpark_)
Website - [bitcoinpark.com](https://bitcoinpark.com) 

# Talk Details
### Length of Talk 

15 or 30 minutes with 15 or 30 minutes of Q&A ideally

### Preferred Day/Time Slot 
Any date and time that works best, I will work to accommodate. It would be cool if we can record the presentation so I can share with specific people who have asked how they can start their own Bitcoin Park in their local community. 

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by thrillerxx** [comment]
It would be wonderful to engage in a conversation on this subject. Rod and his team at Bitcoin Park have provided PlebLab with invaluable remote assistance, offering insight and guidance on ensuring these Bitcoin hubs' long-term sustainability.

**Comment by EthnTuttle** [comment]
+1

**Comment by reez** [comment]
+1 would love to see this!

**Comment by shawnyeager** [comment]
Bullish on @rodbitkite.⚡️

**Comment by john-zaprite** [comment]
Communities are a super important part of this space. This would be a great talk.

**Comment by harry-bitcoinpark** [comment]
This would be a very valuable topic to see at TABConf this coming year. Could you talk a little about 3rd space product market fit? What has that looked like historically in other industries or eras? What does that look like for Bitcoin Park? And what signs should organizers look for in their own third space?

**Comment by wiz** [comment]
yes we need more rod talks

**Comment by upjohnc** [comment]
+1
As one who has benefited from Bitcoin Park, I upvote this talk.  The benefit of the Park to me has been my understanding of bitcoin and how to use it.  Additionally, I have become a better explainer of bitcoin to friends.

**Comment by reallifeck** [comment]
Love this topic. We need more 3rd places for Bitcoin!

**Comment by wds4** [comment]
I love that Nashville has Bitcoin Park! As one of the Park's cofounders and chief architects, @rodbitkite has lots of wisdom and experience to share with others who wish to build and support similar spaces in other towns and cities. lfg! 🚀

**Comment by ltngstore** [comment]
Would be great to see this!

**Comment by iglesiasbrandon** [comment]
21 👍 6 ❤️ 10 🚀 and 15 comments! you all have spoked! 
@rodbitkite this issue has been accepted for TABConf 2023.

**Comment by iglesiasbrandon** [comment]
Hey @rodbitkite , We have added a day, time slot, and length to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by iglesiasbrandon** [comment]
@rodbitkite can you ack this issue, please?

**Comment by rodbitkite** [comment]
ack

**Comment by iglesiasbrandon** [comment]
Closing this issue!
