### ISSUE TITLE
How do wallets work?

### ISSUE THREAD

**Issue by craigraw** [TABConf/2023.tabconf.com#112]
# Description

### What is this workshop about? Give us as many details as possible. 

This workshop is a technical journey through the creation of a bitcoin wallet, receiving and sending transactions, and considerations over the longer term. By doing a walkthrough using Sparrow Wallet, the following common concepts will be explained from a technical standpoint:

- Seeds
- Derivation paths
- Script types
- Addresses
- Gap limits
- UTXOs
- Transaction construction
- Broadcasting
- RBF & CPFP
- Privacy considerations

### What would an attendee learn from this workshop?

Even though many of the concepts above regularly come up, they are often not well understood technically. Understanding how a modern HD wallet works improves security and reduces stress.

### Is there anything folks should read up on before they attend this workshop?

Nothing required.

### Is there anything attendees should set up before the workshop?

Attendees should ensure they have installed Sparrow Wallet on their laptop. Download from https://sparrowwallet.com/download/ and follow the steps to verify the file before installing.

Also ensure you are connected to the internet.

### Relevant Links

# About the Speaker

Developer of Sparrow Wallet

### Social Links
https://github.com/craigraw
https://twitter.com/craigraw
https://sparrowwallet.com

# Talk Details
### Length of Talk
45-60 minutes

### Preferred Day/Time Slot 
Mornings preferred, not available on the 6th.

**Comment by iglesiasbrandon** [comment]
hey @craigraw thank you for submitting an issue for TABConf 2023! We are reviewing submitted issues and accepting some each week. Keep an eye on this issue in case someone asks questions!

Would you be interested in making this a technical interactive workshop instead of a talk? It seems like this topic might be a good candidate for a workshop.

**Comment by craigraw** [comment]
Yes I think that format could work too. In that case, I'd prefer the requirement that attendees have Sparrow Wallet installed so we can jump straight into the topics.

**Comment by iglesiasbrandon** [comment]
Sounds great! @craigraw, ill convert this to a workshop! 
Can you update the description of the issue with that requirement so that attendees can be ready when they attend the workshop?

**Comment by craigraw** [comment]
No problem, updated :)

**Comment by craigraw** [comment]
Just noting again that I can't do the 6th - the schedule currently has this workshop as the first on Day 1.

**Comment by iglesiasbrandon** [comment]
@craigraw thank you for the reminder! i just swapped you over to day 2 !

**Comment by iglesiasbrandon** [comment]
Hey @craigraw , We have added a day, time slot, and length to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/4

Please acknowledge by commenting 'ack'.

This will confirm your workshop for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by craigraw** [comment]
Ack

**Comment by miketwenty1** [comment]
@craigraw 

We are about a week away from the start of the conference. I'm sending this to all accepted upcoming workshop. Please review and ensure you have a clear, up to date, high level, agenda on this GitHub issue. Please buffer in time to help with unexpected problems and questions.

TABConf workshops should aim to involve high levels participation. If you're planning to conduct a live demo, please consider that attendees will require clear instructions on how to prepare for following along, (all steps for setup should be double checked) and any presentation should be structured accordingly.
Participants should leave the workshop either with something built, (be it physical or digital), or with specific knowledge gained from the __hands on/interactive__ experience.

**Comment by iglesiasbrandon** [comment]
Hey @craigraw , I am closing this issue since you have completed the workshop. Thank you for all of the effort you put into it!
