### ISSUE TITLE
Building a wallet with BDK 1.0

### ISSUE THREAD

**Issue by notmandatory** [TABConf/2023.tabconf.com#113]
# Description

### What is this project about? Please give us as many details as possible.

For this builder day project I will show you how to build a simple descriptor based wallet using Rust and the new BDK 1.0 APIs. The primary improvement in 1.0 APIs (currently in alpha release) is the ability to sync your wallet database asynchronously in a different thread than the one used for the rest of the wallet operations. We will use testnet or signet so no mainnet bitcoins will be harmed. 

### Is it a FOSS or Open Source project?

Yes, BDK is licensed Apache 2.0 or MIT, at your option.

### What would an attendee learn from visiting this projects table at Builder Days?

1. creating a BDK wallet with an esplora blockchain data client and flat file database.
2. creating a single signature output descriptor for external and internal wallet scripts.
3. generating a new deposit address.
4. syncing the wallet asynchronously with a bitcoin test blockchain.
5. viewing the wallet balance and transactions.
6. creating and signing a PSBT to spend from the wallet.
7. broadcasting the transaction from a signed and finalized PSBT.

### Is there anything people should read up on before finding the table at Builder Day?

1. you should know [rust](https://www.rust-lang.org/tools/install) well enough to have your dev environment setup and be able to create a small binary project.
2. read up on how to use the [Tokio async runtime](https://tokio.rs/tokio/tutorial).
3. understand bip32 key derivation and paths.
4. understand what bitcoin output descriptors and miniscript are.
5. look at the existing [bdk 1.0 alpha](https://docs.rs/crate/bdk/1.0.0-alpha.1) documentation.
6. look at the existing [bdk 1.0 examples](https://github.com/bitcoindevkit/bdk/tree/master/example-crates/wallet_esplora_async).

### Relevant Links

GitHub Repo: https://github.com/bitcoindevkit/bdk

# Project Details

### Who will run the table? Are those people current contributors or maintainers who can answer questions and get people onboarded?

Running table: [Steve Myers](https://github.com/notmandatory)
Contributor and/or maintainer: Yes
Can answer on-boarding questions: Most of the time

**Comment by notmandatory** [comment]
This could also be a workshop, I'll be in ATL all three days.

**Comment by iglesiasbrandon** [comment]
hey @notmandatory it's up to you, 

Builder Day Projects take place all of day 1 and 2, and it's more casual. People will come to your dedicated table and learn about the project and how to get involved with BDK. A Workshop is a specific time slot 60-120 minutes to have a hands-on interactive experience.

Let me know what direction you want to take!

**Comment by notmandatory** [comment]
@iglesiasbrandon, thanks, if I can also do it on day 1 or 2 as a Workshop I'll do that.

**Comment by iglesiasbrandon** [comment]
how much time will you need for the workshop @notmandatory ?

**Comment by notmandatory** [comment]
A 90 min slot would be great, but could fit it in to 60 mins if needed.

**Comment by iglesiasbrandon** [comment]
Hey @notmandatory , We have added a day, time slot, and length to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/4

Please acknowledge by commenting 'ack'.

This will confirm your workshop for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by iglesiasbrandon** [comment]
bump @notmandatory i need you to ack

**Comment by notmandatory** [comment]
sorry just saw the note, ACK for day 1, 4:00-5:30p

**Comment by miketwenty1** [comment]
@notmandatory 

We are about a week away from the start of the conference. I'm sending this to all accepted upcoming workshop. Please review and ensure you have a clear, up to date, high level, agenda on this GitHub issue. Please buffer in time to help with unexpected problems and questions.

TABConf workshops should aim to involve high levels participation. If you're planning to conduct a live demo, please consider that attendees will require clear instructions on how to prepare for following along, (all steps for setup should be double checked) and any presentation should be structured accordingly.
Participants should leave the workshop either with something built, (be it physical or digital), or with specific knowledge gained from the __hands on/interactive__ experience.

**Comment by notmandatory** [comment]
I recommend anyone interested in this workshop also attend @tcharding's at 1pm.

Docs for this workshop are:
https://notmandatory.github.io/tabconf2023-bdk1-book/tutorials/wallet_async_esplora.html

Example repo for anyone who wants to follow along without the copy/pasta from above is:
https://github.com/notmandatory/tabconf2023-bdk1-workshop

**Comment by iglesiasbrandon** [comment]
Hey @notmandatory , I am closing this issue since you have completed the workshop. Thank you for all of the effort you put into it!
