### ISSUE TITLE
RoninDojo Builder Day

### ISSUE THREAD

**Issue by s2l1** [TABConf/2023.tabconf.com#115]
# Description
### What is this project about? Please give us as many details as possible.

The RoninDojo project has a strong focus on bitcoin privacy and sovereignty. 

We believe in providing a private, secure way for individuals to be their own bank, without trusting third party providers. Anyone should have the ability to use bitcoin privately.

We help users achieve this goal with plug n play bitcoin full node software and hardware.

### Is it a FOSS or Open Source project?

Yes we are FOSS.

### What would an attendee learn from visiting this projects table at Builder Days?

An attendee would learn how they can contribute to our open source project, dive into our software stack, easily build and spin up nodes, and so much more related to bitcoin privacy.

### Is there anything people should read up on before finding the table at Builder Day?

We always suggest learning the basics of how bitcoin works before diving into nodes and bitcoin privacy. If you want to learn more about what the RoninDojo software stack can do then see our wiki below.

### Relevant Links
GitHub Repo:
 
https://code.samourai.io/ronindojo/RoninDojo
*Note we use gitlab instead

https://wiki.ronindojo.io

https://ronindojo.io

# Project Details
### Who will run the table? Are those people current contributors or maintainers who can answer questions and get people onboarded?

1 or 2 of our core team members will run the table.

**Comment by iglesiasbrandon** [comment]
Hey @s2l1 congratulations, this issue has been accepted for TABConf 2023. It has been added to the official GitHub Project schedule. The builder Days tables will be on all day on September 6th and 7th!

**Comment by s2l1** [comment]
Wonderful will let everyone know and start making plans, thank you!
