### ISSUE TITLE
miniSTARK: Implement your own zero-knowledge proofs

### ISSUE THREAD

**Issue by andrewmilson** [TABConf/2023.tabconf.com#116]
# miniSTARK: Implement your own zero-knowledge proofs
### What is this workshop about?
This workshop is a hands-on introduction to proof systems. Using [miniSTARK](https://github.com/andrewmilson/ministark) you can prove the integrity of arbitrary computations to anyone using the power of [STARKs](https://starkware.co/stark/). 

### What would an attendee learn from this workshop?
Attendees will learn:
- How to implement a basic zero-knowledge proof in the Cairo language
- How to prove the program using the miniSTARK prover,
- How to verify the resulting proof
- How to apply the ZeroSync library to generate custom Bitcoin proofs and how to integrate them into their own applications
- Finally, attendees get an introduction on using recursive proofs

### Is there anything attendees should read up on before they attend this talk?
- [Introduction to Cairo](https://www.cairo-lang.org/docs/0.12.0/index.html)

### Is there anything attendees should set up before the workshop?
- [Install the Cairo language (v0.12 !)](https://www.cairo-lang.org/docs/0.12.0/quickstart.html)
- [Install miniSTARK](https://github.com/andrewmilson/ministark)

### Relevant Links
- [Talk: Provers for Consumers](https://www.youtube.com/watch?v=FF7RJF2hI50)
- [Anatomy of a STARK](https://aszepieniec.github.io/stark-anatomy/)
- [Cairo Whitepaper Redux](https://www.youtube.com/watch?v=DTVn0oYLVsE)

# About the Speaker
Andrew Milson is the creator of miniSTARK and Sandstorm. Prior to this Andrew worked as a Software Engineer at Google. 
Recently, he joined the [ZeroSync](https://zerosync.org) project to help them customize miniSTARK for Bitcoin proofs.

### Social Links
- [Github](https://github.com/andrewmilson/ministark)
- [Twitter](https://twitter.com/andrewmilson)
- [Ask questions in the ZeroSync Telegram group](https://t.me/zerosync_chat)

# Workshop Details
### Length of workshop
90 mins

### Preferred Day/Time Slot 
-

**Comment by iglesiasbrandon** [comment]
Hey @andrewmilson , We have added a day, time slot, and length to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/4

Please acknowledge by commenting 'ack'.

This will confirm your workshop for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by miketwenty1** [comment]
@andrewmilson please ack here.

We are about a week away from the start of the conference. I'm sending this to all accepted upcoming workshop. Please review and ensure you have a clear, up to date, high level, agenda on this GitHub issue. Please buffer in time to help with unexpected problems and questions.

TABConf workshops should aim to involve high levels participation. If you're planning to conduct a live demo, please consider that attendees will require clear instructions on how to prepare for following along, (all steps for setup should be double checked) and any presentation should be structured accordingly.
Participants should leave the workshop either with something built, (be it physical or digital), or with specific knowledge gained from the __hands on/interactive__ experience.
