### ISSUE TITLE
OpenSats: Supporting the Open Source infra of tomorrow

### ISSUE THREAD

**Issue by niftynei** [TABConf/2023.tabconf.com#117]
# Description
### What is this panel discussion about? Please give us as many details as possible. 

OpenSats recently announced our first set of grant recipients. Let's talk to them plus some board members about what we're funding, what work we're contributing to bitcoin, and how your open source project can look for getting grant money.

### What would an attendee learn from this talk?
What OpenSats is interested in funding, what the grant money is going towards, what grant recipients from our first round are working on.

### Is there anything folks should read up on before they attend this talk?
OpenSats! https://opensats.org

https://opensats.org/blog/bitcoin-grants-july-2023

### Relevant Links

# About the panelist
### Social Links
Panel to be run by OpenSats board members Dread @islandbitcoin + @niftynei and grant recipients Tony G @TonyGiorgio from MutinyWallet , Robin Linus @RobinLinus from ZeroSync, Dustin of Splicing @ddustin, and Dan Gould @dangould of PayJoins

# Panel Discussion Details
### Length of the panel discussion
45m - 1h

### Preferred Day/Time Slot 
Saturday, 1p (but definitely flexible!)

**Comment by niftynei** [comment]
@iglesiasbrandon I want this for the @base58btc village :)

**Comment by iglesiasbrandon** [comment]
Hey @niftynei added!

**Comment by niftynei** [comment]
Timeslot is 12:45p - 1.30p Friday

**Comment by iglesiasbrandon** [comment]
Closing this issues since it's completed!
