### ISSUE TITLE
b/acc

### ISSUE THREAD

**Issue by niftynei** [TABConf/2023.tabconf.com#118]
# Description
### What is this talk about? Give us as many details as possible. 
b/acc: bitcoin accelerationism

A talk about bitcoin, alpha, and where the next "constant alpha" games might exist in the bitcoin ecosystem.

### What would an attendee learn from this talk?
What accelerates protocols, projects, industries? We'll do a high-level discussion of "constant alpha" and how it applies to the bitcoin ecosystem at large.

### Is there anything folks should read up on before they attend this talk?
No? e/acc is still in the news?

fwiw the deck for the talk is already available here: https://docs.google.com/presentation/d/1sBErKKAy5PCx3KmLqlhTQ9ghKyn-NxxLfllNNjwg_DM/edit#slide=id.p

# About the Speaker

@niftynei is a long time LN contributor and shitposter. She also runs a bitcoin protocol school, @base58btc. Check out their classes on Udemy and in-person; now accepting signups for the TABConf Taproot class: https://base58.school/classes/taproot

### Social Links
Github: @niftynei
Twitter: https://twitter.com/niftynei
Website: https://base58.school

# Talk Details
### Length of Talk
30m

### Preferred Day/Time Slot 
Friday at 12 noon

**Comment by iglesiasbrandon** [comment]
Closing this issue!
