### ISSUE TITLE
Dual funding, liquidity ads and splicing: a game changer for lightning node operators

### ISSUE THREAD

**Issue by t-bast** [TABConf/2023.tabconf.com#12]
# Description

### What is this talk about? Give us as many details as possible. 

Lightning node operators constantly need to make decisions about where to allocate or reallocate their liquidity.
All of these choices cost on-chain fees because their require making on-chain transactions.
Running a lightning node is a very competitive open market (which is a good thing): node operators using sub-optimal allocation and paying higher on-chain costs will thus not be economically sustainable.

Lightning protocol developers have been working for many years on several improvements to on-chain efficiency and liquidity reallocation:

- [dual funding](https://github.com/lightning/bolts/pull/851)
- [liquidity ads](https://github.com/lightning/bolts/pull/878)
- [splicing](https://github.com/lightning/bolts/pull/863)

In this talk, we will explain what each of these features do and why they are a real game-changer for node operators.
We will also detail the state of development in each implementation.
We will also explain the impacts these features will have on mobile wallets.

### What would an attendee learn from this talk?

What these features they've been hearing about for a while actually do, why they're crucial for node operators, and when they can expect to use them on mainnet.

### Is there anything folks should read up on before they attend this talk?

No.

### Relevant Links

- [dual funding](https://github.com/lightning/bolts/pull/851)
- [liquidity ads](https://github.com/lightning/bolts/pull/878)
- [splicing](https://github.com/lightning/bolts/pull/863)

# About the Speaker

I am one of the protocol developers working on these features, both at the specification level and the implementation level.

### Social Links

Github: https://github.com/t-bast/
Twitter: https://twitter.com/realtbast
Website: https://acinq.co/

# Talk Details

### Length of Talk

30 minutes.

### Preferred Day/Time Slot 

None.

**Comment by iglesiasbrandon** [comment]
Hey, @t-bast, thank you for submitting a Talk issue for TABConf 2023! As we get closer to the conference, we will review all the issues, and the chosen ones will be added to the TABConf 2023 schedule: https://github.com/orgs/TABConf/projects/1.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions about your issue. Also, please update the issue description if you'd like to add anything else as we get closer to the conf.

**Comment by niftynei** [comment]
@iglesiasbrandon i want this for the @base58btc village!

**Comment by iglesiasbrandon** [comment]
Hey @niftynei I just assigned it to the base 58 village 💃

**Comment by niftynei** [comment]
Talk is scheduled for 12p - 12.30p Saturday

**Comment by iglesiasbrandon** [comment]
Hey @t-bast  , We have added a day, time slot, length, and village to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/9

Please acknowledge by commenting 'ack'.

This will confirm your talk for the Base 58 Protocol Village at TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by t-bast** [comment]
ACK, I'll start working on some slides for this!

**Comment by iglesiasbrandon** [comment]
hey @t-bast, closing this issue since this has been completed, thank you!
