### ISSUE TITLE
The Lightning Village powered by ZEBEDEE

### ISSUE THREAD

**Issue by JGrahek** [TABConf/2023.tabconf.com#122]
The first ever Lightning Village awaits you at TABConf 2023! We’ve got plenty in store, so we’re splitting the village into four sections:

LEARN
This is your ticket to the latest and greatest in Lightning. We’ll have fireside chats, panels and plenty of opportunities to get into the weeds with some of the best builders in the space. Learn what’s working, what still needs some work and where Lightning is headed. Spoiler alert: great things are coming!

ENGAGE
Get ready to see the incredible stuff that's being built with Lightning right now. From things we’re tinkering with right now, to projects and products already soaring high, this is the place to experience Lightning in action and maybe even spark some ideas of your own.

BUILD
This one's for all you shadowy supercoders. A hacker space that’s all about building with Lightning. Take part in a hackathon, step up to a challenge (and win sats), or help some of your Bitcoiner friends figure out how to build their first Lightning app (or just a paywall if that’s too ambitious). Here, you get to learn, innovate and build.

FUN
When night falls, our village morphs into a party zone! If you were at TABConf last year, you know the drill. But this year, we’re taking it a bit easier on the first few days and saving the all-out party for last! Because we don’t want you hungover for all the awesome talks. 
This part of the village is all about making connections, great conversations, and enjoying the opportunity to hang out with a bunch of Bitcoiners.

TABConf is one of the highlights of the year for us at ZEBEDEE and we can’t wait to show you everything we’ve got in store for the village. See you all soon!

**Comment by iglesiasbrandon** [comment]
Closing this issue because the village was accepted! Please take a look at this view if you would like to know what happening in this village: https://github.com/orgs/TABConf/projects/1/views/8
