### ISSUE TITLE
ZBD Dev 101 Workshop

### ISSUE THREAD

**Issue by zantoshi** [TABConf/2023.tabconf.com#124]
# Description

### What is this workshop about? Provide as many details as possible.

This workshop will be an immersive experience into the world of building lightning apps. They’ll learn all about the ZBD API, user experience flows, and lightning primitives in abstract terms and then a practical implementation in Next.js.

### What would an attendee learn from this workshop?

- How to build LN Apps with the ZBD API.
    - Paywalls
    - Pay to Lightning Addresses
    - Split Payments with Lightning Address
    - Multiple Payouts with Lightning Address
    - See more on my profile.

### Is there anything attendees should read up on before they attend this talk?

Yeah, they should check out our hackerstreams!

See [here](https://twitter.com/PlebLab/status/1689079083727200256)

### Is there anything attendees should set up before the workshop?

Nope.

### Relevant Links

[zebedee.io](http://zebedee.io/)

[docs.zebedee.io](http://docs.zebedee.io/)

# About the Speaker

### Social Links

[Github](https://github.com/zantoshi)
[Twitter](https://twitter.com/5antoshernandez)

[primal.com/santos](https://primal.com/santos)
[Website](https://santos.lol/)

# Workshop Details

### Length of workshop

60-90 minutes

### Preferred Day/Time Slot

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that **absolutely do not work** for you.*

N/A.

**Comment by miketwenty1** [comment]
@zantoshi thanks for the submission. It appears this was submitted a bit late and wasn't accepted this year. We'll be accepting talks for TABConf 6 next year.
