### ISSUE TITLE
NBD Nostr Dev Crash Course

### ISSUE THREAD

**Issue by zantoshi** [TABConf/2023.tabconf.com#125]
# Description

### What is this workshop about? Provide as many details as possible.

This workshop will give an overview of Nostr, nostr as a protocol, implementing an event, an example of a self-built SDK, nostr-tools SDK by NBD, and an example implementation using nostr-tools.

### What would an attendee learn from this workshop?

- Nostr
- Nostr events
- Nostr implementation
- Nostr-tools

### Is there anything attendees should read up on before they attend this talk?

- Nope, they should be technical, though.

### Is there anything attendees should set up before the workshop?

- Nope.

### Relevant Links

https://github.com/zantoshi/forumstr

https://github.com/zantoshi/nostr-keyrring-web-app

https://github.com/zantoshi/nostr-python-utils

### Social Links

[Github](https://github.com/zantoshi)
[Twitter](https://twitter.com/5antoshernandez)

[primal.com/santos](https://primal.com/santos)
[Website](https://santos.lol/)

[NBD](https://nbd.wtf/)

# Workshop Details

### Length of workshop

60-90 minutes

### Preferred Day/Time Slot

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that **absolutely do not work** for you.*

N/A.

**Comment by miketwenty1** [comment]
We're not going to have room in the official workshop schedule. 
https://github.com/TABConf/2023.tabconf.com/issues/58

There may be chance for a nostr area in the builders day area.

**Comment by miketwenty1** [comment]
@zantoshi thanks for the submission. It appears this was submitted a bit late and wasn't accepted this year. We'll be accepting talks for TABConf 6 next year.
