### ISSUE TITLE
Design principles for permissionless P2P networks learned from Bitcoin

### ISSUE THREAD

**Issue by narula** [TABConf/2023.tabconf.com#127]
# Description
### What is this talk about? Give us as many details as possible. 

An effective peer-to-peer network is essential to Bitcoin’s decentralized operation: without it, the network could centralize around a few known miners -- this increases the risk of censorship, whether through finding and attacking miners, or compelling them to discriminate against users. 

Running a permissionless peer-to-peer network is challenging because there is currently no way to charge for the resources used in relaying, storing, and verifying blocks and transactions, as well as maintaining the connectivity of the network (gossiping addresses). In fact, there are two goals which are at odds: nodes should be quick to cut off peers who are exhibiting what appears to be bad behavior, but doing so at scale might unintentionally partition the network. 

This talk will present an overview of the set of techniques (developed by many others) used in Bitcoin to address the challenge of maintaining a permissionless, well-connected network while preventing DoS attacks. This includes: 

* Requiring peers to demonstrate effort, at different levels and in different ways: For example, using proof-of-work or proof-of-utxo to gate more intensive local resource usage, or bucketing by IP in AddrMan
* Requiring an adversary to actually do useful work for the network in order to maintain connectivity: For example, how nodes are protected from eviction

The talk will also touch on places where Bitcoin’s P2P network seems to rely on altruism, and discuss techniques that other P2P networks use, and how they might or might not be applied to Bitcoin’s unique use case.

This talk will not discuss how P2P interacts with the mempool in a node or network (for example, it won’t touch on topics like standardness and transaction pinning attacks).

### What would an attendee learn from this talk?

In addition to the above:
* How gossiping of transactions, addresses, block headers, and blocks works in Bitcoin and some intuition for why it works this way
* Different connection types, and why it’s challenging to think about how to set defaults for connection parameters
* How misbehaving nodes are punished
* An overview of techniques used in other permissionless P2P networks

### Is there anything folks should read up on before they attend this talk?

The talk will be self-contained

### Relevant Links

To go deeper or learn more about P2P challenges, here are some papers and articles I’d recommend reading:
* https://www.usenix.org/system/files/conference/usenixsecurity15/sec15-paper-heilman.pdf 
* https://erebus-attack.comp.nus.edu.sg/erebus-attack.pdf 
* https://arxiv.org/pdf/2108.00815.pdf 
* https://www.cs.umd.edu/projects/coinscope/coinscope.pdf 
* https://gwern.net/doc/technology/2018-07-25-johnbackus-howdecentralizationevolves.html
* https://bitcoincore.reviews/16756  

# About the Speaker

### Social Links
[Github](https://github.com/narula)
[Twitter](https://twitter.com/neha)
[Website](https://nehanarula.org)

# Talk Details

### Length of Talk

25 min + 5 min for questions

### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

Preferably later in the day on Friday, 9/8. I cannot make any other day.

**Comment by miketwenty1** [comment]
@narula thanks for the submission. It appears this was submitted a bit late and wasn't accepted this year. We'll be accepting talks for TABConf 6 next year.
