### ISSUE TITLE
The school of Bitcoin

### ISSUE THREAD

**Issue by kdnolan** [TABConf/2023.tabconf.com#13]
Building an opensource accredited Bitcoin course in Australia. (GitHub as an LMS)

Theschoolfbitcoin.com

https://m.youtube.com/watch?v=B6Wj0Dp3ACM&list=PLD3n5hQtZwochgpYKFzW_blDx-e6lzwZK

What is this talk about?: Bitcoin Education - moving from Creating the worlds first physical Bitcoin school in the world in 2014 to now creating the worlds first Accredited Bitcoin course. [First Bitcoin School](https://www.youtube.com/watch?v=Z5fuBi0AQ9o)

What would an attendee learn from this talk?: How to teach Bitcoin

Is there anything folks should read up on before they attend this talk?: [theschoolofbitcoin.com](https://theschoolofbitcoin.com/)
[Faculty Meetings](https://www.youtube.com/playlist?list=PLwn9KgpxsZSRvMj6vHHAZbXVXOzX-sH6j)
[Curriculum](https://github.com/TheSchoolofBitcoinCurriculum/21TSOBTC-Diploma-of-Applied-Bitcoin/blob/main/Course%20Outline)
Length of talk:1 hour

About Speaker: 
Kieran is driven by three tenets: innovation, disruption, and lifelong learning.

Kieran is the learning programs director for the [Digital Playhouse Foundation](https://www.google.com/url?q=https://www.digitalplayhouse.com.au/digital-playhouse-foundation&sa=D&source=editors&ust=1676331066701747&usg=AOvVaw0j1j2HGHG9s7V2Nz7NcrmO), a charity with a focus on  digital literacy projects including [theschoolofbitcoin.com](https://www.google.com/url?q=http://theschoolofbitcoin.com&sa=D&source=editors&ust=1676331066702062&usg=AOvVaw2xCmj8xYj8iDoGwMsFwfku) 

He runs two Bitcoin podcasts [BitcoinAggregated](https://www.google.com/url?q=https://bitcoinaggregated.com/&sa=D&source=editors&ust=1676331066702761&usg=AOvVaw16PJY6wUaySMC-wapXv-le) (a Bitcoin news podcast built on lightning) and [#getoffzero](https://www.google.com/url?q=https://getoffzeropod.com/&sa=D&source=editors&ust=1676331066703126&usg=AOvVaw2EbfuKVgsqGHNLZqto1syU) (a podcast documenting Bitcoin learning journeys).

During his time as Educational Technologist at Wooranna Park Primary School, his strategic leadership led the school to launching a 24/7 International Virtual Learning Environment in Minecraft, Victoria’s first CoderDojo, Australia’s first Immersive Education Club, the world’s youngest Cisco class, and the very first, student centric, [School on the Blockchain](https://www.google.com/url?q=https://youtu.be/Z5fuBi0AQ9o&sa=D&source=editors&ust=1676331066703724&usg=AOvVaw02vvSGXIWZVEgWjKbEp88_).

He has spoken at a multitude of prominent conferences including; BETTS, [Immersive Education](https://www.google.com/url?q=https://summit.immersiveeducation.org/&sa=D&source=editors&ust=1676331066704213&usg=AOvVaw2Fhg_rHmGyJtExYvvltae6) (Paris), [Wall Street](https://www.google.com/url?q=https://www.youtube.com/watch?v%3DzQ04ESjSXvQ%26feature%3Dyoutu.be&sa=D&source=editors&ust=1676331066704442&usg=AOvVaw3xIXKBCcJHT6Ug6xjhf-yY) (NYC), [FYA](https://www.google.com/url?q=https://twitter.com/RachelYang_/status/975533016050094080?ref_src%3Dtwsrc%255Etfw%26ref_url%3Dhttps%253A%252F%252Fwww-woorannaparkps-com-au.filesusr.com%252Fhtml%252F88db68_0717a8ce0cdc05cb93012c8fa84f4428.html&sa=D&source=editors&ust=1676331066704806&usg=AOvVaw1QJboxoKWkGtC2dLlAEDoE), Australian Financial Review (SYD), [Minecon](https://www.google.com/url?q=https://twitter.com/BronSt/status/670423437723070464&sa=D&source=editors&ust=1676331066705078&usg=AOvVaw2l7OUtb2tvqNjS3EIeAmPc), EduTech (SYD), and Future Schools among many others.

His work has garnered a fair amount of media attention, including [The George Lucas Foundation](https://www.google.com/url?q=https://www.edutopia.org/blog/australia-school-designed-excite-and-engage-suzie-boss&sa=D&source=editors&ust=1676331066705791&usg=AOvVaw24V1vkCowVOmAajQauTpFm), [Bitcoin.com](https://www.google.com/url?q=https://news.bitcoin.com/australian-primary-school-students-explore-bitcoin-and-cryptocurrency-technology/&sa=D&source=editors&ust=1676331066706260&usg=AOvVaw0VAJSnNd2GqqP2mHP6Na2a), [The Age](https://www.google.com/url?q=https://www.theage.com.au/national/victoria/a-gifted-boy-left-singapore-to-enrol-in-this-public-school-20170803-gxoger.html&sa=D&source=editors&ust=1676331066706611&usg=AOvVaw0gLrISNtZPW1vzhp3Ord3P), and [Australian Teacher Magazine](https://www.google.com/url?q=https://educationhq.com/news/one-aussie-primary-school-teaches-cryptocurrency-and-the-world-is-paying-attention-42493/&sa=D&source=editors&ust=1676331066707070&usg=AOvVaw2QqNWZiOzbPsSTjZMVOhsz). He also made the the educator hotlist in both [2019 ](https://www.google.com/url?q=https://issuu.com/keymedia/docs/ofc-17_hotlist_2019-subbed&sa=D&source=editors&ust=1676331066707486&usg=AOvVaw2dHPB3Oo4DczlhpzksQ0dx)& [2020](https://www.google.com/url?q=https://www.theeducatoronline.com/k12/rankings/hot-list-2020/kieran-nolan-wooranna-park-primary-school/272708&sa=D&source=editors&ust=1676331066707798&usg=AOvVaw3Muccf4gRe4dl203UXGWSN)

Github: @kdnolan 
Twitter: @KieranDnolan
Website: kdnolan.com

# Talk Details
Length of talk:1 hour
Fridays best for me - 10am (AEDT)
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by kdnolan** [comment]
What is this talk about?: Bitcoin Education - moving from Creating the worlds first physical Bitcoin school in the world in 2014 to now creating the worlds first Accredited Bitcoin course. [](https://www.youtube.com/watch?v=Z5fuBi0AQ9o)

What would an attendee learn from this talk?: How to teach Bitcoin

Is there anything folks should read up on before they attend this talk?: theschoolofbitcoin.com
[](https://www.youtube.com/playlist?list=PLwn9KgpxsZSRvMj6vHHAZbXVXOzX-sH6j
[]()https://github.com/TheSchoolofBitcoinCurriculum/21TSOBTC-Diploma-of-Applied-Bitcoin/blob/main/Course%20Outline
)
Length of talk:1 hour

**Comment by iglesiasbrandon** [comment]
hey @kdnolan are you planning on giving this talk in person? also would this be better as a builder days table?

**Comment by kdnolan** [comment]
> hey @kdnolan are you planning on giving this talk in person? also would this be better as a builder days table? 

I wasn't... But I actually might be able to if my work okays it for travel etc! 

Let me get back to you 🙂

**Comment by iglesiasbrandon** [comment]
Sounds good, @kdnolan for now, we are only accepting in-person proposals.

**Comment by kdnolan** [comment]
Aww okay! Let me see what I can do! 🙂

**Comment by miketwenty1** [comment]
@kdnolan it seems this submission failed to get accepted this year, I appreciate the submission. One of our big criteria for accepting talks is reputation and community involvement around a topic. We also sort and order issues by 👍 emojis as one way to help understand how many people are excited to see a various talk/panel/workshop. Please consider submitting another idea next year. We'll be accepting talks for TABConf 6 in about 5-6 months.
