### ISSUE TITLE
Zeus Builder Day

### ISSUE THREAD

**Issue by kaloudis** [TABConf/2023.tabconf.com#130]
# Description
### What is this project about? Please give us as many details as possible.

Zeus is a mobile Bitcoin/Lightning wallet for iOS and Android. You can remotely connect to a LND, CLN, or Eclair node, use it with an LNDHub account, or use the new embedded, in-app wallet and node.

### Is it a FOSS or Open Source project?

Yes. It's FOSS with an AGPLv3 license.

### What would an attendee learn from visiting this projects table at Builder Days?

You'll learn about Zeus' architecture, how to get started with development, and have the opportunity to work with the Zeus team and other contributors on new features.

### Is there anything people should read up on before finding the table at Builder Day?

Get a head start on [getting your development environment set up](https://github.com/ZeusLN/zeus#developing) and take a look at our [issues page](https://github.com/ZeusLN/zeus/issues)

### Relevant Links

GitHub Repo: https://github.com/ZeusLN/zeus/

# Project Details
### Who will run the table? Are those people current contributors or maintainers who can answer questions and get people onboarded?

Evan Kaloudis and (potentially) Shubham Kumar from the Zeus team.

**Comment by bnonni** [comment]
hell ya

**Comment by iglesiasbrandon** [comment]
Hey @kaloudis Thank you for submitting this builder Days project! It has been accepted and added to the schedule. Builder Days will be on September 6th and 7th!
