### ISSUE TITLE
WEB3, its major challenges and how we'll surpass them.

### ISSUE THREAD

**Issue by CesarAMartin** [TABConf/2023.tabconf.com#131]
**WEB3, its major challenges and how we'll surpass them.**

- _(Syntezised presentation, it lasts around 15/20 minutes)_

Revolution ISN't something that starts and changes everybody at the same time.

It happens individually, people by people…

Nowadays I see a few challenges in the WEB3 era.

This new age in History makes us move and act, but also, it demands us to THINK and to take action strategically.

Let’s remember: the Internet was invented in 1983, and we could begin using video calls properly in 2019. More than 30 years later.
Crypto was created in 2009, and more than ten years later we’ve reached just over 3% of the world’s population.
So, **#mass #adoption**, **#scalability** and effective **#communication** are permanent challenges and keys to success, also it takes TIME, something we didn't change yet, we only change the perception of it.

I invite all my web3 friends to change the communication and get it easier for people who aren't on the field (yet).

Let’s change the term NFT to digital collectibles,  or the metaverse into internet 3D, or let’s call it our new “space” hahaha .

Let’s change the nomenclature “crypto” into just “money” or even better - digital currency.

Therefore, **UNDERSTANDING** is a must: let’s make it easier for people to understand it all.

A second challenge is **AWARENESS**. Basically, we don’t own our stuff anymore on the internet. Let’s clarify who’s who and who possesses what, permanently and for ever experience.

Another issue is what is concrete and what is **"META"** - in the sense of “a representation dos something, but not the thing. An example is followers in social media. You don’t have “your” followers, the platform you use to have them and you just take temporary advantage of them.

**CUSTODY** is another crucial matter. If someone loses things or assets in the WEB3 how can we help them? Do they trust any other user or entity helping them?

So, I here invite you all guys to - basically - stop making things difficult on the W3, let’s build the world we’ve dreamed of, full of **EVOLUTION!**

Tech is there. Capital is there. Goodwill is just here too.
And U? What do you think of all this?

Share your thoughts in the comments. See you around!

[#web3][#highlineventure][#hvb][#crypto] [#token] [#bitcoin] [#blockchain][#nft] [#asset][#fouad]#fouadninja][#world][#digital][#top]

- Attendees would learn to identify the major challenges WEB3 carries and different insights to surpass them.

- Would be quite convenient if attendees have previous experience with WEB3 interactions / actions.

- Relevant Links: 
https://www.linkedin.com/in/joao-fouad/. 
https://community.nasscom.in/communities/blockchain/what-challenges-lie-ahead-adoption-web3-2023#:~:text=Scalability,level%20as%20centralized%20web%20systems.
https://www.linkedin.com/company/highline-venture-builder/?viewAsMember=true
https://www.instagram.com/highline.vb/

-About the Speaker: A young disruptive entrepreneur and finance/WEB3 specialist, João Fouad -now more than ever – quotes Petter Drucker’s phrase: "The best way to predict the future is to create it." Joao leads [Highline Venture Builder](https://highline.digital/en/), an international HUB for companies, investors &amp; startups dedicated to promoting new millionaire businesses &amp; technologies for the WEB3/blockchain era. Some of those companies are artists’ token-driven management &amp; promotion companies [Idols](https://www.instagram.com/myidols.io/) and [Featz](https://featz.io/), which include 50Cent, Fat Joe and almost every Brazilian pop singer among their promoted celebrities.

He always seek to break the status quo and build new realities based on innovations in the companies he went through and founded. Finance, technology, marketing, and education are the drivers that will change the world. From a very young age, he needed to innovate, to reinvent himself, for the sake of survival, entrepreneurship was not just the only way, but the best.
Delivering innovative products, services, and benefits to humanity that make a positive impact is his responsibility in this life. An international cutting-edge speaker and entrepreneurial mentor, he has been an entrepreneur since he was 16, specializing in finance, investments, business intelligence, e-commerce, and the startup ecosystem.

He's also an EI (emotional intelligence) Master Coach dedicated to empowering other people's lives with techniques from Febracis. Today, he's one of the youngest Founders &amp; CEOs to develop investments, companies &amp; creative digital assets for the WEB3 and the Metaverse in South America.

In 2023, João Fouad was highlighted as one of the world's greatest entrepreneur under 35 years old for the blockchain landscape and bitcoin markets by major media CryptoDaily UK, and was invited to be one of the jury members for the CryptoDaily Awards 2023, specifically, for the ENTREPRENEURSHIP category.

Github:  https://github.com/CesarAMartin
Twitter: https://twitter.com/joaofouad
Website: https://highline.digital/en/ - https://highline.digital/

**# Talk Details**

### Preferred Day/Time Slot : Morning time in BR (BRT) | UTC/GMT -3 hours

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by miketwenty1** [comment]
This talks seems out of place for tabconf.

**Comment by CesarAMartin** [comment]
Hi Michael!

We can adapt it without problems. Would you inform us about that potential
adaptation?

Thanks in advance!

Greetings,

<https://wa.me/558588801577>

**Comment by russeree** [comment]
Out of curiosity how does Bitcoin or layers on top Bitcoin fit into this talk about "Web3" ? The concept of Web3 as a term was coined by Ethereum co-founder Gavin Wood and is used almost exclusively outside of Bitcoin.

**Comment by miketwenty1** [comment]
@CesarAMartin thanks for the submission. It appears this was submitted a bit late and wasn't accepted this year. We'll be accepting talks for TABConf 6 next year.
