### ISSUE TITLE
Talk: Lightning Usability Challenges

### ISSUE THREAD

**Issue by Liongrass** [TABConf/2023.tabconf.com#133]
# Description
### What is this talk about? Give us as many details as possible. 
This talk goes into the details of various issues around Lightning usability and experience from both a user and technical perspective.
- invoices (various forms of invoices and the issues they pose/solve: (zero-amount) Bolt11, LNURL, keysend, Bolt12)
- channels (how to get them, who to pair with: channel boards, lightning service providers, auctions)
- pathfinding (how to compute a reliable path, trampoline, blinded paths)
- on-chain balances
- assets on lightning (taproot assets)
- branding (lightning as a payment network vs bitcoin as a currency)

### What would an attendee learn from this talk?
The listener would gain an understanding of why Lightning payments function the way they do, and which approaches separate wallets/service providers/developers have taken to solve the most relevant pain points.

### Is there anything folks should read up on before they attend this talk?
It's expected that listeners have a basic understanding of what the Lightning network is and what allows it to function.

### Relevant Links

# About the Speaker
### Social Links
[Github](https://github.com/Liongrass/)
[Twitter](https://twitter.com/leoaw)
[Website](https://獅草地.香港/)
[Nostr](nostr:npub1spyzucqh3skwn9k6d4n4wl6k52evglxtrjzvs8et09sxxl9hrduq945j7y)

# Talk Details
### Length of Talk
30 mins
### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*
Anytime

**Comment by miketwenty1** [comment]
@Liongrass thanks for the submission. It appears this was submitted a bit late and wasn't accepted this year. We'll be accepting talks for TABConf 6 next year.
