### ISSUE TITLE
Base58 Village Presents: BIP370 (PSBTv2) + WalletOps Chat

### ISSUE THREAD

**Issue by niftynei** [TABConf/2023.tabconf.com#134]
# Description
Join @achow101 creator of PSBTs, @craigraw of Sparrow Wallet, and @shadouts of Unchained Capital @unchained-capital to talk about PSBTs, v0 and v2, challenges of writing wallet tech, and the incoming of proprietary PSBT formats.

### Relevant Links
https://github.com/bitcoin/bips/blob/master/bip-0370.mediawiki
https://github.com/sparrowwallet/sparrow/tree/master

# About the panelist
Organized by @base58btc 

# Panel Discussion Details
### Length of the panel discussion
45 - 1hr.

### Preferred Day/Time Slot 
1.30p - 2.15p Saturday

**Comment by iglesiasbrandon** [comment]
Closing this issue since it's been completed! Thanks!
