### ISSUE TITLE
Base58 Village: Taproot LN Spec Reverse Engineering Workshop

### ISSUE THREAD

**Issue by niftynei** [TABConf/2023.tabconf.com#135]
# Description
Join @arik-so and @niftynei for a deep dive into re-engineering the Taproot Spec for Lightning. This is an interactive, 2-hour discussion where Arik + Nifty will host a kind of an interactive Socratic thing where we have an objective and ask people how to achieve the protocol's desired properties (how to move LN to Taproot)

We'll dig into Schnorr, Taproot, and some MuSig2 nonce reuse properties. Come prepared to math, make friends, and learn how protocol design considerations are made.

# Workshop Details
### Length of workshop
2hrs 
### Preferred Day/Time Slot 
10a - 12p Friday

**Comment by iglesiasbrandon** [comment]
hey @niftynei , I am closing this issue since it's completed. Thank you for all of the effort you put into it!
