### ISSUE TITLE
Base58 Presents: Splice Up Your Life 

### ISSUE THREAD

**Issue by niftynei** [TABConf/2023.tabconf.com#136]
# Description
Join @ddustin (@opensats Grantee), @t-bast of @ACINQ and Justin Litchfield from @voltagecloud to talk about the genesis, benefits, deployment, and future of Splicing.

Moderated by Justin.

### Relevant Links

# Panel Discussion Details
### Length of the panel discussion
45m

### Preferred Day/Time Slot 
2.15 - 3p Friday

**Comment by t-bast** [comment]
@niftynei can you assign me to this issue so that it appears on my calendar? This will be useful to avoid conflicts (I have a potential one with #188 we need to resolve

**Comment by iglesiasbrandon** [comment]
Closing this issue since it's been completed! Thanks!
