### ISSUE TITLE
UNIVERSALLY CHALLENGED: Bitcoiners Know Nothing

### ISSUE THREAD

**Issue by niftynei** [TABConf/2023.tabconf.com#137]
# Description
PlebUnderground is teaming up with @base58btc to bring you the world's first ever Bitcoiner trivia show: Universally Challenged. Bitcoiners Know Nothing

Join us for the first ever live taping as we match up 3 v 3 teams to answer bitcoin trivia from across the ages, time, dimensions, BIPs etc.

Hosted by [PlebUnderground](https://twitter.com/PlebUnderground)'s lyrical memer, Walton [twitter](https://twitter.com/AEHW1)

# Panel Discussion Details
### Length of the panel discussion
1h

### Preferred Day/Time Slot 
3.30 - 4.30p Friday

**Comment by iglesiasbrandon** [comment]
Closing this issue since this item has been completed! Thank you!
