### ISSUE TITLE
Base58 Presents: An Interactive Introduction to Zero Knowledge Proofs

### ISSUE THREAD

**Issue by niftynei** [TABConf/2023.tabconf.com#138]
# Description
(NOTE: This is a repeat of the Thurs workshop #40) 

By @nkohen

A Zero Knowledge Proof (ZKP) is a type of protocol in which a prover convinces a verifier of some fact (e.g. this riddle has a solution, or I own that public key, or I know a solution to that sudoku puzzle) without having the verifier learn anything else at all! A classic example of a non-interactive ZKP is a digital signature, but ZKPs have many uses throughout cryptography.

In this pencil-and-paper workshop, I will introduce the notion of a Zero Knowledge Proof and we will construct a few example ZKPs for "toy" problems in groups. Once we've learned a couple tricks and how to analyze our ZKPs, we will then "accidentally" discover the Schnorr digital signature!

## What would an attendee learn from this talk?
Attendees will learn what a ZKP is, when it might be a tool to reach for, see a few informative example ZKPs which may help in reading about them in the future, and discover where digital signatures come from.

## Is there anything folks should read up on before they attend this talk?
Nope! Some amount of rigor has been removed in order to make this workshop accessible to all!

## Relevant Links
[Zero Knowledge Proof Wikipedia Page](https://en.wikipedia.org/wiki/Zero-knowledge_proof) (You don't need to understand anything on this page, just figured I'd leave it here in case it helps people get interested).

## About the Speaker
I previously worked at Suredbits and was a contributor to the bitcoin-s library and the DLC specifications. These days I am pursuing a PhD in Mathematics at Indiana University focusing on Number Theory. I also teach math to high schoolers using Inquiry Based Learning during the summers at MathILy.

## Social Links
Github: https://github.com/nkohen
Twitter: https://twitter.com/nadav_kohen

# Workshop Details
### Length of workshop
2hrs
### Preferred Day/Time Slot 
10a - 12p Saturday

**Comment by nkohen** [comment]
ACK

**Comment by itsciefa161** [comment]
How does one join? Does it cost money?

**Comment by iglesiasbrandon** [comment]
hey @itsciefa161, just the cost of the conference ticket. None of the programming at TABConf has any additional costs. 
You can get a ticket by going to https://2023.tabconf.com/

**Comment by itsciefa161** [comment]
Thank you for the reply, sadly it's too expensive for me right now. But I appreciate the response, have fun at the event!!

**Comment by iglesiasbrandon** [comment]
Hey @itsciefa161 , closing this issue since this has been completed, thank you!
