### ISSUE TITLE
Base58 Presents: Trident's MiniScript Challenge

### ISSUE THREAD

**Issue by niftynei** [TABConf/2023.tabconf.com#139]
# Description
In this 1hr long workshop, @matthiasdebernardini of @AnchorWatch-Trident will give a short overview of how MiniScript works.

We'll then split into teams and work to be the first to create a miniscript for a given set of increasingly difficult challenges. Come prepared to script!

# Workshop Details
### Length of workshop
1hr
### Preferred Day/Time Slot 
2.30 - 3.30p Saturday

**Comment by iglesiasbrandon** [comment]
Closing this issue because this item is completed!
