### ISSUE TITLE
What's The Deal With Publishing Data On Bitcoin?

### ISSUE THREAD

**Issue by petertodd** [TABConf/2023.tabconf.com#14]
# Description

Ordinals and other services have published enormously amounts of images, videos, text, and other data to the Bitcoin blockchain. This talk will go over the different ways this, how it affects Bitcoin users, and if it's even possible to stop.

# About the Speaker
### Social Links
https://petertodd.org
https://twitter.com/peterktodd

# Talk Details
### Length of Talk

30 mins

### Preferred Day/Time Slot 

Later in the day.

I hate alarm clocks. :D

**Comment by iglesiasbrandon** [comment]
Hey, @petertodd, thank you for submitting a Talk issue for TABConf 2023! As we get closer to the conference, we will review all the issues, and the chosen ones will be added to the TABConf 2023 schedule: https://github.com/orgs/TABConf/projects/1.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions about your issue. Also, please update the issue description if you'd like to add anything else as we get closer to the conf.

**Comment by miketwenty1** [comment]
@petertodd it seems this submission failed to get accepted this year, I appreciate the submission. One of our big criteria for accepting talks is reputation and community involvement around a topic. We also sort and order issues by 👍 emojis as one way to help understand how many people are excited to see a various talk/panel/workshop. Please consider submitting another idea next year. We'll be accepting talks for TABConf 6 in about 5-6 months.
