### ISSUE TITLE
Base58 Presents: FROST Explain-a-thon

### ISSUE THREAD

**Issue by niftynei** [TABConf/2023.tabconf.com#140]
# Description
Maybe you've heard about FROST but do you know what it does?

In this 1h 15m session we'll have some of the best in the business take a crack at explaining FROST for the layman. Come learn, laugh, and enjoy the competition as we all learn a little bit (or a lot) more about the dominant Taproot threshold signature protocol.

Each explainer will have 5m to walk us through the protocol, to the best of their understanding. At the end, we'll have a group discussion to answer questions and get feedback on which approach was the most useful.

Current explainers include:
- @jesseposner 
- @robinlinus
- @elsirion / @kodylow
- @benthecarman
- @nkohen 
- @niftynei
- ??? Open Submission

# Panel Discussion Details
### Length of the panel discussion
1h 15m

### Preferred Day/Time Slot 
1.15p - 2.30p Saturday

**Comment by nkohen** [comment]
@niftynei I would love to throw my hat into the ring!

**Comment by niftynei** [comment]
@nkohen accepted! :)

**Comment by iglesiasbrandon** [comment]
hey @niftynei, closing this issue since this has been completed, thank you!
