### ISSUE TITLE
Base58 Presents: Lightning Class Preview

### ISSUE THREAD

**Issue by niftynei** [TABConf/2023.tabconf.com#141]
# Description
Join us for a quick, 30m intro to lightning channels. This is a great exercise for anyone who wants to better understand how lightning works.

This is a preview of the 3-day @base58btc Lightning class. 

Read more on the Base58 website: https://base58.school/classes/lightning-bolts

# About the Speaker
@niftynei is a Lightning network spec veteran and long time software engineer. She runs @base58btc, a bitcoin protocol school.

# Workshop Details
### Length of workshop
30m 

### Preferred Day/Time Slot 
12.45 - 1.15p

**Comment by iglesiasbrandon** [comment]
Hey @niftynei , closing this issue since this has been completed, thank you!
