### ISSUE TITLE
Creating a taproot output from command line

### ISSUE THREAD

**Issue by javiervargas** [TABConf/2023.tabconf.com#142]
# Description
This workshop aims to create a bitcoin output (Bech32m) using bitcoin core, btcdeb tool, and the rust-based bdk-cli tool.
The objective is to teach at a general level what are the steps to create a bech32 address and comment the taproot components.?
Attendees should read up on before they attend this BIP:  [340](https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki), [341](https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki), [342](https://github.com/bitcoin/bips/blob/master/bip-0342.mediawiki)?
Attendees should set up bitcoin-core,  [btcdeb](https://github.com/bitcoin-core/btcdeb/tree/master) and [bdk-cli.](https://github.com/bitcoindevkit/bdk-cli)
### Relevant Links

# About the Speaker

@javiervargas 

# Workshop Details
1 hour.

**Comment by miketwenty1** [comment]
@javiervargas I see you submitted this 2 weeks ago, I'm unsure if this will end up being accepted but there's some overlap with my workshop would you like to team up in anyway?

https://github.com/TABConf/2023.tabconf.com/issues/72

I'm also going to plan to do taproot outputs, but just very basic tr(wif) sort of ideas.

**Comment by javiervargas** [comment]
@miketwenty1 For sure!,  Very nice share experiences with you.

**Comment by miketwenty1** [comment]
@javiervargas thanks for the submission. It appears this was submitted a bit late and wasn't accepted this year. We'll be accepting talks for TABConf 6 next year.
