### ISSUE TITLE
Speaker Needed: Setting Up Dev Environment With Nix

### ISSUE THREAD

**Issue by jordan-bravo** [TABConf/2023.tabconf.com#143]
Speaker Needed: Setting Up Dev Environment With Nix

# Description
### What is this workshop about? Provide as many details as possible. 
Most development projects have different environments that require a developer to onboard through a tedious setup process.  The Nix package manager and surrounding Nix ecosystem enable projects to have fully declarative and reproducible development environments. 

### What would an attendee learn from this workshop?
- How to onboard to a project that currently uses Nix.
- How to add Nix to an existing project.
- Using the libraries `direnv` and `nix-direnv` to automatically load the dev environments when changing directory into a project.

### Is there anything attendees should read up on before they attend this talk?
[Nix From First Principles: Flake Edition](https://tonyfinn.com/blog/nix-from-first-principles-flake-edition/)

### Is there anything attendees should set up before the workshop?
Follow this [guide](https://zero-to-nix.com/start/install) to install the Nix package manager.

### Relevant Links
- [Nix From First Principles: Flake Edition](https://tonyfinn.com/blog/nix-from-first-principles-flake-edition/)
- Follow this [guide](https://zero-to-nix.com/start/install) to install the Nix package manager.

# About the Speaker (Speaker Needed)
### Social Links
Github 
Twitter
Website

# Workshop Details (Speaker Needed)
### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by miketwenty1** [comment]
@jordan-bravo it doesn't look like anyone is picking this up.. and also we don't really have room for another workshop. 

cc @iglesiasbrandon
