### ISSUE TITLE
Talk: Portland.HODL - Modern Multisig and the Implications of Script Hashing

### ISSUE THREAD

**Issue by russeree** [TABConf/2023.tabconf.com#144]
# Description
Modern Multisig and the Implications of Script Hashing
### What is this talk about? Give us as many details as possible. 
This talk would discuss many of the aspects that affect modern multisig implementations in Bitcoin when contrasted against the more classic BIP11 Pay to Multisig implementations. Beyond the additional complexity and benefits; P2SH/P2WSH multisig introduces new challenges for long term self custody in the form of persistent XPUB storage. This is due to the need for not only having the signatures needed to satisfy quorum but also the xpubs/public keys required to rebuild the spending script so that the redeem script hash can be satisfied.

There will also be a discussion and overview of various ways users can backup these xpubs and the tradeoffs they present.

- Digital Media (_SD Card, Thumb Drive, SSD, Tape, CD, etc ..._)
- Paper
- Metal
- Cloud Storage
- A single spend from an address
- Inscriptions
- P2MS Outpoints
- OP_RETURN

### What would an attendee learn from this talk?
- The history and motivations for multisig.
- Classic ScriptPubkey multisig (P2MS BIP11)
- Modern P2SH/SegWit/Taproot based multisig
- What is happening during the coordination process when creating a quorum.
- The importance of satisfying the redeem script (NFT of a bitcoin script😂) 
- Why not having just the private keys is enough with multisig today
- How to durably/trustlessly store XPUBs 
- The various types of electronic media and their durability (CDs, SD cards, USB thumbdrives, etc...)
- How a redeem script and script pubkey are created and executed.
- Address types (or lack there of) and what they represent.

### Is there anything folks should read up on before they attend this talk?
Not required though the relevant links will provide additional context needed to get the full value from the talk.

### Relevant Links
[BIP11](https://en.bitcoin.it/wiki/BIP_0011)
[BIP16](https://en.bitcoin.it/wiki/BIP_0016)
[BIP174](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki)

# About the Speaker
I am a guy who likes to work on BitCoin Core and make educational side decks.

### Social Links
[Github](https://github.com/russeree)
[Twitter](https://twitter.com/portlandhodl?lang=en)

# Talk Details
### Length of Talk 
45 mins
### Preferred Day/Time Slot 
Any

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by miketwenty1** [comment]
@iglesiasbrandon is it fair to say the main stage is saturated? I'm seeing some high quality talks being proposed, I'm wondering what options may exist.

**Comment by iglesiasbrandon** [comment]
yea as of right now we dont have any open slots on the main stage for day 3 or 4. we may be able to do things in the unconf room.

**Comment by russeree** [comment]
Thank you interest around my proposed talk! It means a lot.

There is a problem though @miketwenty1 @iglesiasbrandon, When creating this issue I accidently assumed that the conf. date was October 12-15  since Google's first result was https://2022.tabconf.com/. Not realizing it was the 2022 conf; I am woefully unprepared for this years conf. No hotel, flight, ticket, transport etc...  

As such I believe my issue should be closed.
