### ISSUE TITLE
[NextGen Village] Digital Logic pt 3 - Silas Pembroke

### ISSUE THREAD

**Issue by asherp** [TABConf/2023.tabconf.com#145]
## Description

A continuation of Silas Pembroke's series on digital logic, Silas explains computer memory from scratch, constructing the following integrated circuits using [Digital Logic Simulator](https://sebastian.itch.io/digital-logic-sim)

* SR-Latch
* DS-Latch
* D-Latch
* On-Latch
* Register

## About the speaker

Silas Pembroke is a 9yr old with a passion for mathematics, computer science, physics, and gaming. 
This is Silas's second time speaking at Tabconf and he's excited to share his knowledge with other bitcoiner families.

**Comment by iglesiasbrandon** [comment]
hey @asherp , closing this issue since this has been completed, thank you!
