### ISSUE TITLE
Why You Should Run Full-RBF On Your Node

### ISSUE THREAD

**Issue by petertodd** [TABConf/2023.tabconf.com#15]
# Description

Why are so many people running full-RBF? Why should you run it too? This talk will go over what transaction replacement and full-RBF actually are, how full-RBF helps multiparty protocols like coinjoins, why it's good for miners, and why a small minority hate it with a passion.

# About the Speaker
### Social Links
https://petertodd.org
https://twitter.com/peterktodd

# Talk Details
### Length of Talk

Could fit this into a 10min lightning talk slot, or do a full 30 minute talk.

### Preferred Day/Time Slot 

Later in the day preferably.

**Comment by iglesiasbrandon** [comment]
Hey, @petertodd, thank you for submitting a Talk issue for TABConf 2023! As we get closer to the conference, we will review all the issues, and the chosen ones will be added to the TABConf 2023 schedule: https://github.com/orgs/TABConf/projects/1.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions about your issue. Also, please update the issue description if you'd like to add anything else as we get closer to the conf.

**Comment by ariard** [comment]
> Why are so many people running full-RBF? Why should you run it too? This talk will go over what transaction replacement and full-RBF actually are, how full-RBF helps multiparty protocols like coinjoins, why it's good for miners, and why a small minority hate it with a passion.

I think the talk will gain a lot in explaining the technical philosophy discussion that has been discussed between developers and the wider ecosystem during the full-RBF deployment debate of last year. From the mailing list, the [mempool consistency rules](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-October/021135.html) has been questioned, iirc one dev argued that [“to each use-case, its own transaction-relay policy"](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-October/021135.html) and myself argued than "[game-theory of second-layers operations offer economic asymmetries in the usage of policy rules](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-October/021129.html)".

**Comment by iglesiasbrandon** [comment]
Hey @petertodd, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The talks on the main stage will be happening on September 8th and 9th; once we accept more, we will assign the day, time, and location.
