### ISSUE TITLE
Key problems with bitcoin and potential solutions

### ISSUE THREAD

**Issue by dka218** [TABConf/2023.tabconf.com#159]
# Description
### What is this talk about? Give us as many details as possible. 
Identify several key problems with bitcoin (onboarding, key management, fee rate variability, fungibility) and present possible solutions and solicit additional ideas from the audience.
### What would an attendee learn from this talk?
The obstacles that makes it difficult for regular people to use bitcoin and to focus some attention on fixing them.
### Is there anything folks should read up on before they attend this talk?
Talk a normal person through acquiring bitcoin, securely storing the bitcoin, and spending some of the bitcoin.
### Relevant Links

# About the Speaker
### Social Links
Github 
Twitter: https://twitter.com/dka218
Website

# Talk Details
### Length of Talk
30 minutes
### Preferred Day/Time Slot 
Thursday Sept 7 or Sunday Sept 9
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by miketwenty1** [comment]
@dka218  thanks for the submission. It appears this was submitted a bit late and wasn't accepted this year. We'll be accepting talks for TABConf 6 next year.
