### ISSUE TITLE
Lightning Village Keynote

### ISSUE THREAD

**Issue by zantoshi** [TABConf/2023.tabconf.com#161]
### Description
A special keynote by CTO / Cofounder and Overlord of NBD Andre Neves.
### Day
Day 3
### Time
10:00AM - 10:30AM
### Speaker(s)
@andrerfneves

**Comment by andrerfneves** [comment]
👍 count me in

**Comment by iglesiasbrandon** [comment]
Hey @andrerfneves , I am closing this issue since it's completed. Thank you for all of the effort you put into it!
