### ISSUE TITLE
How to Setup a Paid Nostr Relay

### ISSUE THREAD

**Issue by zantoshi** [TABConf/2023.tabconf.com#162]
### Description
Learn how to setup your own paid Nostr Relay with Bitcoin.
### Day
Day 3
### Time
10:30AM - 11:00AM
### Speaker(s)
@andrerfneves @zantoshi

**Comment by andrerfneves** [comment]
👍 count me in

**Comment by iglesiasbrandon** [comment]
Hey @andrerfneves, I am closing this issue since it's completed. Thank you for all of the effort you put into it!
