### ISSUE TITLE
Lightning Builders

### ISSUE THREAD

**Issue by zantoshi** [TABConf/2023.tabconf.com#166]
### Description
Hear from Lightning Builders in the space.
### Day
Day 3
### Time
2:30PM - 3:00PM
### Speaker(s)
@miketwenty1  (ZBD), @andrefneves (ZBD), @Michael (Wavlake), @Keyan (Stacker.News)

**Comment by andrerfneves** [comment]
👍 count me in

**Comment by huumn** [comment]
I am commenting on this one too 🫃

**Comment by blastshielddown** [comment]
🕺

**Comment by iglesiasbrandon** [comment]
Closing this issue since it's been completed! Thank you!
