### ISSUE TITLE
Why you Shouldn't Use Stacker News

### ISSUE THREAD

**Issue by zantoshi** [TABConf/2023.tabconf.com#168]
### Description
Keyan, founder of Stacker.News, is presenting on the bearish case for Stacker.News
### Day
Day 4
### Time
11:30AM - 12:00PM
### Speaker(s)
@keyan

**Comment by huumn** [comment]
I am commenting. 😄

**Comment by iglesiasbrandon** [comment]
hey @huumn  , closing this issue since this has been completed, thank you!
