### ISSUE TITLE
PlebLab x ZBD Panel

### ISSUE THREAD

**Issue by zantoshi** [TABConf/2023.tabconf.com#169]
### Description
Hear from Lightning Builders at PlebLab and ZBD.
### Day
Day 4
### Time
1:30PM - 2:00PM
### Speaker(s)
@AustinKelsay, @Topher, @supertestnet, @andrerfneves
### Moderating
@Kati

**Comment by andrerfneves** [comment]
👍 count me in

**Comment by thrillerxx** [comment]
in

**Comment by cmdruid** [comment]
in, thanks for the invite.

Are there any specific topics or questions that I should prepare for?

**Comment by AustinKelsay** [comment]
I'm in lfg

**Comment by iglesiasbrandon** [comment]
hey @AustinKelsay , closing this issue since this has been completed, thank you!
