### ISSUE TITLE
The path to default ASMap

### ISSUE THREAD

**Issue by fjahr** [TABConf/2023.tabconf.com#17]
# Description
### What is this talk about? Give us as many details as possible. 

I will give a quick overview of how internet routing on clearnet works and how this leads us to the insight that using an ASMap file is a good practice for anyone running a node and also helps the network overall. Then I will show how an ASMap file is constructed taking into account the latest best practices (sources, tools and how they work under the hood). I will then show what potential pitfalls are and how we can get around them when shipping a default ASMap with Bitcoin Core releases in the future.

### What would an attendee learn from this talk?

- How the usage of ASMap files protects your node and strengthens the network
- A better understanding of how internet routing on clearnet works
- What current options exist to build your own ASMap file or audit a file that someone else has built
- How the Bitcoin Core deployment process works and how it changes in the context of shipping an ASMap file as a part of the binary

### Is there anything folks should read up on before they attend this talk?

I will give a quick summary of the context and history so anyone should be able to follow it (I expect many have forgotten about ASMap even if they heard of it in 2020).

### Relevant Links

- [Longer write-up on the current proposal](https://gist.github.com/fjahr/bf0ff0917e03a4e49fac0617b2b35747)
- [Condensed step-by-step description of the release process](https://gist.github.com/fjahr/f879769228f4f1c49b49d348f80d7635)
- [kartograf](https://github.com/fjahr/kartograf)

# About the Speaker

I have been contributing to Bitcoin Core since 2019. Among other things, I have developed the [CoinstatsIndex](https://github.com/bitcoin/bitcoin/pull/18000). In 2022, I have spent some time building a better understanding of the larger internet routing infrastructure. This was necessary to understand and evaluate the potential data sources for ASMap files and create a proposal for ASMap in the Bitcoin Core release process. This effort had been pending since 2020 when the feature was merged as an option. I am also an organizer of the [Bitdevs Socratic Seminar in Berlin ](https://bitdevs.berlin/).

### Social Links

Github: https://github.com/fjahr
Twitter: https://twitter.com/fjahr
Website: https://fjahr.com/

# Talk Details

### Length of Talk

~30 min (I can make it shorter or longer)

### Preferred Day/Time Slot 

No preference

**Comment by JoseMoranUrena523** [comment]
I would definitely hear you out on this one! This is a good talk actually.

**Comment by iglesiasbrandon** [comment]
Hey, @fjahr, thank you for submitting an issue for TABConf 2023! As we get closer to the conference, we will review all the issues, and the chosen ones will be added to the TABConf 2023 schedule: https://github.com/orgs/TABConf/projects/1.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions. Also, please feel free to update the issue description if you'd like to add anything else as we get closer to the conf.

**Comment by renepickhardt** [comment]
It would be super interesting to include lightning network channels and channel partner selection into this. I believe channels should to a large degree be regional because even online payments seems to be a local problem and optimizing for latency is a thing. C.f. the last paragraph and two diagrams in this comment https://github.com/lightningdevkit/rust-lightning/issues/1170#issuecomment-972396747

**Comment by sr-gi** [comment]
I'd most certainly be interested in hearing about this 😁

**Comment by fjahr** [comment]
> It would be super interesting to include lightning network channels and channel partner selection into this. I believe channels should to a large degree be regional because even online payments seems to be a local problem and optimizing for latency is a thing. C.f. the last paragraph and two diagrams in this comment [lightningdevkit/rust-lightning#1170 (comment)](https://github.com/lightningdevkit/rust-lightning/issues/1170#issuecomment-972396747)

Very interesting, not sure how fast I can dive into this but I will definitely check it out. The current version of ASMap doesn't have a geographical component to it but it's something I have in mind to research in the future.

**Comment by iglesiasbrandon** [comment]
Hey @fjahr we have accepted your [workshop](https://github.com/TABConf/2023.tabconf.com/issues/16), does it still make sense to have this talk in addition? 

Would this talk cover things that you are not planning on covering in the workshop?

**Comment by fjahr** [comment]
> Hey @fjahr we have accepted your [workshop](https://github.com/TABConf/2023.tabconf.com/issues/16), does it still make sense to have this talk in addition?
> 
> Would this talk cover things that you are not planning on covering in the workshop?

It's fine if I only do the workshop, I can cover the topics I had planned for the talk in the workshop as well and I think the workshop is more valuable for this topic than the talk.

**Comment by iglesiasbrandon** [comment]
sounds good, thank you @fjahr! we will keep the workshop and close the talk, please let us know if you need any more time allocated to the workshop to cover all the topics.
