### ISSUE TITLE
Hackathon Updates

### ISSUE THREAD

**Issue by zantoshi** [TABConf/2023.tabconf.com#170]
### Description
Get an update on how our hackathon is going.
### Day
Day 4
### Time
2:00PM - 2:15PM
### Speaker(s)
@ThrillerCarX , @Kati, @zantoshi

**Comment by thrillerxx** [comment]
Lets go

**Comment by iglesiasbrandon** [comment]
hey @thrillerxx , closing this issue since this has been completed, thank you!
