### ISSUE TITLE
All Things Nostr

### ISSUE THREAD

**Issue by zantoshi** [TABConf/2023.tabconf.com#172]
### Description
Hear from Nostr builders and creators.
### Day
Day 4
### Time
2:30PM - 3:00PM
### Speaker(s)
@briimhd, @Claire, @Kati . 
### Moderator
@zantoshi.

**Comment by claire-vp** [comment]
LFG

**Comment by Bitc0indad** [comment]
Bullish AF 🔥

**Comment by peachyhodl** [comment]
hyped!!

**Comment by iglesiasbrandon** [comment]
Closing this issue!

**Comment by Claire** [comment]
wrong Claire in description
