### ISSUE TITLE
Secrets & Shares: A Hands-on Guide to SSS and Codex32

### ISSUE THREAD

**Issue by kiarafbickers** [TABConf/2023.tabconf.com#175]
# Description
### What is this workshop about? Provide as many details as possible. 

A hands-on workshop on Shamir's Secret Sharing (SSS) with Codex32. This workshop is designed for anyone interested in learning about how to distribute, verify, and reconstruct sensitive information like Bitcoin seeds. Codex32 provides a step-by-step guide to generating shares, computing checksums, and recovering secrets—all without relying on electronic computers.

### What would an attendee learn from this workshop?

- An understanding of Shamir's Secret Sharing Scheme and Codex32.
- Hands-on experience with Codex32 for generating and verifying checksums by hand.

### Is there anything attendees should set up before the workshop?

There is no pre-setup required, although participants are encouraged to review the basics of Shamir's Secret Sharing for a smoother experience. During the workshop, feel free to come and go as you wish. We will provide all the worksheets and volvelles needed for the exercises. 

### Relevant Links

Read more on the SecretCodex32 website: 
- https://secretcodex32.com/
- https://en.bitcoin.it/wiki/BIP_0069

# About the Speaker
### Social Links
[@kiarabickers](https://twitter.com/kiarabickers) serves as a research communicator on the [@blksresearch](https://twitter.com/blksresearch) team.

# Workshop Details
### Length of workshop
* Can use 1hr or more.

### Preferred Day/Time Slot 
* Wednesday or Thursday morning

**Comment by iglesiasbrandon** [comment]
Hey @kiarafbickers the only time slot we have that might work for you is Wednesday 3:00 PM - 4:30 PM ET. Please let me know if that would work.

**Comment by kiarafbickers** [comment]
That works, expect Tidwell just suggested I do a builders day table instead.

**Comment by kiarafbickers** [comment]
Any update on this @iglesiasbrandon?

**Comment by miketwenty1** [comment]
@kiarafbickers my concern is this will be something that will potentially take a couple hours+ for people interested an ongoing builders day table that spans 2 days gives more opportunity imo for people to get involved in small groups.

@iglesiasbrandon let me know what you think. since the sides of the room are taken.. maybe we make a small island of tables for this idea?

**Comment by kiarafbickers** [comment]
@miketwenty1 A side table totally works!
