### ISSUE TITLE
Homeschooling bitcoiners

### ISSUE THREAD

**Issue by EllyPembroke** [TABConf/2023.tabconf.com#177]
# Description
It's no coincidence that many bitcoiners choose to homeschool their children. Bitcoiners and homeschoolers are motivated by similar values. Both seek freedom and are willing to take responsibility. But where do you start? Our panel of experienced homeschooling bitcoiners can help! They will share their stories and talk about practical ways to start homeschooling without fear of failing your child. They will also share how they are preparing their children for a future with bitcoin in it - the future we're building together.

# About the panelists
Shane Hazel
Scott & Tali Lindberg
Asher & Elly Pembroke

**Comment by Bitc0indad** [comment]
This is the way!

**Comment by iglesiasbrandon** [comment]
Hey @Bitc0indad, closing this issue since this has been completed, thank you!
