### ISSUE TITLE
Bitcoin Core Builder Day

### ISSUE THREAD

**Issue by murchandamus** [TABConf/2023.tabconf.com#178]
# Description
### What is this project about? Please give us as many details as possible.

Bitcoin Core is a full node implementation of the Bitcoin protocol.

### Is it a FOSS or Open Source project?

FLOSS

### What would an attendee learn from visiting this projects table at Builder Days?

We will answer questions about contributing to Bitcoin Core, discuss issues, and feature ideas. We will also be able to assist with questions about Bitcoin Stack Exchange, and the Chaincode Protocol Developer Seminar content.

### Is there anything people should read up on before finding the table at Builder Day?

Anyone is welcome, especially people interested in contributing to one of our projects

### Relevant Links
GitHub Repo: 

- https://github.com/bitcoin/bitcoin
- https://bitcoincore.org
- https://bitcoin.stackexchange.com
- https://learning.chaincode.com

# Project Details
### Who will run the table? Are those people current contributors or maintainers who can answer questions and get people onboarded?

- @achow101 and @Murchandamus will be attending the table, possibly other project contributors may be found in the vicinity at times

**Comment by iglesiasbrandon** [comment]
hey @murchandamus this Builder Days Project has been accepted.

**Comment by miketwenty1** [comment]
@murchandamus I look forward to this
