### ISSUE TITLE
BOB Residency Program

### ISSUE THREAD

**Issue by BOBSpaces** [TABConf/2023.tabconf.com#179]
This talk is about the BOB Space Residency Program, specifically focusing on the importance of having a trusted Bitcoin Hacker Space where developers and power users can come together, explore ideas, and test concepts. The talk is expected to last for 30 minutes.

Attendees to this talk can expect to learn about the significance of having a dedicated space for Bitcoin developers and enthusiasts to collaborate and innovate. It will cover the objectives, benefits, and activities associated with the BOB Space Residency Program and similar initiatives. While the exact details of what attendees will learn are not provided in the description, it's likely to include insights into the Bitcoin development community, the role of hacker spaces, and the potential impact of such programs on the Bitcoin ecosystem by providing experimental tools such BOBs Cashu Community Mint aka BOBStash

There is no specific prerequisite reading or preparation mentioned for attendees before the talk. 

### Social Links

Twitter
https://twitter.com/SovereignSk8
https://twitter.com/BOBSpace_BKK
Website
https://www.bobspaces.net/

# Talk Details
### Length of Talk
~ 30 minutes
### Preferred Day/Time Slot 
Anytime on the first day

**Comment by miketwenty1** [comment]
@BOBSpaces thanks for the submission. It appears this was submitted a bit late and wasn't accepted this year. We'll be accepting talks for TABConf 6 next year.
