### ISSUE TITLE
PLEBNET.DEV: Breaking Tutorial Chains and Diving into Real Bitcoin Development

### ISSUE THREAD

**Issue by Bitc0indad** [TABConf/2023.tabconf.com#182]
**Duration of Talk:** 30 minutes

![PLEBNET.DEV Logo](https://plebnet.dev/images/logo-dark-horiz-transparent.png)

Introducing **PLEBNET.DEV** - not your typical high-brow tech consortium. Rather, it's a community of genuine Bitcoin 'plebs' with a united purpose: actively contributing as developers in the Bitcoin sphere. This presentation illuminates the guiding principles of PLEBNET.DEV, championing the motion of rousing developers from the daunting 'Tutorial Hell'. The mantra? The "Learn, Build, and PR Feedback Loop". By endorsing this approach, developers are prompted to engage in genuine project participation, thereby blending theoretical insight with practical engagement.

### **Discussion Highlights:**
- **Tutorial Hell's Traps:** Unveiling the challenges countless enthusiasts face when they embark on the "Learn to Code" pathway, only to find themselves ensnared, unable to make practical strides.
  
- **PLEBNET.DEV's Dynamic Strategy:** How this community aids its members to shift from ceaseless learning to genuine development - by making pull requests (PRs) and receiving tangible feedback.
  
- **Self-Initiative's Role:** Recognizing the essence of individual drive, and how making that inaugural PR can turbocharge one's evolution as an adept developer.

### **Takeaways for Attendees:**
- Realize the hurdles novice developers encounter with 'Tutorial Hell' and its inherent obstacles.
  
- Comprehend PLEBNET.DEV's applied methodology that promotes the swift utilization of knowledge through the "Learn, Build, and PR Feedback Loop."
  
- Fathom the profound impact of initiating one's developmental voyage, magnified by the game-changing act of drafting that first PR.
  
- View authentic instances of community members who have navigated beyond the tutorial routine, stepping into substantial project involvements.

**Note:** A rudimentary understanding of the development workflow, particularly within the Bitcoin landscape, is advantageous. For a closer look into the applied facet of PLEBNET.DEV's development, peruse [PLEBNET.DEV Resources](http://plebnet.dev/resources).

### **Relevant Links:**
- [PLEBNET.DEV Resources](http://plebnet.dev/resources)
  
- [LNBits Testnet](https://testnet.plebnet.dev/)
  
- [Testnet Lightning Node](https://mempool.space/testnet/lightning/node/03ba00a57cec1cef4873065ad54d0912696274cc53155b29a3b1256720e33a0943)
  
- [Nostr Relay](https://testnet.plebnet.dev/nostrrelay/1)
  
- [Nostrogen](https://nostrogen.plebnet.dev/)

### **Connect:**
- **Github:** [Bitc0indad on GitHub](https://github.com/Bitc0indad)
- **NIP-05** tobias@plebnet.dev  
- **Twitter:** [bitc0indad on Twitter](https://twitter.com/bitc0indad)  
- **Official Website:** [PLEBNET.DEV](http://plebnet.dev)
---
### **Chapter 3: The Forked Betrayal**

...Julien's battle against the corrupt aristocrats became a turning point in his journey. It solidified his commitment to Bitcoin's sovereignty and the values it represented. Through his unwavering determination, he became a beacon of hope for those yearning for financial autonomy and a fairer financial landscape. He knew that the fight against the corrupt aristocrats would be ongoing, but he was emboldened by the collective strength and resilience of the Bitcoin community.
---
_**Attribution:** This is an official **PLEBNET.DEV** contribution. The talk proposal and the narrative excerpt from "The Bitcoin Odyssey" are intellectual properties of [bitc0inDad](tobias@plebnet.dev)_

**Comment by bitkarrot** [comment]
Two thumbs up!

**Comment by Bitc0indad** [comment]
@miketwenty1 can we sneak this in or what?

**Comment by Bitc0indad** [comment]
> Absolutely yes. How does Friday at 1pm sound?

Sounds great, thank you!

**Comment by bitkarrot** [comment]
Yes!!! All our hard work building this now coming to fruition!

**Comment by Bitc0indad** [comment]
@EllyPembroke can we move time to 2pm please? fiatjaf NOSTR talk at 1pm

**Comment by asherp** [comment]
> @EllyPembroke can we move time to 2pm please? fiatjaf NOSTR talk at 1pm

We can but you would compete with the drivechain debate. Otherwise 3pm is open

**Comment by Bitc0indad** [comment]
Lets play it safe 3pm then...I don't care about drivechain lol> > @EllyPembroke can we move time to 2pm please? fiatjaf NOSTR talk at 1pm
> 
> 
> 
> We can but you would compete with the drivechain debate. Otherwise 3pm is open

**Comment by Bitc0indad** [comment]
[TabConf_PND_Presentation.pptx (1).pdf](https://github.com/TABConf/2023.tabconf.com/files/12554891/TabConf_PND_Presentation.pptx.1.pdf)

**Comment by iglesiasbrandon** [comment]
Closing this issue since it's been completed!
