### ISSUE TITLE
Socratic Panel: Joinpools - A Guided Journey Through The Shared UTXO

### ISSUE THREAD

**Issue by btsea** [TABConf/2023.tabconf.com#185]
# Description
Scaling the UTXO set has fundamental limitations. Lightning, while powerful in its own right, offers only limited scaling of the UTXO set. Joinpools, protocols that enable a single UTXO to represent the ownership of multiple participants (n >2), offer a novel approach to breaking through these limitations. In this panel we will shed light on some approaches to constructing Joinpools. How do they work, and what tradeoffs do they make? Can they realistically work given their requirements? 

### Is there anything folks should read up on before they attend this talk?

- [CoinPools](https://coinpool.dev/)
- [Ark](https://www.arkpill.me/)
- Channel Factories [[1](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6124062/pdf/rsos180089.pdf)], [[2](https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-January/003827.html)], [[3](https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-February/003479.html)], [[4](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-April/020370.html)]

# Panelists
- @ariard
- @ZmnSCPxj
- @stevenroose 

## Moderator
- @btsea 

# Panel Discussion Details
This is a Socratic Panel, which means the event will be a two-way dialogue. It is expected for both panel participants and members of the crowd to ask and answer questions. 

To begin the panel, each panelist will give a short 5-10 minute presentation on the topic. Once the presentations are complete, the moderator will pose a few questions to stimulate discussion. From here, the crowd and panelists will be offered a chance to steer discussion with their own questions.

**Comment by btsea** [comment]
@ariard, @ZmnSCPxj, @stevenroose thank you so much for your participation in this panel. 

Please drop a comment in here so we can assign this issue to you. Thank you!

**Comment by ariard** [comment]
Coinpool for the win.

**Comment by stevenroose** [comment]
I had already upthumbed, but hereby a more formal ACK :)

**Comment by btsea** [comment]
Thanks @stevenroose, it seems Github did not consider that sufficient for an assignment.

**Comment by btsea** [comment]
Closing, thanks to all the participants!
