### ISSUE TITLE
Socratic Panel: Covenants - A Taxonomical Analysis

### ISSUE THREAD

**Issue by btsea** [TABConf/2023.tabconf.com#186]
# Description
In Bitcoin discourse, the term ‘covenant’ is used liberally. But what does it really mean? In this panel we will attempt to come to agreement on the definition of the term and describe the properties of a “good” covenant. Do we design covenants for a specific use case, or do we attempt to generalize them? Finally, we will analyze some existing covenant proposals and see if they fit within our shared taxonomy.

# Panelists
- @sanket1729 
- @RobinLinus
- @brqgoo
- @stevenroose

## Moderator 
- @RazTeve

# Panel Discussion Details
This is a Socratic Panel, which means the event will be a two-way dialogue. It is expected for both panel participants and members of the crowd to ask and answer questions. 

To begin the panel, each panelist will give a short 5-10 minute presentation on the topic. Once the presentations are complete, the moderator will pose a few questions to stimulate discussion. From there, the crowd and panelists will be offered a chance to steer discussion with their own questions.

**Comment by sanket1729** [comment]
ACK

**Comment by RobinLinus** [comment]
Unfortunately, this time slot collides with the [FROST Explain-a-thon](https://github.com/TABConf/2023.tabconf.com/issues/140) in which I participate. If it would work for you that I leave the panel around 1:15-1:30 PM, I could ask the others if I can present last.

**Comment by btsea** [comment]
@RobinLinus We can re-arrange, sorry about the conflict! Give me some time to fix that. Thanks for the feedback.

**Comment by RazTeve** [comment]
ACK

**Comment by btsea** [comment]
Hey @stevenroose, I hear you are joining this panel, awesome! Please ACK so I can assign the issue to you.

**Comment by stevenroose** [comment]
ACK

**Comment by btsea** [comment]
Thanks for the participation folks!! Closing on completion. 

Here's to the MEV boogieman
