### ISSUE TITLE
Socratic Panel: Multiparty Computation in Bitcoin: The State of Affairs

### ISSUE THREAD

**Issue by btsea** [TABConf/2023.tabconf.com#187]
# Description
Multiparty computation (MPC) is a broad term of art. In key generation and signing operations, MPC is playing an increasingly critical role in production environments. In this panel we will discuss some of the modern approaches to MPC that have captured mindshare within the Bitcoin community. We will look at their tradeoffs, potential (and actual) vulnerabilities, as well as the current state of their development/implementation. 

# Panelists
-  @jesseposner 
- @nkohen
- @adiabat

## Moderator
- @m1sterc001guy

# Panel Discussion Details
This is a Socratic Panel, which means the event will be a two-way dialogue. It is expected for both panel participants and members of the crowd to ask and answer questions. 

To begin the panel, each panelist will give a short 5-10 minute presentation on the topic. Once the presentations are complete, the moderator will pose a few questions to stimulate discussion. From here, the crowd and panelists will be offered a chance to steer discussion with their own questions.

**Comment by btsea** [comment]
@jesseposner @botanix-labs @adiabat Thank you for your participation in this panel! Please drop a comment here so we can assign the issue accordingly.

**Comment by adiabat** [comment]
ACK
It's 15 min after a talk I'm giving here (https://github.com/orgs/TABConf/projects/1/views/7?pane=issue&itemId=37549008
) so there could be contention if that room runs late (later than this room anyway).  But should be OK as long as everything stays in sync.

**Comment by btsea** [comment]
@adiabat We can push things back another 15 minutes, we have some flex later in the day.

**Comment by nkohen** [comment]
Ack

**Comment by m1sterc001guy** [comment]
ACK

**Comment by jesseposner** [comment]
ack

**Comment by btsea** [comment]
Thank you @jesseposner @nkohen @adiabat @m1sterc001guy  that was awesome. Really enjoyed that. Closing on completion.
