### ISSUE TITLE
Socratic Panel: Private Payments and Me

### ISSUE THREAD

**Issue by btsea** [TABConf/2023.tabconf.com#188]
# Description
Transactional interactions within the Bitcoin protocol carry privacy implications for both the payor and payee. Today, users have access to a variety of protocols to disjoint the payment graph and increase their anonymity set when interacting on and off-chain. 

In this panel we will compare and investigate a subset of tools available to enhance users privacy. Specifically, we plan to cover Redshift (CoinSwaps over Lightning), PayJoin and BOLT12. While each of these protocols is tailored to solve specific problems, we will spend some time comparing the interactivity and liveness requirements of these protocols, alongside their ultimate objectives.  We will also discuss ways that users may combine on and off-chain techniques to further improve their privacy. 

# Panelists
- @benthecarman 
- @dangould
- @t-bast

## Moderator
- @vnprc

# Panel Discussion Details
This is a Socratic Panel, which means the event will be a two-way dialogue. It is expected for both panel participants and members of the crowd to ask and answer questions.

To begin the panel, each panelist will give a short 5-10 minute presentation on the topic. Once the presentations are complete, the moderator will pose a few questions to stimulate discussion. From there, the crowd and panelists will be offered a chance to steer discussion with their own questions.

**Comment by t-bast** [comment]
I'd be happy to join! I just have a partial overlap with #136, if we could move this 15 minutes later that would be great :+1:

**Comment by benthecarman** [comment]
Ack

**Comment by btsea** [comment]
Ah sorry about the @t-bast! We will re-arrange the time to fit your schedule.

**Comment by vnprc** [comment]
Ack

**Comment by btsea** [comment]
Thanks @DanGould @vnprc @benthecarman @t-bast!! Closing on completion.
