### ISSUE TITLE
Socratic Panel: Mempool Policy in 2023 - Navigating MEV, Pinning Attacks, TX Accelerators and More

### ISSUE THREAD

**Issue by btsea** [TABConf/2023.tabconf.com#192]
# Description
Network policy rules are constantly in flux. In the face of new classes of attacks on unconfirmed transactions (e.g. RBF Pinning) and protocols that leverage non-standard transactions, a variety of new network policy rules have been proposed (e.g. V3 transactions and Package Relay). This panel investigates some of these proposals and discusses their implications on the gossip network, off-chain protocols and consensus discovery more generally. 

# Panelists
- @murchandamus
- @petertodd

# Panel Discussion Details
This is a Socratic Panel, which means the event will be a two-way dialogue. It is expected for both panel participants and members of the crowd to ask and answer questions.

To begin the panel, each panelist will give a short 5-10 minute presentation on the topic. Once the presentations are complete, the moderator will pose a few questions to stimulate discussion. From there, the crowd and panelists will be offered a chance to steer discussion with their own questions.

**Comment by btsea** [comment]
@murchandamus, @petertodd thank you so much for your participation in this panel.

Please drop a comment in here so we can assign this issue to you. Thank you!

**Comment by murchandamus** [comment]
ACK

**Comment by petertodd** [comment]
ACK
