### ISSUE TITLE
Hardcore Trivia

### ISSUE THREAD

**Issue by CardCoins** [TABConf/2023.tabconf.com#193]
# Description
Each year, [CardCoins](https://cardcoins.co) sponsors a Hardcore Trivia event at TABConf. There will be a mix of technical and historical trivia questions. To see examples of questions from prior years, please see [this repository](https://github.com/CardCoins/conference-trivia/). 

Please head on over after the closing remarks on the main stage. Rules and prizes will be announced at the start of the event.

# About the Speaker
**CardCoins enables users to buy Bitcoin with cash at over 80,000 locations nationwide.** Follow us on [Twitter](https://twitter.com/cardcoinsco).

**Comment by btsea** [comment]
@iglesiasbrandon @miketwenty1 Is the time assigned to this event acceptable for you guys? We want to make sure it is after the closing remarks, which we don't yet see on the schedule.

**Comment by miketwenty1** [comment]
@btsea 
We will be done with the closing ceremony before 6pm. But unsure if we will have it done before 5pm.

**Comment by iglesiasbrandon** [comment]
final issue completed! thank you for everything @btsea
