### ISSUE TITLE
DAO on Bitcoin, by leveraging Taproot MAST

### ISSUE THREAD

**Issue by ChrisCho-H** [TABConf/2023.tabconf.com#20]
# Description
### What is this panel discussion about? Please give us as many details as possible. 
There are so many emerging DAOs based on ETH, SOL, or whatever. However, Most of them are actually just based on "plutocracy", just like its base chain using POS, DPOS, or whatever. If the purpose of DAO only limited to economic interests, current form might be fine, as DAO based on plutocracy can be regarded as just corporation, maybe in more public and efficient form.  

However, if not limited to economic interests, DAO based on plutocracy is doomed to fail. Truly decentralized autonomous organization needs to be decentralized regarding not only the number of participants, but also the right of each participant. For that reason, one person, one vote rule might be required to be more democratic. Taproot MAST can be used to build DAO on top of Bitcoin. Simply, root of MAST can be used to verify the member of DAO, so don't need to store all public keys of DAO on Bitcoin. There could be many other utilites using Taproot script.

Required values and tech of DAO can be discussed, like what value(democracy? anonymity? transparency?) must be included for true DAO and technical way(using Taproot script) to achieve. I want to open up this session in Panel Discussion, as I just want to share simple outline and possibility of this subject, and then discuss the details publicly with bright Bitcoiners in various backgrounds.

As an output for this discussion, I look forward to the architecture of DAO and script to build it.

### What would an attendee learn from this talk?
Attendee can participate in this discussion with his/her opinion freely, as this issue not only limited to complex tech but also general question about organization, human and etc.
Also Panels can be anyone who has interests(if this idea is selected for schedule🤣).

### Is there anything folks should read up on before they attend this talk?
Taproot knowledge could be helpful.
### Relevant Links

# About the panelist
Software engineer working on various Bitcoin open-source.
### Social Links
GitHub: https://github.com/ChrisCho-H

# Panel Discussion Details
### Length of the panel discussion
20-30 minutes
### Preferred Day/Time Slot 
Any day/time works during the conference.

**Comment by iglesiasbrandon** [comment]
Hey, @Hyunhum , thank you for submitting an issue for TABConf 2023! As we get closer to the conference, we will review all the issues, and the chosen ones will be added to the TABConf 2023 schedule: https://github.com/orgs/TABConf/projects/1.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions. Also, please feel free to update the issue description if you'd like to add anything else as we get closer to the conf.

**Comment by miketwenty1** [comment]
@ChrisCho-H it seems this submission failed to get accepted this year, I appreciate the submission, this panel looked like a very interesting idea. One of our big criteria for accepting talks is reputation and community involvement around a topic. We also sort and order issues by 👍 emojis as one way to help understand how many people are excited to see a various talk/panel/workshop. Please consider submitting another idea next year. We'll be accepting talks for TABConf 6 in about 5-6 months.
