### ISSUE TITLE
The Art of Raising Money for your Bitcoin Startup

### ISSUE THREAD

**Issue by iglesiasbrandon** [TABConf/2023.tabconf.com#29]
# Description
### What is this workshop about?
This is an interactive Q&A workshop/talk. It aims to help attendees learn when and how to get funding for bitcoin startups (current + future!)

### What would an attendee learn from this workshop?
- When is the right time to raise capital?
- How to structure a funding round? 
- What do VCs look for in startups?
- What do VCs look for in pitch decks?
- Making your first outside hire(s)
- Common FAQs on raising capital

### Is there anything attendees should read up on before they attend this talk?
Just come ready to learn and ask questions.

### Is there anything attendees should set up before the workshop?
Nope

### About the Speaker(s)
Christopher Calicott, Trammell Venture Partners

### Social Links
Twitter: https://twitter.com/mecee

### Length of workshop
1 Hour

### Preferred Day/Time Slot 
N/A

**Comment by miketwenty1** [comment]
@iglesiasbrandon would this be a talk instead of a workshop?

**Comment by ccalicott** [comment]
+21

**Comment by 21theresa** [comment]
@ccalicott @miketwenty1, I'm happy to lend a hand in making this interactive.

**Comment by ccalicott** [comment]
ack, although I don't know we'll need an entire hour.

**Comment by miketwenty1** [comment]
Location updated to lightning village.

**Comment by iglesiasbrandon** [comment]
Hey @ccalicott , I am closing this issue since you have completed the workshop. Thank you for all of the effort you put into it!
