### ISSUE TITLE
EXAMPLE - I love Milou: A talk about the 2023 TABConf Mascot

### ISSUE THREAD

**Issue by briimhd** [TABConf/2023.tabconf.com#3]
# Description
### What is this talk about? Give us as many details as possible. 
This talk is about how dedicated I am to supporting Milou on his mission to bring bitcoin to the puppy community.
### What would an attendee learn from this talk?
Attendees will learn about Milou's lifestyle and his struggles with puppy-to-puppy payments.
### Is there anything folks should read up on before they attend this talk?
Please read up on the PRD (puppy reserve department) & how to appropriately approach Milou without a growl response.
### Relevant Links
twitter.com/miloulabs

# About the Speaker
Milou is a bitcoin maxi (very toxic). He is black and white and likes to growl at strangers who approach him too rapidly. His 3 attacks: lick, growl, sneeze.
### Social Links
Github - Milou has no hands so he cannot type
[Twitter](https://twitter.com/miloulabs)
Website - Coming Soon

# Talk Details
### Length of Talk 
2 hours
### Preferred Day/Time Slot 
Day 1, Keynote
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by JoseMoranUrena523** [comment]
This is kinda funny tbh

**Comment by iglesiasbrandon** [comment]
We are closing this issue since we actually have issues in the repo now!

**Comment by briimhd** [comment]
damn i'm truly heartbroken
