### ISSUE TITLE
Lightning Is For Everyone - Leveraging the RLS API 

### ISSUE THREAD

**Issue by iglesiasbrandon** [TABConf/2023.tabconf.com#37]
# Description

River recently just launched a product called River Lightning Services - a simple API for enabling Bitcoin Lightning Network deposits and withdrawals in your product without running any Lightning infrastructure yourself. It is built by developers, for developers.

Lightning is still a new technology that is showing a sharp increase in adoption. It allows for instant payments nearly for free. We have routed over a million transactions through our nodes, and we could provide some key insights and learnings from this developing ecosystem.

This discussion could be about the Lightning Network and the impacts that it will have on the payments industry, crypto businesses and also provide key insights for developers. We recently wrote [a 19-page report on the Lightning Network](https://river.com/learn/files/river-lightning-report.pdf) that can be part of the discussion.

## What would an attendee learn from this talk?
- How Lightning will disrupt the payments industry
- What River uses for infrastructure
- Using a multi-node architecture
- Liquidity management
- Outbound vs inbound flow
- Peer selection (explaining the meritocracy - including anonymity, non-KYC, and node value)
- Insights on payment success rate and how to improve it
- How a business or developer can use the Lightning Network without running any Lightning Infrastructure themselves
- How River Lightning Services abstracts away all node, channel, and liquidity management so people can focus on sending and receiving LN payments via our simple API

## Relevant Links
[rls.dev](https://github.com/TABConf/2023.tabconf.com/issues/rls.dev)

# About the panelist
Alexander Leishman - Founder, CEO,  CTO at River. Alex brings his deep expertise in software engineering, information security, and Bitcoin to River where he oversees investor relations, corporate strategy, engineering and Lightning.

### Social Links
[Alex Twitter](https://twitter.com/Leishman)
[River Twitter](https://twitter.com/River)
[Website](https://river.com/)

### Panel Discussion Details
Flexible

### Preferred Day/Time Slot
Flexible

**Comment by leishman** [comment]
Great!

**Comment by miketwenty1** [comment]
@leishman it seems this submission failed to get accepted this year, I appreciate the submission with Brandon. One of our big criteria for accepting talks is reputation and community involvement around a topic. We also sort and order issues by 👍 emojis as one way to help understand how many people are excited to see a various talk/panel/workshop. Please consider submitting another idea next year. We'll be accepting talks for TABConf 6 in about 5-6 months.
