### ISSUE TITLE
An Interactive Introduction to Secret Sharing

### ISSUE THREAD

**Issue by nkohen** [TABConf/2023.tabconf.com#41]
# Description
### What is this workshop about? Provide as many details as possible. 
Secret sharing (aka secret splitting) is an interactive process in which a group of parties hold parts (aka shards, aka shares) of a secret and can subsequently agree to reconstruct (or else use without reconstructing) the secret should enough of the parties agree. This cryptographic primitive sees myriad of uses in Bitcoin from cold storage solutions and hot wallet solutions to threshold signatures (MuSig and FROST and such) and more!

In this pencil-and-paper (and maybe calculator) workshop, I will ask groups a series of questions and we will discover a couple rudimentary secret sharing schemes, including some simple examples of the famous Shamir Secret Sharing. We will then construct an example of a Multi-Party Computation (MPC) using our secret sharing to solve a problem. If time permits, we'll investigate Shamir Secret Sharing in general.

### What would an attendee learn from this workshop?
An attendee will learn what secret sharing is, a couple examples of secret sharing schemes, including Shamir Secret Sharing which is used in most modern multi-party computations (like MuSig and FROST), and will get a sense for how secret sharing can be used as part of Multi-Party Computations.

### Is there anything attendees should read up on before they attend this talk?
Nope! Some amount of rigor has been removed in order to make this workshop accessible to all!

### Relevant Links
(Secret Sharing Wikipedia Page)[https://en.wikipedia.org/wiki/Secret_sharing] (You don't need to understand anything on this page, just figured I'd leave it here in case it helps people get interested).

# About the Speaker
I previously worked at Suredbits and was a contributor to the bitcoin-s library and the DLC specifications. These days I am pursuing a PhD in Mathematics at Indiana University focusing on Number Theory. I also teach math to high schoolers using Inquiry Based Learning during the summers at MathILy.

### Social Links
Github: https://github.com/nkohen
Twitter: https://twitter.com/nadav_kohen

# Workshop Details
### Length of workshop
1-2 Hours (2 hours means we get to cover everything, 1 hour means some things will be skipped or rushed through a bit, I'm open to having a timeslot of any length in this range). If you have strong opinions about whether I should offer the short or long version, comment below that you want the 1 hour or the 2 hour version!

### Preferred Day/Time Slot 
None.

**Comment by iglesiasbrandon** [comment]
Hey @nkohen , thank you for submitting an issue for TABConf 2023! As we get closer to the conference, we will review all the issues, and the chosen ones will be added to the TABConf 2023 schedule: https://github.com/orgs/TABConf/projects/1.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions. Also, please feel free to update the issue description if you'd like to add anything else as we get closer to the event.

**Comment by iglesiasbrandon** [comment]
Hey @nkohen congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The workshops will be happening on September 6th and 7th; once we accept some more, we will assign the day, time, and location.

**Comment by iglesiasbrandon** [comment]
Hey @nkohen , We have added a day, time slot, and length to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/4

Please acknowledge by commenting 'ack'.

This will confirm your workshop for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by nkohen** [comment]
ACK

**Comment by miketwenty1** [comment]
@nkohen 

We are about a week away from the start of the conference. I'm sending this to all accepted upcoming workshop. Please review and ensure you have a clear, up to date, high level, agenda on this GitHub issue. Please buffer in time to help with unexpected problems and questions.

TABConf workshops should aim to involve high levels participation. If you're planning to conduct a live demo, please consider that attendees will require clear instructions on how to prepare for following along, (all steps for setup should be double checked) and any presentation should be structured accordingly.
Participants should leave the workshop either with something built, (be it physical or digital), or with specific knowledge gained from the __hands on/interactive__ experience.

Good luck on doing 2 of these btw.

**Comment by iglesiasbrandon** [comment]
Hey @nkohen, I am closing this issue since you have completed the workshop. Thank you for all of the effort you put into it!
