### ISSUE TITLE
An Interactive Introduction to Security Models

### ISSUE THREAD

**Issue by nkohen** [TABConf/2023.tabconf.com#42]
# Description
### What is this workshop about? Provide as many details as possible. 
What do cryptographers mean when they say that a protocol is secure? A prominent method of modeling and reasoning about protocol security is through the use of attack games.

In this pencil-and-paper workshop, we'll look at and use some definitions of security for encryption and pseudo-random number generators using attack games. In groups, we'll show that operations such as nested encryption and continuously using a pseudo-random number generator to form a stream of random bits are secure (assuming the underlying encryption and PRG are secure). Both of these are things done all the time in the Lightning Network! If time permits we'll also take a look at some more definitions of security for things like digital signatures or something else (open to suggestions).

### What would an attendee learn from this workshop?
An attendee would get an introductory understanding of how cryptographers reason about security and correctness of protocols.

### Is there anything attendees should read up on before they attend this talk?
Nope! Some amount of rigor has been removed in order to make this workshop accessible to all!

### Relevant Links
Unfortunately this topic is almost exclusively written about for experts and students becoming experts (This workshop is not!), the content of the workshop will be mostly derived from excerpts of [this book](https://toc.cryptobook.us/).

# About the Speaker
I previously worked at Suredbits and was a contributor to the bitcoin-s library and the DLC specifications. These days I am pursuing a PhD in Mathematics at Indiana University focusing on Number Theory. I also teach math to high schoolers using Inquiry Based Learning during the summers at MathILy.

### Social Links
Github: https://github.com/nkohen
Twitter: https://twitter.com/nadav_kohen

# Workshop Details
### Length of workshop
1-2 Hours (2 hours means we get to cover everything, 1 hour means some things will be skipped or rushed through a bit, I'm open to having a timeslot of any length in this range). If you have strong opinions about whether I should offer the short or long version, comment below that you want the 1 hour or the 2 hour version!

### Preferred Day/Time Slot 
None.

**Comment by iglesiasbrandon** [comment]
Hey @nkohen, thank you for submitting an issue for TABConf 2023! As we get closer to the conference, we will review all the issues, and the chosen ones will be added to the TABConf 2023 schedule: https://github.com/orgs/TABConf/projects/1.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions. Also, please feel free to update the issue description if you'd like to add anything else as we get closer to the event.

**Comment by nkohen** [comment]
Closing this so that I don't have to do three workshops :)
