### ISSUE TITLE
Using Nodeyez to Get More from your Node

### ISSUE THREAD

**Issue by vicariousdrama** [TABConf/2023.tabconf.com#44]
# Description
### What is this project about? Please give us as many details as possible.

Nodeyez let's you visualize data from your Bitcoin Node.  Whether using an attached display, sending to an external monitor, or making available through a website dashboard, the images produced let you get an at-a-glance perspective of key metrics of interest to you.

Some of the images that can be generated today range from simple outputs, such as the current block height, to outputting OP_RETURNs to graphing recent fee rates and projected block fees from mempool.

This is an important project so that people running nodes can get more value out of the data they already have and even pull in remote data to process.  Users with simple nodes have invested in the compute and storage space and power but most of these nodes just sit on a shelf somewhere unseen. Nodeyez lets users bring these into focus into more regular use as display pieces projecting data.

### Is it a FOSS or Open Source project?

Yes. Nodeyez is FOSS and released under the MIT License

### What would an attendee learn from visiting this projects table at Builder Days?

- What is Nodeyez - Sample images created
- How to install Nodeyez on a Raspberry Pi
- How to configure Nodeyez to change the look of display panels generated
- Coding a new display panel or modifying existing script for Nodeyez

### Is there anything people should read up on before finding the table at Builder Day?

It would be beneficial to read through the Nodeyez website and have knowledge of Linux and JSON.

### Relevant Links
Nodeyez Website:	https://nodeyez.com
Github Repo:	https://github.com/vicariousdrama/nodeyez

# Project Details
### Who will run the table? Are those people current contributors or maintainers who can answer questions and get people onboarded?
Who will run the table? Are those people current contributors or maintainers who can 
answer questions and get people onboarded?
- Vic (Vicarious Drama) is current contributor/maintainer

**Comment by iglesiasbrandon** [comment]
Hey, @vicariousdrama thank you for submitting an issue for TABConf 2023 Builder days!

**Comment by iglesiasbrandon** [comment]
Hey @vicariousdrama, congratulations, this issue has been accepted for TABConf 2023. It has been added to the official GitHub Project schedule. The builder Days tables will be on all day on September 6th and 7th

**Comment by vicariousdrama** [comment]
That's super awesome! Thank you!
