### ISSUE TITLE
Standard of Contract: The Forgotten Fourth Function of Money and its Implications for Monetary Transitions

### ISSUE THREAD

**Issue by DiracDel0** [TABConf/2023.tabconf.com#45]
# Summary / Abstract

Most people are familiar with the three function model of money comprising store of value, medium of exchange, and unit of account (along with the notion that monetization of an asset sees the acquisition of these functions in that order), and sometimes with the perspective among some Austrians of medium of exchange primacy, whereby money is simply the most salable good. However, prior to this perspective, logician and economist William Jevons, one of the three men behind the marginal revolution in economics, wrote in his 1875 treatise Money and the Mechanism of Exchange of four primary monetary functions: unit of account being presented decomposed as *measure* of value and *standard* of value.

The *measure* of value is what most people think about when they hear the phrase *unit of account* and it is a great irony that despite the frequent use of the term "bitcoin standard", few are aware of the fundamental meaning of standard of value, or as I like to refer to it, standard of contract. To measure is to observe (that which is), but to work to a standard is to specify (that which will come), and with that, it becomes apparent that the ever present factor of time is the critical distinction. 

Most people view money as that which solves the double coincidence of wants problem, but this is not enough -- money also solves the double coincidence of *future* wants problem, and eliminates uncertainty about the future, in the present, necessitated by the fact that physical, real world markets are not perfectly liquid, nor is the *overhead* cost of an economic decision negligible for any actor. It is desirable that decision costs be amortized, which is only possible with a standard of value for contracts.

It is easy to imagine a world in which bitcoin has wholly replaced fiat money and the monetary premium in all other assets has vanished, but the years preceding this are trickier. We are approaching a singularity. I have yet to meet a bitcoiner who has a unified theory of the "physics" as we near this singularity, but I do. We will explore the nature of business and contracts in the tail end of a final monetary transition -- a corporation is itself an emergent phenomenon arising from layering many contracts atop of what are ultimately all individuals (nexus of contracts theory), and within these entities there is a fundamentally different flavor of interaction with money that as often overlooked by the ordinary, individual consumer. Moreover, this is not your grandfather's global monetary transition. As we explore these implications of value standard, we will incidentally shatter the notion of medium of exchange primacy, which disappears in the digital age as monetary switching latency approaches zero.

The talk in article form can be found here
https://heaviside.substack.com/p/the-forgotten-fourth-function-of

# About Speaker

npub1c8nlcgd5l8qenesgdcy4vw0s794yujyy23z50n52v5ld0ddkcjnsppqsah

https://twitter.com/diracdel

# Talk Details

Flexible on length and date. Probably doesn't need to be more than half an hour.

**Comment by miketwenty1** [comment]
@DiracDel0 it seems this submission failed to get accepted this year, I appreciate the submission. One of our big criteria for accepting talks is reputation and community involvement around a topic. We also sort and order issues by 👍 emojis as one way to help understand how many people are excited to see a various talk/panel/workshop. Please consider submitting another idea next year. We'll be accepting talks for TABConf 6 in about 5-6 months.
