### ISSUE TITLE
ZeroSync: Introducing STARK proofs to Bitcoin

### ISSUE THREAD

**Issue by RobinLinus** [TABConf/2023.tabconf.com#46]
# Description
### What is this talk about? Give us as many details as possible. 
This talk is about the [ZeroSync project](https://zerosync.org), which is spearheading the application of proof systems to Bitcoin. We are basically building a Bitcoin client in a STARK proof to compress the chain for scalability, interoperability, and privacy. Just recently, we have completed our first major milestone of a basic recursive chain proof. We are also developing a toolkit for Bitcoin developers to apply zero-knowledge proofs to their own products and services.
The long-term vision is to help bring ZKPs onto Bitcoin's main layer.

### What would an attendee learn from this talk?
- What are proof systems? What are the tradeoffs?
- What is a chain proof? What are the applications? 
- What is the ZeroSync project?
- ZeroSync chain proof demo 
- Roadmap of the ZeroSync project

### Is there anything folks should read up on before they attend this talk?
- https://zerosync.org
- https://zerosync.org/#talks
- https://github.com/zerosync/zerosync
- https://bitcoinmagazine.com/technical/zerosync-reduces-bitcoin-node-validation
- https://geometry.xyz/notebook/A-light-introduction-to-ZeroSync

### Relevant Links
- https://www.youtube.com/watch?v=pStJqHrJhVs
- https://www.youtube.com/watch?v=Ia-mH6XuFcA

# About the Speaker
Project lead at ZeroSync and open source contributor. 

### Social Links
Github https://github.com/robinlinus/
Twitter https://twitter.com/robin_linus
Website https://robinlinus.com

# Talk Details
### Length of Talk
30 minutes

### Preferred Day/Time Slot 
any

**Comment by iglesiasbrandon** [comment]
Hey @RobinLinus, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The talks on the main stage will be happening on September 8th and 9th; once we accept more, we will assign the day, time, and location.

**Comment by iglesiasbrandon** [comment]
Hey @RobinLinus , We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by RobinLinus** [comment]
ack

**Comment by iglesiasbrandon** [comment]
Closing this issue since this item has been completed! Thank you!
