### ISSUE TITLE
Bitcoin/LN's Place within US Commercial Law

### ISSUE THREAD

**Issue by TKChattoraj** [TABConf/2023.tabconf.com#47]
# Description
### What is this talk about? Give us as many details as possible. 
As Bitcoin adoption increases, it will inevitably be used in (larger and more substantial) commercial transactions--for the purpose of buying and selling goods and services.  This talk examines how US commercial law is coalescing to handle those types of transactions by focusing on the recent proposed revisions to the Uniform Commercial Code (the "UCC").  The UCC is the "protocol" for commercial law in the US.  It is state law and not regulatory in nature.  It's substance grows out of how people actually operate when making commercial transactions.  Thus, there is a certain elegance to it.  

Recently the drafters of the UCC proposed a new Article 12 for the purpose of firmly incorporating Bitcoin into commercial law, using the term "Controllable Electronic Record."      

I am still in the process of writing a paper on this topic and so the below outline is a work in progress:

1. Present a brief overview of the UCC--particularly the protocol for selling goods (Article 2) and taking collateral (Article 9).
2. Discuss the problem for Bitcoin under an unrevised UCC.  (Hint:  It's hard to justify it as having the characteristics of money.)
3. Discuss the details of the proposed Article 12.  I won't outlined all of that here, but simply note that someone who obtains Bitcoin for value, in good faith, without notice of someone else having a claim and who obtains "control" of the Bitcoin, will do so free of anyone else's claim.  This is important because it goes a long way to giving Bitcoin properties of money under the commercial law.  Though, importantly, it is not defined as "money" under the UCC.  
4. We'll examine what it means for Bitcoin to not be defined as money under the UCC.  
5. Along the way, we'll examine how ordinals/inscriptions are handled under the proposed Article 12.  
6. Finish the discussion by pointing out how Bitcoin's development and its incorporation into the UCC is an example of its Common Law/Contract Law nature.  That is Bitcoin is a mechanism of peaceful cooperation among folks rather than some "novel" instrumentality of the state for the purpose of exercising some sort of abstract power.  
### What would an attendee learn from this talk?
An attendee will come away from the talk with an appreciation for how Bitcoin will potentially be treated in US Commercial law.  They will understand what parts of a Bitcoin Transaction have legal significance under the proposed Article 12, the Witness field or the ScriptPubKey?  They will understand how the law looks at a utxo, as being passed from one transaction to the next or created all anew with each transaction, and whether that matters.  Developers will want to understand these things because they underlie how applications should handle Bitcoin/Lighting transactions.  Business Owners will want use this information to guide how and when to use and control Bitcoin.    
### Is there anything folks should read up on before they attend this talk?
The Law Lectures of James Wilson: https://oll.libertyfund.org/title/hall-collected-works-of-james-wilson-vol-1 ... just kidding!  Just come with questions (but if you want to discuss James Wilson--all the better).
# Links
UCC:  https://www.law.cornell.edu/ucc
Proposed UCC Revisions:  https://www.uniformlaws.org/viewdocument/final-act-164?CommunityKey=1457c422-ddb7-40b0-8c76-39a1991651ac&tab=librarydocuments

# About the Speaker
Tarun K. Chattoraj.  I am a Bitcoiner and (reformed) commercial attorney.  I write contracts.  I'm a want-to-be developer--working on a Bitcoin/LN application for managing business contracts that pay out in Bitcoin via Lightning.  
### Social Links
Github:  https://github.com/TKChattoraj
Twitter:  @ChattorajTK
Website:  chattoraj.io and https://chattoraj-portfolio.fly.dev/

# Talk Details
### Length of Talk
30 minutes.
### Preferred Day/Time Slot 
Anytime. 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment]
Hey @TKChattoraj , thank you for submitting an issue for TABConf 2023! As we get closer to the conference, we will review all the issues, and the chosen ones will be added to the TABConf 2023 schedule.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions. Also, please feel free to update the issue description if you'd like to add anything else as we get closer to the event.

**Comment by briimhd** [comment]
This could be interesting as a fireside chat as well...

**Comment by TKChattoraj** [comment]
> 
Thanks.  There is a lot of material here and its is directly applicable to Bitcoin/LN adoption.  I could see the discussion spilling into the lobby afterwards.  First what is the UCC?  It's not a regulation, but state law focused on how folks actually conduct commercial transactions.  This is important to know because we want Bitcoin to be used. Using Bitcoin in commercial means it will be interpreted in light of the UCC.  That the new UCC Article 12 directly addresses Bitcoin is very important and it does so in a way that is generally favorable to Bitcoin.  I will talk about how in the absence of these revisions, there is a hiccup in the law that makes Bitcoin less attractive, in the sense that its less fluid in commerce.  You basically have to be worried that someone might have a previous claim on the Bitcoin.  I'll show what that means in practice.  With the revisions that hiccup is gone, making Bitcoin more "negotiable," more easily transferred without the burdens of worrying if someone has a prior claim on your utxo.  This makes it more like money.  I'll also point out that "money" under the UCC has a special/narrow definition.  Biticoin is not defined as "money" under the revised UCC, but with the revisions, it will obtain many of the features that "money" has under the UCC.  I don't want to just talk about the law, but show how the law relates to Bitcoin on a technical level.  The new Article 12 defines something called a Controllable Electronic Record.  I plan to discuss how a Bitcoin utxo meets the definition of a Controllable Electronic Record.  I also want to discuss how the UCC looks at inscriptions and ordinals.  I'm still putting my thoughts together about that, but I envision that to be an important part of the discussion. The crux of my thoughts on this stem from inscriptions being in the Witness Field distinct from the utxo.  Similarly ordinals are derived from the protocol features, but are not operative within the protocol.  These facets of the transaction and protocol will be important in understanding how the UCC will treat inscriptions and ordinals.  Stay tuned...

**Comment by johnsBeharry** [comment]
+1 for @TKChattoraj been dropping knowledge in our community on living a self sovereign life since last year and I'm always blown away.

**Comment by TKChattoraj** [comment]
Hey-That's awesome its under consideration.  If I can provide more details or info, I'm happy to do so.  I plan to show how the UCC revisions incorporate Bitcoin.  Although the UCC doesn't define Bitcoin as "money," it gives Bitcoin many of the characteristics of money from the UCC's narrow legal perspective. It solves an important existing problem surrounding Bitcoin's commercial use. I'll discuss how the utxo and the private key are the legally operative aspects of the protocol.

**Comment by Kodylow** [comment]
ACK - Super interesting concept, haven't heard this explored anywhere, Tarun was one of our students at B58 so has a good technical understanding to couch this perspective on.

**Comment by iglesiasbrandon** [comment]
Hey @TKChattoraj, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The talks will be happening on September 8th and 9th; once we accept more, we will assign the day, time, and location.

We will do our best to accommodate the day/ time you asked for!

**Comment by TKChattoraj** [comment]
Wow.  Thanks for accepting it.  I'm exited for the whole conference in general and making the talk too.

**Comment by iglesiasbrandon** [comment]
Hey @TKChattoraj , We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by iglesiasbrandon** [comment]
hey @TKChattoraj i need you to ack this issue ^ please see comment above.

**Comment by iglesiasbrandon** [comment]
Hey @TKChattoraj, closing this issue since this has been completed, thank you!

**Comment by TKChattoraj** [comment]
Thank you for giving me the opportunity!
