### ISSUE TITLE
Managing on chain privacy for a lightning wallet

### ISSUE THREAD

**Issue by benthecarman** [TABConf/2023.tabconf.com#48]
# Description
### What is this talk about? Give us as many details as possible. 

Talking about the different challenges come from trying to protect a user's onchain privacy when having to deal with lightning. Can explore the traditional mobile wallet user as well as the large routing node use case. 

### What would an attendee learn from this talk?

Different techniques they can use to protect their privacy as well as ways wallets can be built to protect this. 

### Is there anything folks should read up on before they attend this talk?

Some topics to have a understanding of would be, lightning, coinjoin, pay join, 

### Relevant Links

# About the Speaker
### Social Links
Github benthecarman
Twitter benthecarman
Website benthecarman.com

# Talk Details
### Length of Talk 

30m

### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

Afternoon

**Comment by iglesiasbrandon** [comment]
Hey @benthecarman, thank you for submitting an issue for TABConf 2023! As we get closer to the conference, we will review all the issues, and the chosen ones will be added to the TABConf 2023 schedule.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions. Also, please feel free to update the issue description if you'd like to add anything else as we get closer to the event.

**Comment by iglesiasbrandon** [comment]
Hey @benthecarman, congratulations, this issue has been accepted for TABConf 2023!

The talks on the main stage will be happening on September 8th and 9th; once we accept more, we will assign the day, time.

**Comment by iglesiasbrandon** [comment]
Hey @benthecarman , We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by benthecarman** [comment]
Ack

Thanks!

**Comment by iglesiasbrandon** [comment]
hey @benthecarman , closing this issue since this has been completed, thank you!
