### ISSUE TITLE
Bitcoin Plebs are as important as Bitcoin Devs

### ISSUE THREAD

**Issue by rockstardev** [TABConf/2023.tabconf.com#49]
# Description

### What is this panel discussion about? Please give us as many details as possible. 

I think it would be an interesting idea to have a panel discussion on the importance of **Bitcoin Plebs as a group** in the ecosystem and their interactions with Bitcoin Devs (as a group, as well). The role of Plebs in the Bitcoin community is often undervalued and underrepresented. Plebs are the ones who dedicate their time and resources to spreading the word about Bitcoin and its potential benefits, as well as supporting its growth and development. They are the grassroots of the Bitcoin community and are instrumental in driving adoption and education.

However, it's important to recognize that the relationship between Plebs and Devs is not always harmonious. Panel would also be a good place to discuss this; take look at it from the angle of: at which point Plebs should just let Devs dev? I believe that it's a matter of balance. While Plebs should be encouraged to contribute to the community, they should also respect the expertise and knowledge of the Devs. It's important to allow Devs to do their work and make decisions based on their expertise, but it's also important to provide feedback and ask questions when necessary.

### What would an attendee learn from this talk?

I believe that hosting a panel discussion on this topic would provide attendees with the opportunity to gain a deeper understanding of both the perspectives of Developers and Plebs. Additionally, it would be instrumental in fostering improved understanding and collaboration between these two groups within the Bitcoin community. Overall, the panel could serve as a platform for identifying strategies to enhance communication and collaboration between these two groups, resulting in a more united and robust Bitcoin ecosystem.

### Is there anything folks should read up on before they attend this talk?

To prepare for this talk, it would be beneficial to read any online discussions and watch videos in which both Bitcoin Plebs and Devs are represented. It may also be helpful to define what we mean by plebs before the panel discussion. 

In my own definition, plebs are individuals who spend almost all of their free time on Bitcoin-related activities (whether it's on Nostr, Twitter, Telegram, or other platforms... or in person), in an effort to contribute to the ecosystem. Ideally, they also allocate a percentage of their income to regularly purchase Bitcoin, setting a floor on its price. Additionally, they support developers through donations, support ecosystem through attending conferences, support pretty much the whole ecosystem by investing their time and money into Bitcoin over other hobbies or interests (e.g: NFL, baseball, carpentry, etc).

### Interesting Links

Here are few interesting links to brainstorm on the topic:

  - https://twitter.com/giacomozucco/status/1643643720099561472
  - https://www.reddit.com/r/Bitcoin/comments/12cmq64/estimating_the_plebs_savings_power/
  - https://twitter.com/TheBlueMatt/status/1020056156683849729
  - https://twitter.com/danheld/status/1564990405506174978
  - https://twitter.com/PlebLab/status/1611456201484636160
  - https://twitter.com/AEHW1 (all tweets)

# About the panelists

For this panel, a diverse composition of panelists would be ideal: Pleb, Pleb-Dev, Dev-Pleb, Dev
This would ensure all viewpoints are represented. It's important to have edges of spectrum, especially a Dev who does not identify as a Pleb.

If needed, I can share proposals on panelists directly in private DMs (don't want to put individuals on the spot... it's a criminal offense in US to wrongly identify people belonging to a certain group).

# Panel Discussion Details
Length of the panel discussion: 1 hour
Preferred Day/Time Slot: whenever

**Comment by iglesiasbrandon** [comment]
Hey @rockstardev, thank you for submitting an issue for TABConf 2023! 

Please DM panelists suggestions to @briimhd and @miketwenty1 and they can help coordinate and contact those folks if needed.

**Comment by briimhd** [comment]
@rockstardev love this idea! There's so much to talk about here. As Brandon said, please DM me with your ideas for panelists 🤘

**Comment by thrillerxx** [comment]
Great idea for a panel, would attend this!

**Comment by vicariousdrama** [comment]
This is a great panel idea to help break down some barriers and realize we have far more in common then not.

LOL at this part
> it's a criminal offense in US to wrongly identify people belonging to a certain group

**Comment by rockstardev** [comment]
@iglesiasbrandon: already did
@briimhd: sorry Niece, @miketwenty1 on this
@thrillerxx: plz sir, we need 👍 on the issue, not the 🚀 
@vicariousdrama: lol indeed 😉

**Comment by thrillerxx** [comment]
@rockstardev gotchu brother! Also, I would personally recommend inviting https://github.com/cmdruid and https://github.com/AustinKelsay to join the panel. As two individuals who transitioned from non-developer backgrounds to becoming skilled developers, their unique perspectives would add color to the discussion.

**Comment by AustinKelsay** [comment]
Would love to bring my perspective to this panel as someone whose been on both sides of the fence if you're looking for people.

I went from pleb to dev myself, I helped create the PlebDev lightning course with PlebLab, I run a dev education community in Bitcoin called PlebDevs, and I work at Fold as an engineer.

**Comment by miketwenty1** [comment]
@rockstardev correct me if I'm wrong. You want 4 panelist and 1 moderator for this panel?
- Pleb
- Pleb-Dev
- Dev-Pleb
- Dev

Do you know who you want for these various roles?
I personally think @AustinKelsay could fill the role of "Pleb-Dev" if you want to have him, he seems interested.

**Comment by iglesiasbrandon** [comment]
Hey @rockstardev we have accepted this panel for TABConf 2023! thank you for submitting it! please update the description of the issue with the panelist you choose.

**Comment by murchandamus** [comment]
I think I understand what a “pleb”, a “pleb-dev” and a “dev” are, but what is a “dev-pleb”?

**Comment by iglesiasbrandon** [comment]
I don't know if this is accurate, but the way I read it was: 

- pleb: someone new to Bitcoin
- pleb-dev: someone who is already in Bitcoin but is learning software development
- dev-pleb: someone who is a software developer but is new to Bitcoin
- dev: a software developer that works on Bitcoin projects

Perhaps @rockstardev can confirm or clarify 😄.

**Comment by mh-ash** [comment]
Hope I’m replying in the correct way on here - can’t wait for this one @rockstardev !!!

**Comment by iglesiasbrandon** [comment]
Hey @rockstardev , We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by thrillerxx** [comment]
🙏Could we confirm @AustinKelsay for this panel. He is a big part of the PlebDev movement and a perfect example of it.

**Comment by iglesiasbrandon** [comment]
> Hey @rockstardev , We have added a day, time slot, and length to this issue. You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6
> 
> Please acknowledge by commenting 'ack'.
> 
> This will confirm your talk for TABConf 2023! If we need to make any changes, you will be notified on this issue.

Hey @rockstardev please note, i updated the time slot of your panel to 4:30 - 5:15 PM

**Comment by iglesiasbrandon** [comment]
hey @rockstardev can you ack this issue please?

**Comment by bitkarrot** [comment]
A related Tabconf talk worth mentioning here! @Bitc0indad

https://github.com/TABConf/2023.tabconf.com/issues/182

**Comment by Bitc0indad** [comment]
I'm available for Friday and Saturday panel discussions representing PLEBNET.DEV started from nothing with mentorship and direction I avoided tutorial hell...The mantra "Learn, Build, and PR Feedback Loop" is our drumbeat!

**Comment by justingoldberg** [comment]
> 

@Bitc0indad There's a three letter acronym that describes the process from learning to action. I forgot it, but I remember it's meaning: 

1. you watch someone else doing something
2. then you do it yourself (with them watching and providing a minimal effective dose of guidance where needed)
3. finally, you are doing it on your own.

**Comment by iglesiasbrandon** [comment]
Closing this issue, thank you @rockstardev!
