### ISSUE TITLE
Miniscript Discussion

### ISSUE THREAD

**Issue by Rob1Ham** [TABConf/2023.tabconf.com#51]
# Description
### What is this workshop about? Provide as many details as possible. 

The workshop is about how to leverage miniscript on your bitcoin project. I recently did a presentation at BTC++, so I'll be building on top of the slides shared there. Here is a [link](https://docs.google.com/presentation/d/1nAEVrOfKpvvCw1uuOsuVxhFC538QDwaCPq_G5tslvRA/edit?usp=sharing) to those slides.

### What would an attendee learn from this workshop?

- What is Bitcoin Script
- What is miniscript
- How to leverage BDK to build miniscript enabled output descriptors

### Is there anything attendees should read up on before they attend this talk?

- check out [miniscript.com](miniscript.com) for the reference documentation on what bitcoin script is
- if you want a preview, check out [bitcoin dev kit's playground](https://bitcoindevkit.org/bdk-cli/playground/)

### Command Line Tutorial 
- Install rust: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
Link to workshop Gist: https://gist.github.com/Rob1Ham/e34017e14fe228c9f62286ede5910601

### BDK Elephant
Site: https://elephant.bitcoindevkit.org/
Coordination Google Doc: https://docs.google.com/spreadsheets/d/1bJqAl7q6R3bNAAbD0p-rq73KbGbR1Wiwk2Oj83mcebM/edit#gid=0

# About the Speaker
### Social Links
Github: Rob1Ham
Twitter: twitter.com/rob1ham
Website: anchorwatch.com

# Workshop Details
### Length of workshop
I can do 30 minutes of discussion with some time for Q&A, depending on my free time maybe i'll get some more interactive code stood up for people to check out prior to the event, hard to say this far out if I will get that online in time.

### Preferred Day/Time Slot

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

No preference, I plan on being there for the whole conference so whenever works for you.

address: tb1q3sq0qfdqwnr8k85j8v2xmezlyyuhvv62n7n029
Amount: 100000

**Comment by iglesiasbrandon** [comment]
Hey @Rob1Ham, thank you for submitting an issue for TABConf 2023!

When you get a chance to update the description please remove the needs details label!

**Comment by miketwenty1** [comment]
im excited for this one.

**Comment by Rob1Ham** [comment]
Updated with some initial comments! I hope to build on top of some reference code to make this much more interactive come time for TABConf!

**Comment by iglesiasbrandon** [comment]
Fantastic, thanks @Rob1Ham I'm looking forward to this workshop!

**Comment by Rob1Ham** [comment]
I just realized I have a conflict on the 8th/9th, so I definitely need to do my workshop early on the 7th so I can travel and leave tabconf early 😭😭😭

**Comment by miketwenty1** [comment]
@Rob1Ham would you be able to do this on the 6th? (so you're not rushed on the 7th).

**Comment by Rob1Ham** [comment]
For sure, I haven't booked travel yet, but I'll make sure i'm in town on or
before the 6th

**Comment by iglesiasbrandon** [comment]
Hey @Rob1Ham congratulations, this issue has been accepted for TABConf 2023!

It would be great if you could make the session interactive like you mentioned in the description. Lets get people actually building with miniscript by the end of this workshop! We can allocate more than 1 hour if needed; just let us know. 

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The workshops will be happening on September 6th and 7th; once we accept some more, we will assign the day, time, and location.

**Comment by Rob1Ham** [comment]
Amazing! I have my hands full the next few weeks, but can definitely make this an interactive workshop, and i'll even be able to provide some sample/test signers for people to mess around as well!

**Comment by Rob1Ham** [comment]
Can my talk be slotted for later in the day? I’m flying back from Riga and get in around noon on Wednesday.

**Comment by iglesiasbrandon** [comment]
Hey @Rob1Ham we will slot this workshop for Thursday instead. thanks for letting us know!

**Comment by Rob1Ham** [comment]
Ok Great, I am flying out thursday evening, so earlier in the day Thursday
would be great. Thank you!

**Comment by iglesiasbrandon** [comment]
Hey @Rob1Ham  , We have added a day, time slot, and length to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/4

Please acknowledge by commenting 'ack'.

This will confirm your workshop for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by Rob1Ham** [comment]
ack

**Comment by miketwenty1** [comment]
@Rob1Ham 

We are about a week away from the start of the conference. I'm sending this to all accepted upcoming workshop. Please review and ensure you have a clear, up to date, high level, agenda on this GitHub issue. Please buffer in time to help with unexpected problems and questions.

TABConf workshops should aim to involve high levels participation. If you're planning to conduct a live demo, please consider that attendees will require clear instructions on how to prepare for following along, (all steps for setup should be double checked) and any presentation should be structured accordingly.
Participants should leave the workshop either with something built, (be it physical or digital), or with specific knowledge gained from the __hands on/interactive__ experience.

**Comment by iglesiasbrandon** [comment]
Hey @Rob1Ham  , I am closing this issue since you have completed the workshop. Thank you for all of the effort you put into it!
