### ISSUE TITLE
Coworking, Hackerspace, Incubator, Accelerator: How Bitcoin-Focused Community Spaces Impact the Industry

### ISSUE THREAD

**Issue by bnonni** [TABConf/2023.tabconf.com#52]
# Description
### What is this panel discussion about? Please give us as many details as possible. 
Discussion about the emergence of physical, bitcoin-focused coworking, hacker spaces, incubators and accelerators: their importance, why they matter, how they impact the overall ecosystem, how they impact the process of building builders, how they impact the goal of global bitcoin adoption.

### What would an attendee learn from this talk?
- Why should I care?
- How to join one or get involved in my city?
- My city doesn't have a space, how do I start one? (problems & solutions, tips & tricks, etc.)
- I'm not a dev, can I still join and make an impact?
- What value can I gain from participating in or starting a space?
- What value can I bring to the table for my local space or my community?
- What events are coming up in my city at the local space?
- What can I learn by attending events at my local space?
- How do I ensure I provide value to my community as a space organizer?
- How to engage and grow my space's community?

### Is there anything folks should read up on before they attend this talk?
Checkout websites for other coworking, hackerspaces, incubators, accelerators. See relevant links below.

### Relevant Links
- https://www.bitcoincommons.com/ (coworking)
- https://www.pleblab.com/ (hackerspace + accelerator)
- https://bitcoinpark.co/ (coworking + hackerspace + community event space)
- https://wolfnyc.com/ (accelerator)
- https://hack.bs.it/ (hackerspace)
- https://atlbitlab.com/ (coworking + hackerspace)

Please comment on this issue with a coworking, hackerspace, incubator, accelerator program I may have missed!

# About the panelists
Moderator: 
- Kim Castner, [Voltage](https://voltage.cloud/)
    - Twitter: [@dont_grow_weary](https://twitter.com/dont_grow_weary)
    - Nostr: [npub](https://snort.social/p/npub1jv6j6dpum7dgrdn8jm5gqnt5vv3g4eqfj55etgxsaa56dnkp3smq67g7he)

Panelists:
- Brian Atchue, [WolfNYC](https://wolfnyc.com/)
    - Twitter: [@BrianAtchue](https://twitter.com/BrianAtchue)
    - GitHub: @brianatchue
- Car, [PlebLab](https://www.pleblab.com/)
    - Twitter: [@ThrillerX_](https://twitter.com/ThrillerX_)
    - GitHub: @thrillerxx
- Kaily Buemi, [Unchained](https://unchained.com/) / [Bitcoin Commons](https://www.bitcoincommons.com/)
    - Twitter: [@kailybuemi](https://twitter.com/kailybuemi)
    - GitHub: @KailyB
    - Nostr: [npub](https://snort.social/p/npub1rtqagw775d0f936mghe2x8unkt74t4d8ncs3zktet96kahpfypjs74wra8)
- Bryan Nonni, [ATL BitLab](https://atlbitlab.com/ )
    - Twitter: [@nonni_io](https://twitter.com/nonni_io)
    - GitHub: @bnonni
    - Nostr: [npub](https://snort.social/p/npub1nh0klcapjnfnpfkxufu2gv4wzvy72txqskrj2jen0585j8ml7epqp5scfr)
- Josh Castner, [Bitcoin Park](https://bitcoinpark.com/)
    - Twitter: [@JoshBitcoinPark](https://twitter.com/JoshBitcoinPark)
    - Discord: @joshbitcoinpark
    - Nostr: [npub](https://snort.social/p/npub1j0sh8peshr8rthgn0hlh2mxqwaazne3kc3rqsm0y7ysssg77wd8smfga0n)

# Panel Discussion Details
### Length of the panel discussion
30 min - 1 hour

### Preferred Day/Time Slot
Whatever makes sense. Feels like a good panel for the morning, post-caffeine, but could also be good in the afternoon post lunchtime. I defer date / time selection to TAB organizers.

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment]
Hey @bnonni , thank you for submitting an issue for TABConf 2023!

Also, please feel free to update the issue description if you'd like to add anything else as we get closer to the event.

**Comment by bnonni** [comment]
@iglesiasbrandon Sounds good! On that note, what is the process for finding panelists for a proposed panel discussion such as this one?

**Comment by thrillerxx** [comment]
Would absolutely be thrilled to be a part of this event. We've all been in touch behind the scenes, and our collective knowledge will make for an incredible experience. I have a ton of insights about hackerspaces, writing an article on the subject not too long ago. Check it out here: https://www.thrillerbitcoin.com/hackerspaces-sunday-orange-flow/

**Comment by brianatchue** [comment]
Sounds great!

**Comment by iglesiasbrandon** [comment]
> @iglesiasbrandon Sounds good! On that note, what is the process for finding panelists for a proposed panel discussion such as this one?

Thats a great question @bnonni i created a 'Speakers Wanted' label for folks to assign to issues if they need speakers or if they want to submit an idea but don't necessarily want to be the speaker.

**Comment by brianatchue** [comment]
I'd be interested in joining the panel. Brian Atchue Head of Marketing and Operations for Wolf.

**Comment by bnonni** [comment]
@brianatchue @thrillerxx awesome! I’ll update the issue accordingly to include you both.

**Comment by ejuline** [comment]
Bryan, Chis is a crucial subject to growth of the communities. I could put you in touch with our Head of Community, George Mekhail. He has some fantastic resources. Ed

**Comment by bnonni** [comment]
@ejuline that would be awesome! Please do! You should have my contact info. Feel free to start an email thread :)

**Comment by iglesiasbrandon** [comment]
Hey @RobinLinus, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The talks/ panels on the main stage will be on September 8th and 9th; once we accept more, we will assign the day, time, and location.

**Comment by iglesiasbrandon** [comment]
Hey @bnonni, We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by iglesiasbrandon** [comment]
Hey @bnonni  I'm closing this issue since it's been completed! Thank you!
