### ISSUE TITLE
BlockTube: How to Upload Bitcoin Block Files to YouTube

### ISSUE THREAD

**Issue by bnonni** [TABConf/2023.tabconf.com#53]
# Description
### What is this workshop about? Provide as many details as possible.
A neat and slightly impractical way to store backups of the entire bitcoin blockchain on YouTube servers as tarballs embedded into videos. I'll share my journey from "that's a neat idea" to "alright *cracks knuckles* lets actually do this" including challenges I faced, software iterations, etc.

### What would an attendee learn from this workshop?
What data is important for rebuilding the Bitcoin blockchain in the event of a loss of network nodes, how this storage glitch works and what software to use to do it, how I built a program to compress blk.dat files into tgz files and embed the tgzs into an .avi video file, how JS sucks for this kind of task and how Rust is superior, how to go from raw file to video file (i.e. compress a blk.dat file into a blk.dat.tgz, etch blk.dat.tgz into blk.dat.avi).

### Is there anything attendees should read up on before they attend this talk?
See relevant links

### Is there anything attendees should set up before the workshop?
- Install Rust https://www.rust-lang.org/tools/install (required if you want to follow along)
- Signup for a YouTube account (required if you want to follow along)
- Clone the repo https://github.com/bnonni/BlockTube (required if you want to follow along)
- Familiarize yourself with [`isg_4real`](https://github.com/bnonni/Infinite-Storage-Glitch) (optional)

**If you don't want to follow along with the technical stuff, then you can skip the above steps.

### Relevant Links
- https://learnmeabitcoin.com/technical/blkdat
- https://www.rust-lang.org/tools/install
- https://github.com/bnonni/Infinite-Storage-Glitch
- https://github.com/bnonni/BlockTube

# About the Speaker
### Social Links
- Github: @bnonni
- Twitter: [@nonni_io](https://twitter.com/nonni_io)
- Website: [bryan.nonni.io](https://bryan.nonni.io/)
- Nostr: [npub1nh0klcapjnfnpfkxufu2gv4wzvy72txqskrj2jen0585j8ml7epqp5scfr](https://snort.social/p/npub1nh0klcapjnfnpfkxufu2gv4wzvy72txqskrj2jen0585j8ml7epqp5scfr)

# Workshop Details
### Length of workshop
30 min - 1 hour

### Preferred Day/Time Slot
Anytime is fine with me
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment]
Hey @bnonni , thank you for submitting an issue for TABConf 2023!

Also, please feel free to update the issue description if you'd like to add anything else as we get closer to the event.

**Comment by bnonni** [comment]
Closing to focus on other content :)
