### ISSUE TITLE
Grow mushrooms at home, make first aid ointments, and tie dye for fun! (while we build bitcoin, run miners, sync nodes, and write nostr notes!)

### ISSUE THREAD

**Issue by CarolineSimply** [TABConf/2023.tabconf.com#54]
# This workshop is a reminder to focus on our other useful skills in the natural world. While we are immersed in the technical world of bitcoin we need to take time to grow our other practical skills! 

### Social Links
Find Eric @bitcoin_rail
Nostr npub: npub1k5xvvcj5e9y8vphgtkd9g6l3fkpzzvedljpl23s3zqa28777fa7sqn27vn

Find Carolyn @cornfordogs
Nostr npub: npub1ke3eru0fsqss7kp33e394uu5wuh9yjhte2dd08klmx47pq9jv0gscg2uas

# Workshop Details
### For those with interest, we can share some pre-work videos/readings but just showing up will work too. We would love to hear from those who are interested in engaging so we prioritize what people are most interested in learning.

![IMG_9944](https://user-images.githubusercontent.com/115885793/231895423-ab27f524-3fbd-4932-aea5-74d6f71e836c.jpg)
![IMG_0377](https://user-images.githubusercontent.com/115885793/231894989-bb449a57-3971-4fc1-9f57-f895a5258ef0.jpg)
![IMG_9921](https://user-images.githubusercontent.com/115885793/231895435-ba098435-3dad-48e3-87f5-543183a876e1.jpg)
![IMG_9918](https://user-images.githubusercontent.com/115885793/231895518-1dd7cc2b-c734-4b30-9167-a4669d2f91df.jpg)

**Comment by iglesiasbrandon** [comment]
Hey @CarolineSimply, thank you for submitting an issue for TABConf 2023! We will review all the issues as we get closer to the conference. 

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions. Also, please feel free to update the issue description if you'd like to add anything else as we get closer to the event.

**Comment by EllyPembroke** [comment]
NextGen village #76 is all about passing on valuable information such as this. We're happy to put you on the schedule. What kind of seating arrangement would you prefer? Would you like to present from the stage or would participants gather around tables? Apart from the workshop we could also have a table/booth/station.

**Comment by CarolineSimply** [comment]
@EllyPembroke Thank you! That's what I thought too! I envision a mix so maybe a mini-presentation from the stage and some hands on. If we have a sense of participant numbers I can bring equipment to tie up something to tie dye, people can fold/prepare -- see ice dye demo --- but do theirs at home :) Mushroom stuff we can demo / do something hands on too :)

First aid weeds --I'll think through how to do. 
@iglesiasbrandon which day of week is day 3 or day 4? @EllyPembroke are you thinking we repeat the session day 4 if successful day 3?
I'll figure out flights soon and won't be there the whole time :( 
also, I'd like to lock in time frame but would prefer to see where some of the main stage sessions land and work around what I really want to listen to. Possible?

**Comment by CarolineSimply** [comment]
Oh, I see day 3 and 4 will be sept 8 and 9. I'll plan accordingly!
More than likely will prefer a late morning or early afternoon time slot....

**Comment by CarolineSimply** [comment]
@iglesiasbrandon @EllyPembroke 

Brandon---I welcome some help from local atlanta bitcoiners to get some supplies to the venue for our session re: growing mushrooms at home, making salves, etc (next gen village, day 3, possible repeat day 4):
- single burner (camp stove) with a propane can (or something electric) to melt beeswax
- small saucepan we can "ruin" with beeswax melted in it
- a sports water jug we can fill with venue/hotel ice for tie dye demo
- tarp (for covering the floor for a demo with dyes, just as extra precaution)
- a small/medium size plastic tote the ice can drip into
- a metal grate (think oven shelf or similar) that can sit on top the tote or in the tote but at least 3 inches above the bottom
- some soft cardboard boxes (sparkling water, soda, beer) that we can use to shape around the tie dye products

I will be able to easily fly with everything else...let me know if there are challenges with any of this? :)

**Comment by Bitc0indad** [comment]
Now this sounds like a great time!

**Comment by iglesiasbrandon** [comment]
hey @CarolineSimply , closing this issue since this has been completed, thank you!
