### ISSUE TITLE
Arctica Open Source Hardware Wallet and Miniscript Multisignature Desktop Wallet

### ISSUE THREAD

**Issue by wild-kard** [TABConf/2023.tabconf.com#55]
# Description
### What is this project about? Please give us as many details as possible.
Arctica is native desktop application built on top of Rust & Vue.js that utilizes a local instance of Bitcoin Core as it's backend.

The software is targeted at non technical users and achieves two primary functions.
1) [completed/ Beta testing] The creation of open source hardware wallets on generic hardware devices such as SD cards or USB sticks, through a series of instructions and 1 click prompts provided to the user. The hardware wallets employ a "layered multisig" to achieve device level encryption of privacy and security sensitive information such as wallet files, private & public keys, and descriptors.

2) [completed/ Beta testing] A standalone desktop application that employs the use of 7 Arctica Hardware wallets to establish a seamless Multi-signature Bitcoin Cold Storage wallet. This application handles everything from security & privacy to sending & receiving bitcoin with a non-technical, UX centered approach.

### Is it a FOSS or Open Source project?
This project is FOSS. 

### What would an attendee learn from visiting this projects table at Builder Days?
How our open source hardware wallet works under the hood. How easy arctica is to setup and use for non technical users. The security and privacy advantages of the Arctica Software Protocol. This includes...

- A free & open source code base 
- the Advantages of generic hardware 
- the benefits of fully encrypted keys, descriptors, & wallet files
- the enhanced security & recoverability/redundancy offerings of multisig cold storage
- multiple wallets with different security profiles (currently 2 of 7 wallet and a 5 of 7 wallet with a time lock)
- The importance of running a local full node to validate incoming transactions
- The advantages of digital key & descriptor backups on CD/DVD, alleviating users from the necessity of handwriting and storing unencrypted physical copies of seed phrases or descriptors.

As well, attendees could gain an understanding of the development roadmap of arctica which plans to implement a number of useful features... 

- decryption of individual hardware wallets via a blind pin server
- timed spend threshold & privacy key decay for inheritance
- Advanced Timelock Recovery Features
- A duress feature
- A tripwire feature
- Enhanced Accessibility & UX improvements
- Connectivity over TOR

Additionally users can learn how they could easily build on top of the open source hardware wallets created by the Arctica software to enable a wide variety of custom desired features. 

I built this project as a solo junior developer with very little experience, so I also think I could lend valuable insights to new/aspiring coders on how to get started working on FOSS projects.

### Is there anything people should read up on before finding the table at Builder Day?
A general understanding of the usefulness of multisig cold storage & device security. As well as a general understanding of Miniscript.

### Relevant Links

GitHub Repo: 
https://github.com/wild-kard/arctica

# Project Details

### Who will run the table? Are those people current contributors or maintainers who can answer questions and get people onboarded?
Myself - Lead Project Developer

**Comment by iglesiasbrandon** [comment]
Hey, @wild-kard thank you for submitting an issue for TABConf 2023 Builder days!

**Comment by Rob1Ham** [comment]
Hope I can be in town to see this one!

**Comment by wild-kard** [comment]
@iglesiasbrandon how will I know if my project has been approved? 

And assuming it does get approved, do builders need to purchase general admission tickets?

**Comment by iglesiasbrandon** [comment]
Hey @wild-kard, 4-8 weeks before the conference, we will start adding all of the issues to the official GitHub project, and they will have a status field that will indicate if the issue has been approved and added to the schedule. (since this is a builder days project it will most likely be approved because the builder day projects don't have specific time slots. each builder days project will have a table for day 1 & 2 of the conference where folks can learn about the project and hopefully become contributors! 

We try to get as many people as possible to purchase tickets if they can. TABConf is run at cost, and the ticket sales help us cover the expenses of the conference. We make them as affordable as possible; they are currently $121. We also have a grant program where folks can apply for a ticket (https://2023.tabconf.com/grants)

**Comment by iglesiasbrandon** [comment]
Hey @wild-kard, congratulations, this issue has been accepted for TABConf 2023. It has been added to the official GitHub Project schedule. The builder Days tables will be on all day on September 6th and 7th
