### ISSUE TITLE
Spacechain: a modest sidechain proposal

### ISSUE THREAD

**Issue by supertestnet** [TABConf/2023.tabconf.com#56]
# Description
### What is this workshop about? Provide as many details as possible. 

- What spacechains are
- How they work
- How anyprevout can help
- Comparison with other sidechains
- Spacechain use cases
- Demo that works today
- Q&A

### What would an attendee learn from this workshop?

Spacechains let us create robust sidechains with better doublespend protection and better censorship resistance than more popular models because they use blind merge mining to inherit bitcoin's proof of work. The downside is that they do not provide a great solution for actually getting bitcoins onto and off of a spacechain, so you either need to use an existing model for that (such as a multisig federation) or build sidechains where that's not necessary.

### Is there anything attendees should read up on before they attend this talk?

See relevant links

### Is there anything attendees should set up before the workshop?

No, we will use a browser based tool to launch a spacechain together, so attendees only need a computer with a regular web browser

### Relevant Links

- Shinobi, [Spacechain: how it works](https://bitcoinmagazine.com/technical/how-bitcoin-spacechains-work)
- Shinobi, [Spacechain use cases](https://bitcoinmagazine.com/technical/spacechains-unlocks-bitcoin-use-cases)
- Somsen, [Spacechain in four minutes](https://youtu.be/Ti1vRQMg_qE)
- Super Testnet, [Spacechain launcher](https://github.com/supertestnet/spacechain-launcher)
- Fiatjaf, [Soma (Spacechain-inspired open market for assets)](https://github.com/nbd-wtf/soma)

# About the Speaker

Super Testnet is a freelance software developer with a focus on bitcoin, lightning, and nostr. He is also the chairman of free and open source software at Pleblab

### Social Links
Github: https://github.com/supertestnet
Twitter: https://twitter.com/super_testnet

# Workshop Details
### Length of workshop

1 hour

### Preferred Day/Time Slot 

Anything works for me

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by briimhd** [comment]
I like this a lot

**Comment by iglesiasbrandon** [comment]
Hey @supertestnet, thank you for submitting an issue for TABConf 2023! We will review all the issues as we get closer to the conference.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions. Also, please feel free to update the issue description if you'd like to add anything else as we get closer to the event.

**Comment by miketwenty1** [comment]
@supertestnet do you feel this is more of a talk rather than a workshop?
Do you intend there being participation with attendees?

**Comment by supertestnet** [comment]
> @supertestnet do you feel this is more of a talk rather than a workshop? Do you intend there being participation with attendees?

It's a workshop because after learning how spacechains work the audience actually uses a launcher tool I created to make a spacechain and examine it firsthand. But at btc++ I think only two people actually did this, the rest of the people just watched as I did it up on the screen. I suspect the same thing for tabconf.

**Comment by iglesiasbrandon** [comment]
Hey @supertestnet, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The workshops will be happening on September 6th and 7th; once we accept some more, we will assign the day, time, and location.

**Comment by supertestnet** [comment]
Woot! Super excited to attend and showcase the power of spacechains for everyone

**Comment by iglesiasbrandon** [comment]
Hey @supertestnet , We have added a day, time slot, and length to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/4

Please acknowledge by commenting 'ack'.

This will confirm your workshop for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by miketwenty1** [comment]
@supertestnet 

We are about a week away from the start of the conference. I'm sending this to all accepted upcoming workshop. Please review and ensure you have a clear, up to date, high level, agenda on this GitHub issue. Please buffer in time to help with unexpected problems and questions.

TABConf workshops should aim to involve high levels participation. If you're planning to conduct a live demo, please consider that attendees will require clear instructions on how to prepare for following along, (all steps for setup should be double checked) and any presentation should be structured accordingly.
Participants should leave the workshop either with something built, (be it physical or digital), or with specific knowledge gained from the __hands on/interactive__ experience.

**Comment by iglesiasbrandon** [comment]
Hey @supertestnet  , I am closing this issue since you have completed the workshop. Thank you for all of the effort you put into it!
