### ISSUE TITLE
Paid Nostr Relay

### ISSUE THREAD

**Issue by yeg0rpetrov** [TABConf/2023.tabconf.com#58]
# Description. 
How to set up nostr relay. 
### What is this workshop about? Provide as many details as possible. 

To walk through the paid nostr relay. What is the  difference between paid vs none paid. How to install. What is the hardware needed. Why it's important.

### What would an attendee learn from this workshop?

Attendees will learn how to run their paid relay and contribute to the Nostr ecosystem. 

### Is there anything attendees should read up on before they attend this talk?

I would suggest to check out 
the guide written by Andre Neves:

https://andreneves.xyz/p/how-to-setup-a-paid-nostr-relay

### Relevant Links

# Cameri
### Social Links npub1qqqqqqyz0la2jjl752yv8h7wgs3v098mh9nztd4nr6gynaef6uqqt0n47m
Github https://github.com/Cameri/nostream
Website https://eden.nostr.land

# ...
### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.* 
Up to organizers schedule

**Comment by iglesiasbrandon** [comment]
Hey @yeg0rpetrov, thank you for submitting an issue for TABConf 2023! We will review all the issues as we get closer to the conference.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions. Also, please feel free to update the issue description if you'd like to add anything else as we get closer to the event.

**Comment by iglesiasbrandon** [comment]
Hey @yeg0rpetrov , congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The workshops will be happening on September 6th and 7th; once we accept some more, we will assign the day, time, and location.

**Comment by yeg0rpetrov** [comment]
Hey 👋 That's sounds like a big deal! Also I just proposed it and didn't mean to run actual workshop. Still don't know if I will be able to make it to the conf:/ Maybe Cameri will be interested to do it https://github.com/Cameri

**Comment by iglesiasbrandon** [comment]
Hey @yeg0rpetrov can you send this over to Cameri and ask if they would be interested in hosting this workshop?

**Comment by yeg0rpetrov** [comment]
Had a talk with cameri and he will not be able to come😬

**Comment by iglesiasbrandon** [comment]
hey @yeg0rpetrov dang im sorry to hear that! should we close this issue? or move it back to proposal status and add the speakers wanted label?

**Comment by andrerfneves** [comment]
👋

**Comment by andrerfneves** [comment]
Maybe this doesn't need to be a whole hour long? And more of a HOW TO SETUP NOSTREAM? That way we can setup a public relay, and a paid relay through ZBD API? Happy to help here in Cameri's absence. Just an idea

**Comment by yeg0rpetrov** [comment]
Yeap I guess that would make sense. Andre, will you be able to run this one ? Thank you

**Comment by miketwenty1** [comment]
I think https://github.com/TABConf/2023.tabconf.com/issues/125 these ideas may be able to be combined into a builders day table.. I don't believe we have anymore room in the official workshop schedule.

**Comment by miketwenty1** [comment]
@yeg0rpetrov it seems this submission failed to get accepted this year, I appreciate the submission, this talk seemed pretty interesting. One of our big criteria for accepting talks is reputation and community involvement around a topic. We also sort and order issues by 👍 emojis as one way to help understand how many people are excited to see a various talk/panel/workshop. Please consider submitting another idea next year. We'll be accepting talks for TABConf 6 in about 5-6 months.
