### ISSUE TITLE
Base58's Protocol Village

### ISSUE THREAD

**Issue by niftynei** [TABConf/2023.tabconf.com#59]
# Description

Village focused on protocols in the bitcoin space, including:
- bitcoin
- nostr
- lightning
- cryptography

Our village will consist of:
- protocol implementation walkthrus, 
- the World Famous Bitcoin Live-Action Role-Play (LARP), 
- a protocol design competition
- some live-coding demos from protocol focused projects
- talks from protocol developers across the ecosystem

# Project Details

This will be a village run and hosted by [Base58](https://base58.info), a bitcoin protocol academy. Last year we ran a live-coding demo at TABConf. This year, we'd like to do this in addition to more hands-on learning opportunities.

**Comment by iglesiasbrandon** [comment]
sounds awesome, thanks @niftynei!

**Comment by iglesiasbrandon** [comment]
Hey @niftynei, congratulations, this Village has been accepted for TABConf 2023!

We will work with you and the village leaders to get the programming for the village into GitHub and onto the official project schedule. 

The Villages will be happening on September 8th and 9th.

**Comment by niftynei** [comment]
sick! super stoked!!
