### ISSUE TITLE
Improving Lightning Mobile Wallets with Rapid Gossip Sync

### ISSUE THREAD

**Issue by ecurrencyhodler** [TABConf/2023.tabconf.com#6]
# Description
Rapid gossip sync is a protocol that allows nodes to catch up with channel gossip data by relying on semi-trusted servers.

### What is this talk about? Give us as many details as possible. 
Firstly, the idea of Rapid Gossip Sync is that gossip data is pre-processed by one or multiple semi-trusted servers. These validate the signatures sent via regular gossip and verify the channels against the blockchain. This should obviate client-side signature verification and allow us to entirely remove signatures from the messages.

Secondly, the server sends batches of gossip data, representing snapshots of recent channel graphs. Given that the server batches the data, global properties across all announcements and updates (such as the chain hash) can be stripped out and sent just once. Similarly, since clients are primarily interested in new information, a single timestamp (the latest one) suffices to determine what data the client has or hasn't seen before when it requests the latest gossip snapshot.

The most crucial optimization that comes with Rapid Gossip Sync is that it doesn't send redundant updates. So even if a node sends 100 channel updates, and the only mutated property is its base fee, there would be no need to send out any other unchanged properties. To do that, we overloaded the channel flag byte, which would otherwise only use two bits to indicate an update's affected direction and whether a channel is disabled.

Channel updates are sent frequently and often refer to channels the client hasn't seen before, meaning that the server must include all properties, not just the mutated ones. This realization led us to notice that many properties were set to the same value across different channel updates, so we decided to measure what values occurred most frequently. Then, to reduce data overhead, we declare those most commonly occurring values as defaults at the start of every gossip snapshot. Any property whose value matches the default can be omitted from the snapshot if a channel update refers to a previously unknown channel. The only difficulty arising from that optimization is distinguishing whether a channel update is new or incremental. As it happens, the last remaining bit of the channel flags lends itself perfectly for this purpose. This way, when an update is new, a set property bit will indicate a deviation from the default specified at the beginning of the snapshot. Otherwise, that same bit, when set, would instead indicate a mutation. In either case, when a property's bit flag is not set, its corresponding value needn't be sent over the wire.

Finally, short channel IDs need to be specified for each announcement and update. Since they require 8 bytes per message, we were able to reduce memory requirements by sorting announcements and updates incrementally, and then successively specifying channel IDs in terms of their relative delta, which can be expressed in fewer than 8 bytes by using the BigSize data type.

### What would an attendee learn from this talk?
The technical details behind rapid gossip sync.

### Relevant Links
https://lightningdevkit.org/blog/announcing-rapid-gossip-sync/

# About the Speaker
Arik works on LDK at Spiral

### Social Links
Twitter
https://twitter.com/arikaleph

# Talk Details
### Length of Talk
30 minutes

### Preferred Day/Time Slot 
TBD

**Comment by iglesiasbrandon** [comment]
Hello @ecurrencyhodler! Thank you for submitting a Talk issue for TABConf 2023! You are among the first to submit! As we get closer to the conference, we will review all the issues, and the chosen ones will be added to the TABConf 2023 schedule: https://github.com/orgs/TABConf/projects/1.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions about your submission. (thanks for adding a detailed description!)

**Comment by iglesiasbrandon** [comment]
Hey @ecurrencyhodler, We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes you will be notified on this issue.

**Comment by iglesiasbrandon** [comment]
ahh yes sorry about that @ecurrencyhodler! @arik-so

**Comment by iglesiasbrandon** [comment]
hey @arik-so, I am closing this issue since it's completed. Thank you for all of the effort you put into it!
