### ISSUE TITLE
Hacking nostr for bitcoin privacy

### ISSUE THREAD

**Issue by benthecarman** [TABConf/2023.tabconf.com#60]
# Description
### What is this talk about? Give us as many details as possible. 

Discussing various techniques that we can use nostr as a bitcoin privacy tool. From things like NIP-89, to things like payjoin and coinjoin, even how it can be used for lightning. 

### What would an attendee learn from this talk?

Different bitcoin privacy techniques and how they can be enhanced through nostr. 

### Is there anything folks should read up on before they attend this talk?

What is nostr and some bitcoin privacy basics. 

### Relevant Links

https://github.com/nostr-protocol/nips/pull/476

# About the Speaker
### Social Links
Github benthecarman
Twitter benthecarman
Website benthecarman.com
Nostr ben@benthecarman.com

# Talk Details
### Length of Talk

30 mins

### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

Afternoon

**Comment by iglesiasbrandon** [comment]
@benthecarman, thank you for submitting an issue for TABConf 2023! We will review all the issues as we get closer to the conference.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions. Also, please feel free to update the issue description if you'd like to add anything else as we get closer to the event.

**Comment by miketwenty1** [comment]
@benthecarman it seems this submission failed to get accepted this year, I appreciate the submission. One of our big criteria for accepting talks is reputation and community involvement around a topic. We also sort and order issues by 👍 emojis as one way to help understand how many people are excited to see a various talk/panel/workshop. Please consider submitting another idea next year. We'll be accepting talks for TABConf 6 in about 5-6 months.
