### ISSUE TITLE
Mutiny Wallet Builder Day

### ISSUE THREAD

**Issue by benthecarman** [TABConf/2023.tabconf.com#61]
# Description
### What is this project about? Please give us as many details as possible.

Mutiny is a bitcoin and lightning wallet with best practices built in. It is a rust library built on top of ldk and bdk. Mutiny compiles to wasm and can be easily packaged to have lightning capabilities in the browser. 

### Is it a FOSS or Open Source project?

MIT

### What would an attendee learn from visiting this projects table at Builder Days

If they are a front end / Javascript developer they could learn to setup mutiny and start building their own application on top of the mutiny sdk. 

If they are a rust developer they can learn to setup and start contributing to Mutiny's backend. 

### Is there anything people should read up on before finding the table at Builder Day?

What is WASM

### Relevant Links
GitHub Repo: 

https://github.com/MutinyWallet/mutiny-node

# Project Details
### Who will run the table? Are those people current contributors or maintainers who can answer questions and get people onboarded?

Just I will be there

**Comment by iglesiasbrandon** [comment]
Hey @benthecarman, congratulations, this issue has been accepted for TABConf 2023. It has been added to the official GitHub Project schedule. The builder Days tables will be on all day on September 6th and 7th

**Comment by benthecarman** [comment]
LFG
