### ISSUE TITLE
How to package services for StartOS v0.4.0

### ISSUE THREAD

**Issue by MattDHill** [TABConf/2023.tabconf.com#63]
# Description
Start9's StartOS (formerly embassyOS) is the world's best (and perhaps only) operating system whose graphical interface is optimized for self-hosting. All other operating systems (Mac, Windows, iOS, Android, and all Linux distros) have graphical interfaces optimized for running client applications. Running servers and nodes requires "popping the hood", using the command line, and performing the complex tasks of a system's administrator. For this reason, self-hosting has been practically off limits to the vast majorty of the population.

Packaging a service for StartOS means it can be discovered, downloaded, installed, configured, and run by anyone possessing basic computer skills, no command line necessary.

StartOS v0.4.0 introduces a totally revamped packaging SDK as well as incredible new StartOS APIs for service networking.

GitHub Repo: 

https://github.com/Start9Labs/embassy-os

# Project Details
The packaging workshop will be lead by Matt Hill from Start9.

**Comment by MattDHill** [comment]
I think it would depend on interest. I would do a 2 hour workshop explaining how packaging is done, or I could do a two-day builder project where people actually package their favorite Bitcoin/Lightning services for StartOS.

**Comment by iglesiasbrandon** [comment]
Hey @MattDHill congratulations, this issue has been accepted for TABConf 2023. It has been added to the official GitHub Project schedule. The builder Days tables will be on all day on September 6th and 7th.

**Comment by MattDHill** [comment]
Amazing, can't wait!

**Comment by jordan-bravo** [comment]
Looking forward to this.  I would love to learn how to package Whirlpool/Dojo for StartOS.

**Comment by MattDHill** [comment]
Hey @iglesiasbrandon any chance I can get this for the 7th?

**Comment by MattDHill** [comment]
Sorry just saw this. I'm fine with whatever. What is the difference between the two?

**Comment by MattDHill** [comment]
Let's do a workshop. 120 mins is perfect.

**Comment by iglesiasbrandon** [comment]
updated!

**Comment by iglesiasbrandon** [comment]
Hey @MattDHill  , We have added a day, time slot, and length to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/4

Please acknowledge by commenting 'ack'.

This will confirm your workshop for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by MattDHill** [comment]
Ack

**Comment by miketwenty1** [comment]
@MattDHill 

We are about a week away from the start of the conference. I'm sending this to all accepted upcoming workshop. Please review and ensure you have a clear, up to date, high level, agenda on this GitHub issue. Please buffer in time to help with unexpected problems and questions.

TABConf workshops should aim to involve high levels participation. If you're planning to conduct a live demo, please consider that attendees will require clear instructions on how to prepare for following along, (all steps for setup should be double checked) and any presentation should be structured accordingly.
Participants should leave the workshop either with something built, (be it physical or digital), or with specific knowledge gained from the __hands on/interactive__ experience.

**Comment by iglesiasbrandon** [comment]
Hey @MattDHill , I am closing this issue since you have completed the workshop. Thank you for all of the effort you put into it!
