### ISSUE TITLE
How to set up a friends/family multisig wallet

### ISSUE THREAD

**Issue by MattDHill** [TABConf/2023.tabconf.com#64]
# Description
Multisig can be intimidating. I think it would be nice to have a workshop demonstrating a step-by-step process for setting up a secure, offline, multisig wallet with a couple trusted friends and family.

## Exploring the Power of Multisig Wallets

Understanding Multisig Wallets

- Definition and basic concept of multisig wallets
- Definition and explanation of multisig (multisignature) technology
- How multisig wallets differ from traditional single-signature wallets
- Advantages and benefits of using multisig wallets for crypto asset management
- Overview of the technical principles behind multisig wallets

Enhanced Security Features

- Discussing the enhanced security provided by multisig wallets
- Protection against single points of failure and reducing the risk of hacks or human errors
- Recovery mechanisms in case of lost keys or compromised devices

Use Cases for Multisig Wallets

- Illustrating real-world examples of where multisig wallets are commonly used

Demonstrating the multisig wallet setup

- Setting up a multisig wallet with step-by-step understanding

# About the Speaker
@mshankarrao 

# Workshop Details
~1 hours

**Comment by MattDHill** [comment]
This would be a speakers wanted label.

**Comment by mshankarrao** [comment]
Are you still looking for the speaker to demonstrate this one? Also are you looking for any specific multisig or the electrum wallet should work?

**Comment by iglesiasbrandon** [comment]
yea, we are still looking for speakers for this topic! is this something you would be interested in doing @mshankarrao ?

**Comment by mshankarrao** [comment]
> yea, we are still looking for speakers for this topic! is this something you would be interested in doing @mshankarrao ?

Yes for sure

**Comment by iglesiasbrandon** [comment]
> > yea, we are still looking for speakers for this topic! is this something you would be interested in doing @mshankarrao ?
> 
> For sure

ok great! im going to assign you to this workshop. Please feel free to update the description (first comment) on the issue with exactly what you are planning on covering.

**Comment by mshankarrao** [comment]
> > > yea, we are still looking for speakers for this topic! is this something you would be interested in doing @mshankarrao ?
> > 
> > 
> > For sure
> 
> ok great! im going to assign you to this workshop. Please feel free to update the description (first comment) on the issue with exactly what you are planning on covering.

Exploring the Power of Multisig Wallets

1. Understanding Multisig Wallets
   - Definition and basic concept of multisig wallets
   - Definition and explanation of multisig (multisignature) technology
   - How multisig wallets differ from traditional single-signature wallets
   - Advantages and benefits of using multisig wallets for crypto asset management
   - Overview of the technical principles behind multisig wallets

2. Enhanced Security Features
   - Discussing the enhanced security provided by multisig wallets
   - Protection against single points of failure and reducing the risk of hacks or human errors
   - Recovery mechanisms in case of lost keys or compromised devices

3. Use Cases for Multisig Wallets
   - Illustrating real-world examples of where multisig wallets are commonly used
   - Managing funds for cryptocurrency exchanges, ICOs, and token sales
   - Escrow services, decentralized finance (DeFi) platforms, and governance mechanisms

4. Demonstrating the multisig wallet setup
   - Setting up a multisig wallet with clear steps

**Comment by iglesiasbrandon** [comment]
@mshankarrao issue description has been updated! let me know if you want me to update the title to "Exploring the Power of Multisig Wallets"

**Comment by iglesiasbrandon** [comment]
Hey @mshankarrao congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The workshops will be happening on September 6th and 7th; once we accept some more, we will assign the day, time, and location.

**Comment by iglesiasbrandon** [comment]
Hey @mshankarrao , We have added a day, time slot, and length to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/4

Please acknowledge by commenting 'ack'.

This will confirm your workshop for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by mshankarrao** [comment]
Ack

**Comment by miketwenty1** [comment]
@mshankarrao 

We are about a week away from the start of the conference. I'm sending this to all accepted upcoming workshop. Please review and ensure you have a clear, up to date, high level, agenda on this GitHub issue. Please buffer in time to help with unexpected problems and questions.

TABConf workshops should aim to involve high levels participation. If you're planning to conduct a live demo, please consider that attendees will require clear instructions on how to prepare for following along, (all steps for setup should be double checked) and any presentation should be structured accordingly.
Participants should leave the workshop either with something built, (be it physical or digital), or with specific knowledge gained from the __hands on/interactive__ experience.

**Comment by mshankarrao** [comment]
> @mshankarrao
> 
> We are about a week away from the start of the conference. I'm sending this to all accepted upcoming workshop. Please review and ensure you have a clear, up to date, high level, agenda on this GitHub issue. Please buffer in time to help with unexpected problems and questions.
> 
> TABConf workshops should aim to involve high levels participation. If you're planning to conduct a live demo, please consider that attendees will require clear instructions on how to prepare for following along, (all steps for setup should be double checked) and any presentation should be structured accordingly. Participants should leave the workshop either with something built, (be it physical or digital), or with specific knowledge gained from the **hands on/interactive** experience.

Yeah sure, i am working on the pitch deck and planning to show a demo of how we can setup multisig wallet. Will show them some transactions in the testnet on Electrum wallet. Also will see if i can get any volunteer from the audience to show and make the demo more interactive.

**Comment by iglesiasbrandon** [comment]
Hey @mshankarrao, I am closing this issue since you have completed the workshop. Thank you for all of the effort you put into it!
