### ISSUE TITLE
BitDevs Socratic Village

### ISSUE THREAD

**Issue by CardCoins** [TABConf/2023.tabconf.com#66]
# Description 
The Socratic Village is based on the concept of a Socratic Seminar/Circle, a collaborative dialogue that is facilitated by participants examining a subject or text and articulating their questions and viewpoints. The group setting helps participants construct meaning through analysis, interpretation, listening and active engagement in conversation.

Content in the Socratic Village will primarily be a combination of Socratic Sessions with general themes and topic-specific Socratic Panels. The Socratic Sessions will be a condensed version of a Socratic-style meetup. A discussion leader will curate some content based on a general theme and come prepared to give background on the material and provide discussion questions for the group.

The Socratic Panels will be driven by a small group of experts on a specific subject matter. The panelists will first give a 5-10 minute presentation on the topic, after which the panelists should expect to field questions from the community as well as have their own questions to stimulate discussion. The crowd can both ask and answer any questions. A moderator will come prepared with additional questions to stimulate discussion.

# Project Details
This is a village run and hosted by BitDevs communities spanning multiple cities.

# Organizers:
- @btsea (BitDevs NYC)
- @vnprc (Triangle BitDevs)
- @MiamiBitDevs
- @m1sterc001guy (BitDevs MPLS)

**Comment by iglesiasbrandon** [comment]
Sounds awesome; thanks @CardCoins!

**Comment by iglesiasbrandon** [comment]
Hey @CardCoins congratulations, this Village has been accepted for TABConf 2023!

We will work with the BitDevs Socratic village leaders to get the programming for the village into GitHub and onto the official project schedule. 

The Villages will be happening on September 8th and 9th.

**Comment by vnprc** [comment]
Should we open issues for socratic seminars or will that be handled internally within the village?

**Comment by btsea** [comment]
Great question @vnprc! Bump for @iglesiasbrandon.

**Comment by iglesiasbrandon** [comment]
Hey @vnprc @btsea, you should open issues on this repo for the Socratic seminars, and I will work with the village leaders to accept them or give them access to do it without me. We will be using the same Github project for all of the issues, but the Github project will have different views for each of the villages.

**Comment by vnprc** [comment]
Great! We will work on rounding up some volunteers, figuring out what kind of events we want to hold and create issues in this repo for them.

**Comment by iglesiasbrandon** [comment]
im going to close this issue since the village was accepted!
