### ISSUE TITLE
Bitcoin - The Future of Money

### ISSUE THREAD

**Issue by libbie1** [TABConf/2023.tabconf.com#67]
# Description
### What is this talk about? Give us as many details as possible. 
Bitcoin - The Future of Money
### What would an attendee learn from this talk?
About Ownership, Bitcoin as an Investment, Bitcoin Challenging Today’s Custodial Financial System, The Importance of Self-Custody and more.
### Is there anything folks should read up on before they attend this talk?
No.
### Relevant Links
www.ballet.com

# About the Speaker
### Social Links
Github 
Twitter 
@bobbyclee
Website
bobbylee.com

# Talk Details
### Length of Talk 
30 minutes
### Preferred Day/Time Slot 
September 6 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment]
Hey @libbie1 As we get closer to the conference, we will review all the issues, and the chosen ones will be added to the TABConf 2023 schedule.

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks questions. Also, please feel free to update the issue description if you'd like to add anything else as we get closer to the event.

**Comment by miketwenty1** [comment]
@libbie1 it seems this submission failed to get accepted this year, I appreciate the submission. One of our big criteria for accepting talks is reputation and community involvement around a topic. We also sort and order issues by 👍 emojis as one way to help understand how many people are excited to see a various talk/panel/workshop. Please consider submitting another idea next year. We'll be accepting talks for TABConf 6 in about 5-6 months.
