### ISSUE TITLE
How to Manage an effective Lightning Node 

### ISSUE THREAD

**Issue by beeforbacon** [TABConf/2023.tabconf.com#68]
**Description**
I would like to give a presentation/talk on how to manage a Bitcoin Lightning Node effectively and easily for new and existing node runners. I want this to be an implementation agnostic presentation so those running either LND, CLN, or others can get something out of it. I have been operating and managing LN routing nodes for 4 years and would like to share my experience and what I have learned.

**What would an attendee learn from this talk?**
1. A fast what/how/why of lightning nodes
2. Allocating initial capital strategies and considerations
3. How to choose peers and channel sizes
4. Go over inbound liquidity strategies for initial bootstrap
5. General fee rate strategies
6. General balance strategies
7. How to Grow after initial bootstrap
8. Tools that are useful

**About the Speaker**
Nate
Support Engineer at [Voltage](https://voltage.cloud)
Twitter: https://twitter.com/beeforbacon1

**Talk Details**
Length of Talk
60 Minutes preferred but could consolidate and do 30 if that was all that was available. 

**Preferred Day/Time Slot**
Any

**Comment by iglesiasbrandon** [comment]
Hey @beeforbacon, thank you for submitting an issue for TABConf 2023! We will review all the issues as we get closer to the conference.

I don't expect us to add any issues to the schedule until two months before the conference but keep an eye on this in case someone asks questions. Also, please feel free to update the issue description if you'd like to add anything else as we get closer to the event.

**Comment by beeforbacon** [comment]
> Hey @beeforbacon, thank you for submitting an issue for TABConf 2023! We will review all the issues as we get closer to the conference.
> 
> I don't expect us to add any issues to the schedule until two months before the conference but keep an eye on this in case someone asks questions. Also, please feel free to update the issue description if you'd like to add anything else as we get closer to the event.

Sounds good. Thanks.

**Comment by iglesiasbrandon** [comment]
Hey @beeforbacon, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The talks on the main stage will be happening on September 8th and 9th; once we accept more, we will assign the day, time, and location.

**Comment by iglesiasbrandon** [comment]
Hey @beeforbacon , We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by beeforbacon** [comment]
ack

**Comment by iglesiasbrandon** [comment]
Hey @beeforbacon , I am closing this issue since it's completed. Thank you for all of the effort you put into it!
