### ISSUE TITLE
Applying Arvin Khamseh on to TABConf 2023

### ISSUE THREAD

**Issue by MileNFT** [TABConf/2023.tabconf.com#69]
I just heard about the upcoming TABConf 2023 in Atlanta, with the Web3 and digital marketplace component, and had to reach out to you about incredible speaker ARVIN KHAMSEH- I know your audience will be as thrilled as others who have encountered him will be -Now based in Dubai Arvin has been's in the middle of a world speaking tour at major events across the globe speaking to NFT and crypto enthusiasts, government leaders, and other stakeholders - and would be a wonderful addition to your speakers' list. I can promise that he's one that attendees will be speaking about long after the show - he's not there to pitch any projects - he is - and he literally fills the room. Let me know if we can arrange a call after you review the details below...Arvin's Bio and links to him speaking on stage: Arvin the host of the Soldout Secret Show and founder of Soldout NFTs. Since successfully selling out an Italian artist collection in 2021, Arvin has raised 30M+ from retail investors. Some notes about his company:

* Several sold-out collections in the bear market with a cost per sale to you of NFT around $13+
* ROI generated inside web3 marketing: 11-48X
* Success rate inside web3 marketing: 81%
* Currently working with a large entertainment enterprise you'd know
* Head of NFT track at AIBC/Sigma Web 3 event
* Organizer of Upwork official web3 community
* Web 3 Speaker at Google and Stanford
* Contributor to Forbes Council, Cointelegraph & Rolling stone circle

These videos give you some idea: VIDEO SHOWING ARVIN FILLING THE ROOMS AT EVENTS AROUND THE WORLD:
https://www.linkedin.com/posts/arvinkhamseh_nft-nftmarketing-activity-6949577739611856896-5gh2/?utm_source=linkedin_share&utm_medium=ios_app

MORE RECENT FOOTAGE OF ARVIN SPEAKING ON STAGE:
https://www.youtube.com/shorts/CmMpjlRx1cI
https://www.youtube.com/watch?v=8OZjCi9XXTw 

Also, I would like to ask if there is an opportunity to discuss Arvin attending some of your future events as a speaker.

Sincerely,

Milenko Rebic
Project Manager
[www.soldoutnfts.io](http://www.soldoutnfts.io/)
[pm@soldoutnfts.io](mailto:pm@soldoutnfts.io)

**Comment by briimhd** [comment]
Sorry, this is a bitcoin-only conference. "NFTs" are not relevant as a topic of discussion at TABConf. I will be closing this issue.
