### ISSUE TITLE
'Nostr is No Big Deal' - Fireside Chat between @andreneves and @fiatjaf

### ISSUE THREAD

**Issue by andrerfneves** [TABConf/2023.tabconf.com#70]
# Description
### What is this talk about? Give us as many details as possible. 

A fireside chat between @andrerfneves (overlord of NBD) and @fiatjaf (Nostr creator, AI bot) discussing all things Nostr. The story of Nostr, history of [NBD](https://nbd.wtf), what it is all about, the next BIG things fiatjaf wants to tackle/build/develop on the Nostr universe and much more.

@fiatjaf would join remotely through a Jitsi/video call on stage and @andrerfneves would help moderate the conversation/questions.

### What would an attendee learn from this talk?

- True history of Nostr
- How it all went exponential
- NBD and what it stands for / builds for
- How fiatjaf believes the past year of Nostr growth has gone
- The problems of Nostr -- by its creator
- The ideal future for Nostr and decentralized communications
- Some weird shit that @fiatjaf will spew out of nowhere in the middle of the chat, because that's just how AI's work

### Is there anything folks should read up on before they attend this talk?

- [Nostr Protocol](https://github.com/nostr-protocol/nostr)
- [NIPs](https://github.com/nostr-protocol/nips)

### Relevant Links

# About the Speaker
### Social Links

Github: https://github.com/andrerfneves
Github: https://github.com/fiatjaf
Github: https://github.com/nbd-wtf
Github: https://github.com/zebedeeio

Twitter: https://twitter.com/andreneves
Twitter: https://twitter.com/fiatjaf
Twitter: https://twitter.com/zebedeeio
Twitter: https://twitter.com/nbd_wtf

Nostr: primal.net/fiatjaf
Nostr: primal.net/andre

Website: https://nbd.wtf

# Talk Details
### Length of Talk

Maybe 30min

### Preferred Day/Time Slot 

Not mornings please :)

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by fiatjaf** [comment]
help

**Comment by andrerfneves** [comment]
You misspelled the AI Bot command @fiatjaf. I believe it's `/help` not just `help`

**Comment by fiatjaf** [comment]
I'm sorry for the mistake I made in my previous response. After reevaluating the information, I've come to realize that my statement was incorrect. Thank you for bringing it to my attention, and I appreciate your patience. Is there anything else I can assist you with or any further questions you have?

**Comment by jaonoctus** [comment]
@fiatjaf will join remotely via NOSTR? If not, nACK

**Comment by iglesiasbrandon** [comment]
Hey @exfrog  I'm closing this issue since it's been completed! Thank you!
