### ISSUE TITLE
SeedSigner Builder Day Table

### ISSUE THREAD

**Issue by SeedSigner** [TABConf/2023.tabconf.com#71]
# Description
### What is this project about? Please give us as many details as possible.
SeedSigner is a bitcoin signing device that users can build themselves from commonly available electronic components. The signer is stateless and air-gapped, and allows users to 1) create private keys from real world entropy 2) generate extended public keys for initial wallet setup, and 3) securely sign transactions using an animated QR code exchange process
### Is it a FOSS or Open Source project?
The necessary components and instructions to build a SeedSigner are publicly available; the software to operate a SeedSigner is FOSS (MIT), and several 3D-printable enclosure models are also FOSS (MIT).
### What would an attendee learn from visiting this project's table at Builder Days?
Attendees would learn to build and operate one of our signing devices.
### Is there anything people should read up on before finding the table at Builder Day?
More info on the project is available from our website: https://seedsigner.com
### Relevant Links
GitHub Repo: https://github.com/SeedSigner/seedsigner

# Project Details
### Who will run the table? Are those people current contributors or maintainers who can answer questions and get people onboarded?
Myself, our lead maintainer Nick Klockenga, & our lead developer Keith Mukai would run the table.

**Comment by iglesiasbrandon** [comment]
Hey @SeedSigner, congratulations, this issue has been accepted for TABConf 2023. It has been added to the official GitHub Project schedule. The builder Days tables will be on all day on September 6th and 7th
