### ISSUE TITLE
Lunch and Learn: bitcoin-cli beginners workshop

### ISSUE THREAD

**Issue by miketwenty1** [TABConf/2023.tabconf.com#72]
# SETUP steps, You can do this before attending:
- Download Bitcoin core. https://bitcoincore.org/en/download/. (Make sure you download the right binary for your computer)
- Do **NOT** run this with the default settings unless you know what you're doing (we will configure this together). We'll also go over how to check the integrity of the download tarball.
- Follow along [gist guide](https://gist.github.com/miketwenty1/cd0a9b0fb4aca149e87c1875cf93a812#file-workshop-txt) (in case you get totally lost)

# Description
### What is this workshop about? Provide as many details as possible. 

This workshop will help people get familiar with Bitcoin-cli. We will primarily be using Regtest, however it will be possible to take this information to mainnet, testnet, signets, etc. Multiple concepts will be discussed to give people a deeper understanding of how bitcoin works.

### What would an attendee learn from this workshop?

- Setup and configure our environment for regtest. 
- Verify their bitcoin core software.
- Configure and reference `bitcoin.conf` file.
- Primary functions in and around the `bitcoin-cli` or Bitcoin-Qt that ships with bitcoincore.
- We will create multiple wallets, send and receive from these wallets.
- We will mine fake regtest blocks with alice.
- High level review of labels using bob.
- Goal will be to send a psbt to carol from bob.

More competent attendees will be asked to assist their struggling neighbors.

### RPC Commands that will be covered:
- createwallet 
- unloadwallet
- loadwallet
- listwallets
- getnewaddress 
- generatetoaddress 
- listunspent
- getbalance
- getbalances
- getblockchaininfo
- listlabels
- sendtoaddress
- listtransactions
- walletcreatefundedpsbt
- decodepsbt
- walletprocesspsbt
- analyzepsbt
- finalizepsbt
- decoderawtransaction 
- sendrawtransaction

### Is there anything attendees should read up on before they attend this talk?

- https://bitcoincore.org/en/doc/24.0.0/rpc/ or latest stable docs will be used as a guide.

### Relevant Links
- https://bitcoincore.org.
- https://bitcoincore.org/en/doc/24.0.0/rpc/

# About the Speaker
### Social Links
Github - https://github.com/miketwenty1
Twitter - https://twitter.com/miketwenty1

# Workshop Details
### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment]
Hey @miketwenty1, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The workshops will be happening on September 6th and 7th; once we accept some more, we will assign the day, time, and location.

**Comment by iglesiasbrandon** [comment]
Hey @miketwenty1 , We have added a day, time slot, and length to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/4

Please acknowledge by commenting 'ack'.

This will confirm your workshop for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by iglesiasbrandon** [comment]
bump @miketwenty1 can you ack

**Comment by miketwenty1** [comment]
ACK

**Comment by iglesiasbrandon** [comment]
Hey @miketwenty1, I am closing this issue since you have completed the workshop. Thank you for all of the effort you put into it!
