### ISSUE TITLE
Bitcoin Chain Maximalism vs. Bitcoin Monetary Maximalism

### ISSUE THREAD

**Issue by allenpiscitello** [TABConf/2023.tabconf.com#73]
# Description

Bitcoin maximalism is a widely used term but poorly defined. Some argue that Bitcoin maximalism is the idea that all of crypto will migrate to the Bitcoin blockchain. I will take on the opposite viewpoint that the Bitcoin asset is the key innovation and will spread to all possible implementations of holding the asset, including sidechains, alt-chains, databases, or even legal constructs. I will discuss the two conflicting viewpoints and how they affect the debate on recent events such as Ordinals, Inscriptions, and DeFi.

(open to making this a panel with opposing viewpoints)

# About the Speaker
Allen Piscitello is a Senior Staff Software Engineer at Synota, a company using Bitcoin to improve inefficiencies in the energy industry. Allen is a 12+ year Bitcoiner who has lived through and participated in many of the previous debates that have defined Bitcoin as it is today. Previous to working at Synota, Allen was the Director of Research Integrations and Vice President of Product Management at Blockstream .

# Talk Details
### Length of Talk
30 minutes

**Comment by iglesiasbrandon** [comment]
Hey @allenpiscitello, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The talks on the main stage will be happening on September 8th and 9th; once we accept more, we will assign the day, time, and location.

**Comment by iglesiasbrandon** [comment]
Hey @allenpiscitello , We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by allenpiscitello** [comment]
Ack

**Comment by iglesiasbrandon** [comment]
hey @allenpiscitello , closing this issue since this has been completed, thank you!
