### ISSUE TITLE
Fedimint 1.0 and Fedi-Mods Workshop

### ISSUE THREAD

**Issue by Kodylow** [TABConf/2023.tabconf.com#74]
# Description
### What is this workshop about? Provide as many details as possible. 
How to build Fedi-mods: webLN enabled apps that leverage the Fedi user's Fedimint module resources.

Workshop format will be a Replit based tutorial on how to build out a WebLN enabled LLM chatbot application using L402s/LNURL and load it into Fedi. After setting up the lightning side, remainder of the workshop will involve tying in the application to services offered by a user's Fedimint modules.

### What would an attendee learn from this workshop?

Lightning development, how to build with Fedi and Fedimint. Attendee will walk away with a working lightning application that works in Fedi that they built.

### Is there anything attendees should read up on before they attend this talk?

No, self contained workshop.

### Is there anything attendees should set up before the workshop?

No, will be using Replit so all setup can be configured before they fork the Repl by me.

### Relevant Links

https://fedi.xyz/builders

# About the Speaker
Kody Low is a developer and Head of Developer & Product Support at Fedi.

### Social Links
Github: https://GitHub.com/kodylow
Twitter: @kodylow

# Workshop Details

1 or 2 hour workshop, can flex and just have more/less of the starter code already done beforehand, would prefer 2 hours though.

### Preferred Day/Time Slot
Whatever works best for you.

**Comment by Kodylow** [comment]
@miketwenty1

**Comment by iglesiasbrandon** [comment]
Hey @Kodylow congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The workshops will be happening on September 6th and 7th; once we accept some more, we will assign the day, time, and location.

**Comment by iglesiasbrandon** [comment]
Hey @Kodylow , We have added a day, time slot, and length to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/4

Please acknowledge by commenting 'ack'.

This will confirm your workshop for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by miketwenty1** [comment]
@Kodylow we need an ACK here please.


We are about a week away from the start of the conference. I'm sending this to all accepted upcoming workshop. Please review and ensure you have a clear, up to date, high level, agenda on this GitHub issue. Please buffer in time to help with unexpected problems and questions.

TABConf workshops should aim to involve high levels participation. If you're planning to conduct a live demo, please consider that attendees will require clear instructions on how to prepare for following along, (all steps for setup should be double checked) and any presentation should be structured accordingly.
Participants should leave the workshop either with something built, (be it physical or digital), or with specific knowledge gained from the __hands on/interactive__ experience.

**Comment by iglesiasbrandon** [comment]
Hey @Kodylow , I am closing this issue since you have completed the workshop. Thank you for all of the effort you put into it!
