### ISSUE TITLE
A 2024 Playbook For Building A Self-Custody Lightning Wallet

### ISSUE THREAD

**Issue by jurvis** [TABConf/2023.tabconf.com#75]
# Description
### What is this talk about? Give us as many details as possible. 
In my talk, I will present the challenges mobile engineers typically encounter when trying to implement a self-custody Lightning wallet and the tools that have emerged through the Lightning Development Kit (LDK) project over the last couple of years that has helped address them.

Additionally, I will present a framework I use to think about the different dimensions required to build a full-featured, easy-to-use self-custody Lightning wallet: Liquidity, Payment Reliability, Key Management, and Backups and Restoration.

Using this framework, we will examine what is coming up in 2024 to continue to push the possibilities of bringing great Lightning user experiences to mobile self-custody wallets.
### What would an attendee learn from this talk?
An attendee would be able to identify the technical and product considerations they must pay attention to when building a self-custody Lightning wallet and familiarize themselves with the various solutions coming down the pipeline and their trade-offs.

Then, we will attempt to provide the "formula" for building a mobile self-custody Lightning wallet in 2024.

### Is there anything folks should read up on before they attend this talk?
None!

### Relevant Links
- [Lightning Development Kit](https://lightningdevkit.org/)
- [ldk-swift](https://github.com/lightningdevkit/ldk-swift)
- [ldk-garbagecollected](https://github.com/lightningdevkit/ldk-garbagecollected)
- [rapid-gossip-sync-server](https://github.com/lightningdevkit/rapid-gossip-sync-server)
- [ldk-node](https://github.com/lightningdevkit/ldk-node)
- [vss-server](https://github.com/lightningdevkit/vss-server)

# About the Speaker
Jurvis is a contributor to the Lightning Development Kit (LDK) project and works at Block to bring Lightning to its self-custody bitcoin wallet, [Bitkey](https://wallet.build/). 

### Social Links
[GitHub](https://github.com/jurvis/) 
[Twitter](https://twitter.com/jurvistan/)

# Talk Details
### Length of Talk
30-45 minutes
### Preferred Day/Time Slot 
Thursday late morning.

**Comment by iglesiasbrandon** [comment]
Hey @jurvis, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The talks on the main stage will be happening on September 8th and 9th; once we accept more, we will assign the day, time, and location.

**Comment by iglesiasbrandon** [comment]
Hey @jurvis , We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by jurvis** [comment]
ack

**Comment by iglesiasbrandon** [comment]
Closing this issue because this item has been completed! Thank you!
