### ISSUE TITLE
NextGen Village

### ISSUE THREAD

**Issue by EllyPembroke** [TABConf/2023.tabconf.com#76]
## Description

NextGen Village is a fun interactive space for bitcoiners of all ages. Meet other bitcoiner families and learn more about how bitcoin works with games, crafts, puzzles and our NextGen panels. Come and go any time. It takes a village to raise the next generation of sovereign individuals! 

## Activities

*Design your own buttons
*Assemble 3D puzzles of "bitcoin blocks" out of a "mempool" of "transactions"
*Learn how to play the board game "HODL up" 
*Play the card game "SHAmory" and bring home some books for the youngest bitcoiners
*Interactive projection art - paint with VR
*Learn how to design and print your own 3D models

## Community call

Are you bringing your kids? Do you have ideas for activities, games, panels or talks? Submit your ideas!

**Comment by iglesiasbrandon** [comment]
Hey @EllyPembroke, congratulations, this Village has been accepted for TABConf 2023!

We will work with you and the village leaders to get the programming for the village into GitHub and onto the official project schedule.

The Villages will be happening on September 8th and 9th.

**Comment by Bitc0indad** [comment]
Congrats @EllyPembroke!
