### ISSUE TITLE
The Scaling Lightning Initiative - A Testing Toolkit for the Lightning Network

### ISSUE THREAD

**Issue by ohenrik** [TABConf/2023.tabconf.com#77]
# Description
### What is this talk about?
This talk is about the Scaling Lightning Initiative.

The Scaling Lightning initiative aims to build a testing toolkit for the Lightning Network protocol, its implementations, and applications that depend on the Lightning Network.

Currently, there are unknowns and untested assumptions about how the Lightning Network and its applications will react to shocks in transaction volume, channels, nodes, gossip messages, etc.

Having a set of tools and a signet Lightning Network will help:
* Developers test their applications.
* Researchers verify their assumptions.
* Operators test their infrastructure.
* Novices learn how the Lightning Network and various applications work in a somewhat realistic environment without risking real coins.

The goal is to collaborate as an industry to help scale the Lightning Network and the applications that depend on it.

We are continually defining the project through Issues in the github repo and work has started:
https://github.com/scaling-lightning/scaling-lightning/issues

**Yes, I know about Polar.** While Polar is an excellent project it is fundamentally different from what we want to achieve with the Scaling Lightning initiative. Polar is a desktop application meant to manually build a network through a drag and drop interface, which is great for novices and simple projects. However, it's not something that is suitable for a developer or testing environment at a startup or as a researcher. We have discussed and considered using parts of Polar or altering Polar, but it's not the right direction to go for SL.

### What would an attendee learn from this talk?
It's essential that we work together on shared protocols and tools that help lift the entire Lightning industry. This talk is about why we as an industry should collaborate on building a testing toolkit and how the toolkit works. 

### Is there anything folks should read up on before they attend this talk?
No reading or preparation necessary.

### Relevant Links
https://github.com/scaling-lightning/scaling-lightning
https://twitter.com/ohskogstrom/status/1663394819954348033
https://twitter.com/ScalingLN

# About the Speaker
I'm the founder of LN_Capital and have been in the lightning industry since January 2019. Over the last 5 years I have seen tremendous growth and evolution in the network. I'm passionate about the lightning industry and through LN Capital's Twitter account I try to share and give back to the community by posting threads about various topics in the Lightning industry.

I'm also the founder of the Scaling Lightning initiative (open source project).  Ex-CTO and founding team member at Arcario / K33Research.

### Social Links
Github: https://github.com/ohenrik
Twitter: https://twitter.com/ohskogstrom
Website: https://ln.capital
Telegram: https://t.me/+AytRsS0QKH5mMzM8

# Talk Details
### Length of Talk: 
30 minutes

### Preferred Day/Time Slot 
9am - 11am or 1pm - 3pm

**Comment by ohenrik** [comment]
**NB:** this can also be a made into a workshop demoing the testing framework.

**Comment by iglesiasbrandon** [comment]
Hey @ohenrik, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The talks on the main stage will be happening on September 8th and 9th; once we accept more, we will assign the day, time, and location.

**Comment by iglesiasbrandon** [comment]
Hey @ohenrik , We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by ohenrik** [comment]
Ack

**Comment by ohenrik** [comment]
@iglesiasbrandon My presentation is in Keynote, is that ok or do I need to convert it to PowerPoint?

**Comment by iglesiasbrandon** [comment]
you should bring you laptop and just plug it in directly @ohenrik

**Comment by ohenrik** [comment]
Perfect :)

**Comment by iglesiasbrandon** [comment]
Hey @ohenrik , closing this issue since this has been completed, thank you!

**Comment by ohenrik** [comment]
Thank you @iglesiasbrandon , it was a pleasure speaking at TabConf!
