### ISSUE TITLE
A Philosophy of Mempool Policy 

### ISSUE THREAD

**Issue by instagibbs** [TABConf/2023.tabconf.com#79]
Mempool policy, like transaction standardness policy, is one of the most misunderstood parts of the Bitcoin network. Is it censorship? Is it paternalism? Is it necessary? 

This talk would essentially be a a higher level meta discussion of  https://gist.github.com/instagibbs/ee32be0126ec132213205b25b80fb3e8

I will frame one way how we can look at the goals of mempool policy within these tensions between anti-DoS and wallet/user intentions. What success might look like, and what failure might look like. This touches on (sigh)fullrbf, mempool.space's transaction accelerator, Bitcoin smart contracting, future potential softforks such as BIP118 and SIGHASH_GROUP, and the Lightning Network today.

**Comment by iglesiasbrandon** [comment]
hey @instagibbs how long would this talk be?

**Comment by miketwenty1** [comment]
closing due to #102

**Comment by instagibbs** [comment]
Sorry can't make it this year anyways, gave murch the go-ahead to take it

**Comment by EllyPembroke** [comment]
@instagibbs we'll miss you!
