### ISSUE TITLE
Distributed Charge - GRID live demo

### ISSUE THREAD

**Issue by AndySchroder** [TABConf/2023.tabconf.com#82]
Show a Distributed Charge - GRID live demo in the NextGen village similar to the setup shown here: http://andyschroder.com/DistributedCharge/news/2023.01.17-BitcoinPark/ .

More information about the payment workflow is shown here: http://andyschroder.com/DistributedCharge/GRID/Overview/ .

**Comment by EllyPembroke** [comment]
@iglesiasbrandon This looks great! We would like to accept it.

**Comment by iglesiasbrandon** [comment]
Hey @EllyPembroke @AndySchroder this issue has been accepted for the NextGen village.

**Comment by AndySchroder** [comment]
Does anyone have any special or fun electrical loads they'd like to connect to this?

**Comment by AndySchroder** [comment]
Will the facility be providing me a table to place this on?
