### ISSUE TITLE
Distributed Charge - BIKE

### ISSUE THREAD

**Issue by AndySchroder** [TABConf/2023.tabconf.com#83]
I've proposed https://github.com/TABConf/2023.tabconf.com/issues/81 and https://github.com/TABConf/2023.tabconf.com/issues/82 for the NextGen village. These setups are very advanced but they aren't super interactive. In addition to these setups, or instead of these setups, I propose another implementation called BIKE. BIKE will be an exercise bike that has an integrated generator. Attendees can ride this stationary bike for a while convert some of the chemical energy in their body to mechanical and then electrical energy. Once they are done they can then receive a payment for the energy using either LNURL or BOLT12 (if it's mature by then). This implementation will have no industrial use, it's only a fun toy for TABConf to see just how hard it is for humans to competitively produce electrical energy at current market rates.

**Comment by EllyPembroke** [comment]
@iglesiasbrandon Especially excited about this one. We would like to accept it.

**Comment by iglesiasbrandon** [comment]
Hey @EllyPembroke @AndySchroder this issue has been accepted for the NextGen Village.

**Comment by TKChattoraj** [comment]
I would love to see these at TABConf.  These are actual working hardware.  While others talk about things in the energy space, Andy has actual working hardware.

**Comment by AndySchroder** [comment]
So, I can show the output of this on a TV or a small screen built into the unit. Will you have any TV's in the event space that I can place it nearby to show on a larger screen?

**Comment by AndySchroder** [comment]
Any information on the size of the room this will be placed in? Just trying to understand if it will be in a corner of a room where lectures will be presented, or a hangout area?

What time of day will I set up and teardown?

**Comment by AndySchroder** [comment]
What does the tag "SM" mean?

**Comment by EllyPembroke** [comment]
NextGen village is mostly a hangout space with a few lectures. I'll be happy to address practical setup questions in an email or zoom call
