### ISSUE TITLE
Turning real things on with the raspi CM4, Board A0, and LND

### ISSUE THREAD

**Issue by AndySchroder** [TABConf/2023.tabconf.com#84]
# Description
### What is this workshop about? Provide as many details as possible. 

This workshop is about turning on electrical switches when a payment is made using the bitcoin lightning network. These switches could be used to operate a soda or candy machine, a laundry machine, a parking garage gate, a car wash, a turnstile in a subway, a pool table, etc..

### What would an attendee learn from this workshop?
- How to setup remote access to the device in the field using [StaticWire](https://github.com/AndySchroder/StaticWire).
- How to interact with the GPIO on a raspberry pi using python.
- Simple electrical circuit wiring and why [Board A0](http://andyschroder.com/DistributedCharge/BoardA0/Overview/) is needed to handle real electrical loads with the raspberry pi.
- LND grpc interface using python.
    - Requirements to establish connectivity.
    - How to create invoices.
    - How to continuously monitor invoices for payment using streaming grpc calls.
- How to make a raspberry pi operate in a kiosk mode.

### Is there anything attendees should read up on before they attend this talk?
- Attendees should be familiar with python, ssh, and the linux command line.

### Is there anything attendees should set up before the workshop?
- Have a LND node they can connect to remotely using GRPC.
- A lightning wallet on their phone.
- They'll need an ssh public key ready to share so that I can give them access to one of the demo raspberry pi computers.
- A laptop with ssh an sftp.

### Relevant Links

- http://andyschroder.com/BitcoinFluidDispenser/TheOriginal/
- http://andyschroder.com/BitcoinFluidDispenser/2.3/
- http://andyschroder.com/DistributedCharge/alpha/InitialDemonstration/
- http://andyschroder.com/DistributedCharge/BoardA0/Overview/
- http://andyschroder.com/DistributedCharge/GRID/Overview/

# About the Speaker
http://andyschroder.com/

# Workshop Details
### Length of workshop

Would like this to be a 90 minute workshop that is done several times throughout the day. Due to hardware costs and the coaching required, I'd like to limit this to a small number of participants, probably 5.

### Preferred Day/Time Slot 
Don't want to do it during the NextGen village because I've proposed https://github.com/TABConf/2023.tabconf.com/issues/81 , https://github.com/TABConf/2023.tabconf.com/issues/82 , and https://github.com/TABConf/2023.tabconf.com/issues/83 .

**Comment by iglesiasbrandon** [comment]
Hey @AndySchroder, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The workshops will be happening on September 6th and 7th; once we accept some more, we will assign the day, time, and location.

**Comment by AndySchroder** [comment]
Sounds great, let me know what size group you'd like me to plan for. Like I mentioned above, it will be easier for me to have multiple small sessions than one big one. With a small group, it could take place in a small room, but I'd need a TV in there to show people each step.

**Comment by iglesiasbrandon** [comment]
Hey @AndySchroder, unfortunately, I don't know how many people will decide to attend the workshop. We might need to wing it or have a cap on the number of people who can attend. 

You will have a large screen to show people each.

**Comment by AndySchroder** [comment]
What does the SM tag mean?

**Comment by AndySchroder** [comment]
Will the TV have HDMI or some special wireless thing? Would prefer HDMI so I can connect to the raspi.

**Comment by AndySchroder** [comment]
So, as far as dealing with the number of attendees being uncertain. Building and bringing a test setup for each attendee is going to be very costly and complicated to manage even for a small group. Also, much of the setup I'd like to go over is how to configure the operating system and that's going to be difficult for people to do unless they also have a monitor and keyboard on their test unit. I'd like it if there were a single test unit that I demonstrate the operating system setup on where they watch along for that part.

For the python script that actually connects to LND and BoardA0, there are going to be a number of different parts of the code that will be built and independently tested. Board A0 has 4 output relays. Since it runs on the raspi which is a multi-user system, everyone could log into the same machine and I can accommodate a variable number of attendees. The attendees can follow along with most of that locally on their own laptop or on the shared raspi, then at the end we'll put each part of the code together into a single program and test with the output relays on Board A0 with the shared raspi. Each person could be allocated one relay output and then up to 4 people at a time could test and show of their own personal "remix" of all the major python code blocks.

Does this sound interactive enough?

**Comment by AndySchroder** [comment]
What is the wifi situation going to be like at the hotel? Will there be captive portals and such needed to use it? Trying to figure out if their wifi is going to work smoothly with the raspi which does not have a graphical desktop environment.

**Comment by AndySchroder** [comment]
How can I coordinate getting an ssh pubkey from attendees ahead of time?

**Comment by iglesiasbrandon** [comment]
Hey @AndySchroder i would recommend adding to the description that if anyone is interested in this workshop, they should comment with their SSH pubkey on this issue.

**Comment by AndySchroder** [comment]
What time of day will this be presented? All the other workshops have times defined but mine.

**Comment by miketwenty1** [comment]
@iglesiasbrandon bump on this

**Comment by AndySchroder** [comment]
I was talking to @EllyPembroke out of band and we are thinking of doing this talk in the NextGen Village room. Sounds like there is decent time flexibility in there and my other more advanced hardware will be on display there so people can see that in context with the workshop.

**Comment by iglesiasbrandon** [comment]
@AndySchroder sounds good, I assigned it to the NextGen village. @EllyPembroke FYI

**Comment by AndySchroder** [comment]
@EllyPembroke  and @iglesiasbrandon  could we set the time for this as 14:00-16:00 on Day 2?
