### ISSUE TITLE
Seed XOR - How to securely and secretly store your sats

### ISSUE THREAD

**Issue by Searedsalmon** [TABConf/2023.tabconf.com#85]
# Description
### What is this talk about? Give us as many details as possible. 

Seed XOR is a plausibly deniable means of storing secrets in two or more parts that look and behave just like the original secret. One 24 or 12-word seed phrase becomes two or more parts that are also BIP-39 compatible seeds phrases. These should be backed up in your preferred method, metal or otherwise. These parts can be individually loaded with honeypot funds as each one is normal BIP-39 compatible wallet.

### What would an attendee learn from this talk?

Splitting their seed phrase with Seed Xor

### Is there anything folks should read up on before they attend this talk?
- BIP 39: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

### Relevant Links

[SeedXOR](https://github.com/Coldcard/firmware/blob/master/docs/seed-xor.md)

# About the Speaker
### Social Links
Github @searedsalmon
Twitter @seardsalmon

# Talk Details
### Length of Talk
30 min
### Preferred Day/Time Slot 
No preference

**Comment by iglesiasbrandon** [comment]
hey @Searedsalmon could this be a workshop instead?

**Comment by iglesiasbrandon** [comment]
@Searedsalmon poke on my comment above

**Comment by Searedsalmon** [comment]
Hey Brandon, sorry for the delay. I would like to do a talk more than workshop.

**Comment by btsea** [comment]
@Searedsalmon We have an extra non-Socratic slot in our Village for this! Can you tell me a bit more about how the presentation will flow? Will you actually do a seed XOR? Or demo it in some way? That would be really cool.

**Comment by iglesiasbrandon** [comment]
Closing this issue since the item has been completed! Thank you!

**Comment by btsea** [comment]
Thanks @iglesiasbrandon !
