### ISSUE TITLE
Web of Trust

### ISSUE THREAD

**Issue by huumn** [TABConf/2023.tabconf.com#86]
# Description
We program a WoT algorithm together that outsources the selection of a prize for the attendee to all other attendees. The attendee takes home the prize that the algorithm determines.

### What is this workshop about? Provide as many details as possible. 
1. Upon entering, attendees anonymously and privately tell us their preferred prize.
2. Attendees then assign every person seated directly near them a trust score. 
3. We then take these trust scores and run it through an algorithm we build together. For each attendee, the algorithm tells them how much they trust every other attendee in the room.
4. We walk through an algorithm to tally up preferences for each prize, weighting each tally by how much the attendee trusts the tallier (which we got from step 3). 
5. The prize with the highest tally (from the perspective of the attendee's web of trust) is given to the attendee.

### What would an attendee learn from this workshop?
Web of Trust

### Is there anything attendees should read up on before they attend this talk?
Not really. Maybe matrix multiplication and graphs in the CS sense but I can probably explain that.

# About the Speaker
I work on [Stacker News](https://stacker.news)

# Workshop Details
### Length of workshop
30-60m depending on how much prep I do.

### Preferred Day/Time Slot 
Earlier in the conference and earlier in the day preferred.

**Comment by iglesiasbrandon** [comment]
Hey @huumn, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The workshops will be happening on September 6th and 7th; once we accept some more, we will assign the day, time, and location.

**Comment by iglesiasbrandon** [comment]
Hey @huumn , We have added a day, time slot, and length to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by huumn** [comment]
ACK

**Comment by miketwenty1** [comment]
@huumn 

We are about a week away from the start of the conference. I'm sending this to all accepted upcoming workshop. Please review and ensure you have a clear, up to date, high level, agenda on this GitHub issue. Please buffer in time to help with unexpected problems and questions.

TABConf workshops should aim to involve high levels participation. If you're planning to conduct a live demo, please consider that attendees will require clear instructions on how to prepare for following along, (all steps for setup should be double checked) and any presentation should be structured accordingly.
Participants should leave the workshop either with something built, (be it physical or digital), or with specific knowledge gained from the __hands on/interactive__ experience.

**Comment by huumn** [comment]
Workshop complete! I got more frazzled than expected but 

- the code is here: https://github.com/huumn/wot-demo
- the live demo is here: https://www.charlottesweboftrust.com/
