### ISSUE TITLE
The Good, the Bad and The Ugly: Lightning Safety and Security in 2023

### ISSUE THREAD

**Issue by ariard** [TABConf/2023.tabconf.com#87]
The talk is a continuation of Matt's one of last year TABConf on Lightning security and robustness and it will dig into the class of LN protocol vulnerabilities, explain the current mitigations in development across the ecosystem and lay out what Lightning infrastructure operators can do to protect their channel funds with today's Lightning state of implementations, software tooling and operational third-party infrastructure.

The following class of LN protocol vulnerabilities will be investigated (non-exhaustive):
- mass mempool congestions and [flood-&-loot](https://arxiv.org/pdf/2006.08513.pdf) attacks
- [dust HTLC exposure inflation attacks](https://lists.linuxfoundation.org/pipermail/lightning-dev/2021-October/003257.html) and "smart" go-to-chain heuristics
- [pinning attacks](https://github.com/t-bast/lightning-docs) and [package relay](https://bitcoinops.org/en/topics/package-relay/) / nVersion=3 mitigations
- eclipse and [time-dilation attacks](https://arxiv.org/pdf/2006.01418.pdf)
- [witness inflation attacks](https://github.com/bitcoin/bitcoin/pull/19645) and other timevalue DoS
- [channel jamming attacks](https://bitcoinops.org/en/topics/channel-jamming-attacks/) and [HTLC endorsment](https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-April/003918.html)/anti-DoS token mitigations
- ["hot"-key extractions attacks](https://lists.linuxfoundation.org/pipermail/lightning-dev/2023-January/003829.html) and "smart" LN signers security model

The attendees can learn the weaknesses and flaws Lightning is currently exposed to, the engineering state of mitigations and their multi-dimensional trade-offs and what piece of infrastructure and tooling is relevant to be deployed to protect their Lightning infrastructure.

The links provided in the description of the talks are good starters to attend the talk.

About myself, former Chaincode Labs open-source developer, Bitcoin Core and Lightning Dev Kit contributor since 2018, independent Bitcoin protocols R&D engineer.

As usual for all my technical conferences talks, I'm kindly requesting from the organizers to not proceed to video record of my physical persona and nicely requesting the audience to not take pictures, while audio captation is allowed.

Length of talk: 25 min + (10/15 min of Q&A ?)

Preferred Day/Time Slot: Keynote - 8th or 9th September (indifferent)

_The talk content and the slides will be submitted to peer review to other Lightning senior developers to assert the correctness and respect the boundaries in term of sensitive Lightning safety information sharing._

**Comment by iglesiasbrandon** [comment]
hey @ariard thank you for submitting an issue for TABConf 2023! We are reviewing submitted issues and accepting some each week. Keep an eye on this issue in case someone asks questions!

**Comment by ariard** [comment]
Sure thing, the Lightning Village can be a good fit and I think makes it easier to match my personal policy w.r.t speaker privacy.

**Comment by ariard** [comment]
Closing this one, I won't have time to prepare something high-quality. Maintaining the two other talks, feel free to add me on a fitting lightning sec panel at the last minute.
