### ISSUE TITLE
“Draw me a Contracting Protocol” : The case-study of Blockrate Binaries Contracts

### ISSUE THREAD

**Issue by ariard** [TABConf/2023.tabconf.com#88]
The talk is about a) presenting the functional "anatomy" of contracting protocols, a class of Bitcoin second-layers (e.g vaults, LN, DLCs) that has been gaining more and more awareness and usage in the Bitcoin ecosystem along the past years, b) do a case study of Blockrate Binaries Contract as an example of a contracting protocol and c) teach attendees to design their own contracting protocols, the fundamentals, the pitfalls, and the software libraries available to build them.

The talk aims to be in socratic form, where attendees can ask questions on the flight, share their experiences, challenges the ideas presented, etc.

The attendees can read the [BIP331 Motivation](https://github.com/bitcoin/bips/pull/1382) which is one of the best resource available on the challenges of contracting protocols, [the Optech article on Blockrate Binaries](https://bitcoinops.org/en/newsletters/2023/05/10/) and the [Blockrate Binaries paper](https://github.com/blockrate-binaries/paper/blob/master/blockrate-binaries-paper.pdf) itself (previous litterature on POWSWAP is presented in the sources).

About myself, former Chaincode Labs open-source developer, Bitcoin Core and Lightning Dev Kit contributor since 2018, independent Bitcoin protocols R&D enginer.

As usual for all my technical conferences talks, I'm kindly requesting from the organizers to not proceed to video record of my physical persona and nicely requesting the audience to not take pictures, while audio captation is allowed.

Length of talk: 15 - 20min

Preferred Day / Time Slot: Workshop. If both talks (cf. other on on LN sec) are accepted, as a preference not the same day.

_Disclosure of potential conflict of interests: The blockrate binaries paper research has been conducted in the context of a business relationship with the OP_ENERGY project, while in respect of scientific research autonomy and Bitcoin FOSS standards._

**Comment by btsea** [comment]
We'd love to have this in the Socratic Village!

**Comment by miketwenty1** [comment]
@iglesiasbrandon I believe this should be marked as Accepted for the socratic village?

**Comment by btsea** [comment]
Thank you @ariard! Closing on completion.
