### ISSUE TITLE
Utreexo - Prune my coins from your node

### ISSUE THREAD

**Issue by kcalvinalvin** [TABConf/2023.tabconf.com#89]
# Description

Utreexo is a proposed hash-based accumulator for the Bitcoin UTXO set. The talk will focus on how exactly the accumulator algorithms work so that the audience gains a better understanding of how the consensus-critical algorithm works. I will go into detail on how: addition, deletion, prove, and verify functions work as well as how we've implemented the data structure in code. The audience can expect to take away how the algorithms work, how they are implemented, and how/why we got to the current algorithms today, which are different from what the original utreexo paper outlined.

# About the Speaker
### Social Links
Github: github.com/kcalvinalvin
Twitter: twitter.com/kcalvinalvinn

# Talk Details
### Length of Talk

30min or 1 hour. No preference.

### Preferred Day/Time Slot

No preference.

**Comment by iglesiasbrandon** [comment]
Hey @kcalvinalvin, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The talks on the main stage will be happening on September 8th and 9th; once we accept more, we will assign the day, time, and location.

**Comment by iglesiasbrandon** [comment]
Closing this issue because this has been completed!
