### ISSUE TITLE
Building a UX Research Toolkit for bitcoin builders

### ISSUE THREAD

**Issue by mouxdesign** [TABConf/2023.tabconf.com#9]
# Description
### What is this talk about? Give us as many details as possible. 
During most of 2022 Mogashni has been building a UX Research Toolkit. This toolkit is for you the builders. Is it meant to be easy to use and take out the guess work of knowing what users really want and expect when they use the products we build.

For most of 2022 Mogashni built the UX Research toolkit in public totally out in the open inviting feedback from the larger ecosystem of builders and developers in the bitcoin space. The toolkit was built from her hands-on experience working with and alongside various bitcoin projects to help them to improve their user experiences. 

### What would an attendee learn from this talk?
The problem that the toolkit aims to solve is that it is will help builders to understand:
- Why people use our products
- What features they expect from using our products
- What is causing them to stop using our products
- What we can add in terms of features that can ensure people keep on using the our products

_**People use products and continue to use them because they feel understood and that the interface really understands what they need and want. This prevents us from building in a silo, instead we build products that "stick", that feel intuitive and that make people feel empowered when using them. This ultimately breaks that trust barrier and leads to more adoption.**_ - Mogashni

### Is there anything folks should read up on before they attend this talk?
No
### Relevant Links
[Spiral Quarterly update ](https://spiral.xyz/blog/spiral-quarterly-update-q1-2023/)(Grant spotlight)

# About the Speaker
Mogashni is UX Research evangelist and is working on a grant from Spiral to help builders build more human centric products. She is passionate about creating user experiences that make people feel empowered. To do this she believes that connecting with and speaking to users is a way to really understand what they need, want and expect from our application. 

### Social Links
[Twitter](https://twitter.com/MogashniNaidoo)
[Blog](https://uxresearch.simple.ink/blog)

# Talk Details
### Length of Talk
15-20 mins

### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment]
Hello @mouxdesign! Thank you for submitting a Talk issue for TABConf 2023! You are among the first to submit! As we get closer to the conference, we will review all the issues, and the chosen ones will be added to the TABConf 2023 schedule:  https://github.com/orgs/TABConf/projects/1. 

I don't expect us to add any issues to the schedule until a month or two before the conference but keep an eye on this in case someone asks any questions about your issue.

**Comment by iglesiasbrandon** [comment]
Hey @mouxdesign , We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by iglesiasbrandon** [comment]
@mouxdesign, closing this issue since this has been completed, thank you!

**Comment by mouxdesign** [comment]
Hi team! Thank you so much for accepting my talk. Unfortunately I was not able to make it to TAB Conf this year. Will keep it on my radar for next year for sure!
