### ISSUE TITLE
Build a Decentralized Web App with Web5.js

### ISSUE THREAD

**Issue by angiejones** [TABConf/2023.tabconf.com#93]
# Description
Together, we'll build a decentralized web app with Web5.js.

### What is this workshop about? Provide as many details as possible.
Web5.js is a library that enables developers to build decentralized apps. It utilizes open standards such as Decentralized Identity and Decentralized Web Nodes to reimagine the account model of the web. Instead of usernames and passwords, users authenticate with a unique personal identifier that is anchored on Bitcoin.

In this workshop, we'll build a decentralized, serverless app that reads and writes to users' personal data stores - allowing them to maintain ownership of their data and utilize it with any decentralized app!

### What would an attendee learn from this workshop?
- How to create and resolve decentralized identifiers
- How to create, read, update, and delete records in decentralized web nodes
- How to create, install, and query protocols that define data schemes and permissions

### Is there anything attendees should read up on before they attend this talk?

- [What is Web5](https://developer.tbd.website/blog/what-is-web5)

### Is there anything attendees should set up before the workshop?
- a JavaScript IDE such as VSCode

### Relevant Links
- [Web5 Developer Docs](https://developer.tbd.website/docs/)
- [Decentralized Identity](https://www.w3.org/TR/did-core/)
- [Decentralized Web Nodes](https://identity.foundation/decentralized-web-node/spec/)

# About the Speaker
Angie Jones is the Head of Developer Programs for TBD, Block’s newest business unit focused on decentralized technologies. She is an award-winning teacher and international keynote speaker who shares her wealth of knowledge at software companies and conferences all over the world. She is also an IBM Master Inventor, Java Champion, and GitHub Star.

### Social Links
[GitHub](https://github.com/angiejones) 
[Twitter](https://twitter.com/techgirl1908)
[Website](https://angiejones.tech/)

# Workshop Details
### Length of workshop
120 minutes

### Preferred Day/Time Slot 
Flexible

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by iglesiasbrandon** [comment]
Hey @angiejones thank you for submitting an issue for TABConf 2023! We are reviewing submitted issues and accepting some each week. Keep an eye on this issue incase someone asks questions!

**Comment by angiejones** [comment]
@iglesiasbrandon I've been scheduled for another event during this time and unfortunately will need to withdraw my submission. I'll try again next year 🙏🏾
