### ISSUE TITLE
Unleashing Bitcoin's Potential: A New Approach to Lightning Network Liquidity

### ISSUE THREAD

**Issue by johncantrell97** [TABConf/2023.tabconf.com#94]
# Description

Over the past year there has been an effort to formalize a set of specifications for lightning service providers.  The specifications are maturing and the first implementations are surfacing ready to be used by all participants on the lightning network.

This talk will give a quick overview of the liquidity problem the lightning network faces, what has been done historically, and how a new set of protocols hope to solve it.  

It will then dig into the details of the new protocol specifications, highlighting the different approaches and tradeoffs a wallet or lsp can make when considering a solution.  

Finally, I will showcase a new ldk-based LSP library that implements the specifications and how a wallet built with LDK can easily integrate the new liquidity management functionality.

An attendee will learn about one of the biggest problems facing the lightning network, potential solutions to the problem, and an easy way to integrate the solutions into their wallets or applications.

There is no required reading for this talk but some relevant links:

[Lightning Service Provider Specifications ](https://github.com/BitcoinAndLightningLayerSpecs/lsp)
[LDK-based LSP Client Library](https://github.com/lightningdevkit/ldk-lsp-client)

# About the Speaker

I have been working in and around bitcoin for nearly a decade now and most recently joined the [c= team](https://cequals.xyz/) at [Block](https://block.xyz/) to build tools and services that will help bring the next billion people to the lightning network.

I am a core contributor and maintainer of the [LDK-based LSP Client Library](https://github.com/lightningdevkit/ldk-lsp-client).

I wrote a LDK-based lightning server called [Sensei](https://github.com/l2-technology/sensei) that enabled multiple nodes to run within a single application instance.

### Social Links
[Github](https://github.com/johncantrell97) 
[Twitter](https://twitter.com/johncantrell97)

# Talk Details
### Length of Talk
30 minutes

### Preferred Day/Time Slot 
Morning of the 8th is preferable but can likely do anytime.

**Comment by iglesiasbrandon** [comment]
hey @johncantrell97 talks only happen on the 8th and 9th. the 6th and 7th are Builder Days and workshops. If you wanted to change this into an interactive workshop, the 6th or 7th would be an option.

**Comment by johncantrell97** [comment]
Oh whoops, missed that.  I can probably do anytime but would prefer the 8th in that case.

**Comment by iglesiasbrandon** [comment]
Hey @johncantrell97 , congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The talks will be happening on September 8th and 9th; once we accept more, we will assign the day, time, and location.

We will do our best to accommodate the day/ time you asked for!

**Comment by iglesiasbrandon** [comment]
Hey @johncantrell97 , We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by iglesiasbrandon** [comment]
Hey @johncantrell97 Please acknowledge by commenting 'ack'.

**Comment by johncantrell97** [comment]
Ack

**Comment by iglesiasbrandon** [comment]
Closing this issue because it's competed
