### ISSUE TITLE
Solving the bitcoin meta-problem

### ISSUE THREAD

**Issue by john-light** [TABConf/2023.tabconf.com#95]
# Description
### What is this talk about? Give us as many details as possible. 

Time is limited, material resources are limited, and there’s a real possibility that bitcoin ossifies in the not-so-distant future and no more consensus changes can be made. If this is all true, it leads me to wonder: what is the most important unsolved problem in bitcoin that we should prioritize fixing with the limited resources we have before bitcoin consensus ossifies?

My gut answer is “privacy”. Whenever I’m teaching newcoiners, I’m always bothered by how many caveats and instructions are required to teach them how to gain some semblance of privacy when using bitcoin. And even after that, I come away from the conversation both uncertain that the tools recommended will actually protect the newcoiner’s privacy in the long-run, and also quite certain that even if the tools did work, the newcoiner will make a mistake at some point that will un-do the work they had done to protect their privacy up until that point. This is unacceptable and untenable. We need a solution that people can use to store and transfer coins in a self-custodial, p2p manner that offers privacy and ease-of-use as close to physical cash as possible. Bitcoin is too risky and inconvenient for most people to use otherwise.

Then I think, ok, if we somehow solved that, then what’s the next most important problem to solve? And the one after that? And after that? And so on. There will always be some new problem to solve, because human desire and creativity is neverending. And I realize that actually, perhaps the most important problem to solve is that in many (most?) cases, we don't yet have a way of solving new user problems without either giving up on self-custody or activating consensus changes. I’m calling this “the bitcoin meta-problem”.

Currently, to solve some problem that users have, a bitcoin developer must either work within the limited confines of bitcoin’s existing scripting capabilities, or else propose consensus changes that require buy-in from the majority of miners and economic full nodes. If the developer can’t or doesn’t want to do either of those, then they have to convince the user to move their BTC into some (centralized/federated/collateralized) custodial system, sacrificing to some degree the core value propositions of bitcoin for some new functionality.

What is needed is a solution (a “meta-solution” to the “meta-problem”) that enables a bitcoin developer to build new functionality that solves their users’ problem without requiring the developer to either make consensus changes to bitcoin or convince their users to give up self-custody.

One meta-solution would be to directly add a fully expressive smart contract language to bitcoin, capable of supporting any kind of logic that developers would need to solve any kind of user problem. This is the approach pioneered by Ethereum. Bitcoin developers have so far rejected this approach because of the relatively heavy computational burden that it would place on bitcoin full nodes and this consensus is unlikely to change. So we need to add one more requirement: the meta-solution can’t impose heavy computational costs on bitcoin full nodes.

Another meta-solution would be to add support for validity rollups to bitcoin. Validity rollups can enable developers to deploy new functionality without having to make consensus changes to bitcoin, convince users to give up self-custody, or put a heavy computational load on bitcoin full nodes. To support any kind of new functionality (new privacy protocols, new smart contracts, etc), bitcoin full nodes only have to verify a single cryptographic proof per rollup block.

Based on [my research](https://lightco.in/2022/10/21/validity-rollups/), I consider validity rollups to be the best meta-solution that has been invented so far. Validity rollups might even be the best meta-solution possible as a protocol that can check all of the relevant boxes: self-custodial (trustless), infinitely extensible, and easy for bitcoin full nodes to verify and stay in sync.

### What would an attendee learn from this talk?

Answers to these questions:
- What is the bitcoin meta-problem?
- What is my proposed solution to the meta-problem, and how does it compare to alternatives?
- Bonus, if there's time: How do validity rollups actually work?

### Relevant Links

This talk is based on this blog post: https://lightco.in/2023/01/03/meta-problem/

I came to this conclusion after performing this research that was sponsored by the Human Rights Foundation: https://bitcoinrollups.org

See also:
- https://lightco.in/2022/11/03/validia-chains/
- https://lightco.in/2023/03/13/sovereign-rollups/

# About the Speaker
### Social Links
Github - https://github.com/john-light
Twitter - https://twitter.com/lightcoin
Website - https://lightco.in

# Talk Details
### Length of Talk

I could talk for as little as 15-20 mins or as long as 45-60 mins. It depends on how much time you want to give me to go into how validity rollups work and compare to alternatives.

### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

Preference for Sept 8th, mid morning or afternoon

**Comment by miketwenty1** [comment]
@iglesiasbrandon I want to note he has a very compressed version of this talk available. I see it wasn't accepted, but it may be interesting to try to fit it in if possible.
