### ISSUE TITLE
A Hybrid Solution To Unjamming Lightning

### ISSUE THREAD

**Issue by carlaKC** [TABConf/2023.tabconf.com#96]
# Description
### What is this talk about?
The threat of channel "jamming" attacks against the lightning network has been known and discussed [since 2015](https://lists.linuxfoundation.org/pipermail/lightning-dev/2015-August/000135.html). This problem has remained unsolved despite eight years of on-and-off discussion on the lightning mailing list. Addressing this trivially inexpensive denial of service attack against the network is vital to ensuring the long-term success of lightning.

This talk will cover the implementation details of a hybrid proposal to mitigate channel jamming, as originally outlined by  [Clara Shikhelman and Sergei Tikhomirov](https://research.chaincode.com/2022/11/15/unjamming-lightning). It will justify the combination of local reputation tracking and unconditional fees as a hybrid approach to mitigating jamming attacks against the lightning network and provide implementation details of the ongoing work to specify this mitigation in the BOLTs.

### What would an attendee learn from this talk?
- A high level classification of ~8 years of jamming mitigation proposals
- Motivation for a hybrid proposal to use unconditional fees and local reputation tracking to mitigate jamming
- Details of the ongoing specification of HTLC endorsement and reputation in the BOLTs
- How this solution is being sanity checked against real world data (and how they can help!)

### Is there anything folks should read up on before they attend this talk?
Attendees should have a basic understanding of the way that the Lightning Network operates (channels, routing and HTLCs) and familiarize themselves with the concept of [channel jamming attacks](https://bitcoinops.org/en/topics/channel-jamming-attacks/). For details of the solution proposed, see the [original research paper](https://research.chaincode.com/2022/11/15/unjamming-lightning).

### Relevant Links
- [Summary Gist](https://gist.github.com/carlaKC/be820bb638624253f3ae7b39dbd0e343)
- [BOLT PR](https://github.com/lightning/bolts/pull/1071)
- [Research Paper](https://research.chaincode.com/2022/11/15/unjamming-lightning)

If you're looking to catch up on the plane, the following "one pager" summaries are a quick read: 
- [Overview of Migitations](https://docs.google.com/document/d/1P30rtfVsRlci6DW7X0G7zbY-4PBP_jERolEZprwW06w/edit?usp=sharing)
- [Hybrid Approach](https://docs.google.com/document/d/1EilY47u0ZgYZP2dJHs1tEX1fSVE_oZ8LRVTRo7XTXFU/edit?usp=sharing)
- [Reputation Summary](https://docs.google.com/document/d/19BdHb_rF_VVIwiCnh2RlrT8Rn_gn-KDPvcaeqJ7v550/edit?usp=sharing)

# About the Speaker

Carla is a software engineer working on the implementation and improvement of the Lightning Network [specification](https://github.com/lightning/bolts) at Chaincode Labs. She previously worked at Lightning Labs, where she focused on reliability improvements to LND and led the Lightning Loop submarine swap team. She got her start in Bitcoin development at the 2019 [Chaincode Residency](https://residency.chaincode.com/) and has been passionate about paying it forward to help onboard new bitcoin developers ever since.

### Social Links
https://github.com/carlaKC
https://twitter.com/actuallyCarlaKC

In collaboration with Clara Shikhelman, Chaincode Labs:
https://github.com/ClaraShk
https://twitter.com/ClaraShik

# Talk Details
### Length of Talk
30 mins

### Preferred Day/Time Slot 
Thursday 7th / late morning

**Comment by iglesiasbrandon** [comment]
Hey @carlaKC, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The talks on the main stage will be happening on September 8th and 9th; once we accept more, we will assign the day, time.

**Comment by iglesiasbrandon** [comment]
Hey @carlaKC , We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by carlaKC** [comment]
ACK ❗

**Comment by iglesiasbrandon** [comment]
Closing this issue since this item has been completed! Thank you!
