### ISSUE TITLE
Formula 21: Drivechain to Survive

### ISSUE THREAD

**Issue by stum0** [TABConf/2023.tabconf.com#97]
# Description
### What is this panel discussion about? Please give us as many details as possible. 
 Drivechain debate! Are drivechains needed for the long term survival of bitcoin? Or any other subject to do with drivechains.

Idealy between Paul Sztorc and Peter Todd. But if not, then anyone else who wishes to go up against Paul. If there is no one, maybe we have Paul on stage and he has to watch two other people debate drivechains, but hes not allowed to speak.

### What would an attendee learn from this talk?
The pro's and cons of drivechains
### Is there anything folks should read up on before they attend this talk?
preferably the whole of truthcoin.info but if not just https://www.drivechain.info/ will do 
### Relevant Links
https://fiatjaf.com/drivechain.html
https://www.drivechain.info/
# About the panelist
### Social Links
GitHub 
@psztorc
@petertodd
Twitter
https://twitter.com/peterktodd
https://twitter.com/Truthcoin
Website

# Panel Discussion Details
### Length of the panel discussion
I'm not sure on what the format of this debate should be so i will leave that up to someone else to decide. 
### Preferred Day/Time Slot 
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by zantoshi** [comment]
+1

**Comment by petertodd** [comment]
On Wed, Jul 12, 2023 at 10:24:25AM -0700, stum0 wrote:
> # Description
> ### What is this panel discussion about? Please give us as many details as possible. 
>  Drivechain debate, are drivechains needed for the long term survival of bitcoin? Or maybe another subject to do with drivechains.
> 
> Idealy between Paul Sztorc and Peter Todd. But if not, then anyone else who wishes to go up against Paul. If there is no one, maybe we have Paul on stage and he has to watch two other people debate drivechains

I'm willing to do this!

**Comment by psztorc** [comment]
I will do it sure

**Comment by iglesiasbrandon** [comment]
@petertodd @psztorc, congratulations, this issue has been accepted for TABConf 2023!

@miketwenty1 will moderate this. 

The talks/ panels on the main stage will be on September 8th and 9th; once we accept more, we will assign the day, time.

**Comment by iglesiasbrandon** [comment]
Hey @petertodd @psztorc @miketwenty1 , We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by petertodd** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Thanks.

Consider me ACK'd to do the Drivechain to Survive talk at TABConf 2023 once
$1700 USD worth of BTC has been sent to this address to cover my travel
expenses (hotel + round trip travel from Europe):

    bc1px4wxzjqtkz0d8glx7y2u6zuls0fyldvwdqqwz3txaxx37l04jvas4yu5ts

I don't care who pays. So long as I don't. :)

-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEE0RcYcKRzsEwFZ3N5Lly11TVRLzcFAmTeDfYACgkQLly11TVR
Lzd+sg/+NiCdnBRILafYkPQIsFDxVHGKbts9Yoo5sbmBWmekVMDsd9oum0Ymw7ZP
c88G+mFZaH9CMhTtyN/Cb0hh/BZJbHMQVwApHMVHtw9FLp4YiZjKZEf8g7a8Z2TF
7MPL045LhdYgbeY0CR4WrUrB782rgVv59N/GzcJFuGCETMIifYV+JkXUH68I0rrS
pTvoD2LRgSvbZzU6lGeMN1G3bB4GmGZQGHuRIIV0J+sazU6j4t2HFqd0hn96ovYp
odSyM+5bb1weklWUBFwXwbkfSybThZR1VGCgc5AZLN5WjEqPGQG5MNQyre3GrIVZ
gL+wXbzwtQw2kLPX3nQCP0p/fGLEhzc4KRcQvoOuAT6TUc0Paoz81bdftG5b10oM
bmFHKyZ1gwCKI6+x3lKsLXA5hLzhK1Xm1MQO8GwnPIPv6ulPVuJd/F6WnwmudKiH
Fr9A/EaSwxSE7SF5Gs+t8GgQ1qeHW66G9eNml42gV5yI0IHE8/jpyKSBj7FiEXO+
7ed5W/VSJE7vE3vidh8XTxLb9bsWuvEeKsb5ZxxU1+C7PMBqemM3b/uDhaxywQc2
dgrm671RV8Glyl5vWGS+ypLBqhH+p6fPrJAL8NabBvfoI9LHvcsS+O95OvIRkKse
hNW/Q2Ob7O2sVGBbRCridl4oZUAAxFyieUC6BqtuAsCm14RQ6WI=
=WVRC
-----END PGP SIGNATURE-----

```

**Comment by petertodd** [comment]
...and to @psztorc, yes, the blog post is coming. :)

**Comment by iglesiasbrandon** [comment]
hey @petertodd, TABConf has a grant program you can apply to. 
This is the way. https://2023.tabconf.com/grants

Please let me know if you are planning to attend TABConf and if you plan on being a part of this panel with @miketwenty1 and @psztorc.

**Comment by petertodd** [comment]
@iglesiasbrandon Submitted.

**Comment by iglesiasbrandon** [comment]
Closing this issue since the debate is over, thank you for the debate @petertodd @psztorc @miketwenty1
