### ISSUE TITLE
Interactive Breakers - Why does interactivity ruin everything?

### ISSUE THREAD

**Issue by adiabat** [TABConf/2023.tabconf.com#98]
# Description
### What is this workshop about? Provide as many details as possible. 

This workshop is about the surprisingly high cost of interactivity.

Bitcoin (and the more general ideas of digital currency) has seen years of work on really cool decentralized protocols, but many promising protocols haven't seen adoption or use commensurate with their inherent theoretical awesomeness.  In many cases, interactivity is the reason why. 

I'll go over some interactive and non-interactive protocols and try to define what "interactivity" means, and what parts of interactivity seem to be the costly ones.  The interactivity requirements of the Lightning Network is a current focus, but similar issues are widespread throughout decentralized protocols.

In the workshop itself, interactivity will be optional. I'll talk in the beginning and then we'll have an interactive discussion.  
..or maybe not!  Maybe I just show some slides and people nod their heads a bit and look at their phones, and the discussion aspect of the talk fails to achieve adoption due to the surprisingly high costs of interactivity. :)

### What would an attendee learn from this workshop?

I'll go over some topics at a high level:

- oldschool: the Fiat-Shamir transform and cryptographic non-interactivity
- Address re-use, one time addresses, stealth addresses
- multisig / musig / frost / roast
- Interactive and non-interactive signature aggregation
- SNICKER / Coinjoin
- Problems with interactivity in the Lightning Network

so attendees can learn a bit about those topics if they want to investigate further.  I'm hoping to also get ideas / problems / strategies from other attendees about how they deal with interactive protocols, or ways to avoid the need for interactivity.  How can we make interactive protocols less painful to program, and easier for people to use?

### Is there anything attendees should read up on before they attend this talk?
People with experience programming Bitcoin / LN software may have experience with these issues that they can bring up.  

### Is there anything attendees should set up before the workshop?
Probably just ideas.
If people bring laptops / computers we could try to send files to each other without the data leaving the room.

### Relevant Links

Fiat-Shamir: https://en.wikipedia.org/wiki/Fiat%E2%80%93Shamir_heuristic
Silent Payments: https://gist.github.com/RubenSomsen/c43b79517e7cb701ebf77eec6dbb46b8
SNICKER: https://gist.github.com/AdamISZ/2c13fb5819bd469ca318156e2cf25d79
FROST https://eprint.iacr.org/2020/852
Musig2 https://eprint.iacr.org/2020/1261
LN Async payments https://lists.linuxfoundation.org/pipermail/lightning-dev/2021-October/003307.html
(may add more links that I find on this topic)

# About the Speaker

Tadge Dryja, Bitcoin & Lightning researcher & programmer.  Significant papers authored or co-authored include The Bitcoin Lighting network, Discreet Log Contracts, Utreexo.  

### Social Links
Github 
https://github.com/adiabat
Twitter
https://twitter.com/tdryja
Website
none at the moment

# Workshop Details
### Length of workshop

45 minutes (flexible)

### Preferred Day/Time Slot 

Flexible

**Comment by miketwenty1** [comment]
@adiabat, we are changing the format to a talk. You can still make it a follow-along demo or something similar. However, since you want to cover a lot of material, it would be best to present it as a talk. We are very excited about this submission.

**Comment by iglesiasbrandon** [comment]
hey @adiabat this talk was officially accepted.

**Comment by iglesiasbrandon** [comment]
Hey @adiabat, We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by adiabat** [comment]
ACK

Thanks, look forward to seeing everyone in Atlanta next month!

**Comment by adiabat** [comment]
Related materials:

Fiat-Shamir Transform:
https://en.wikipedia.org/wiki/Fiat%E2%80%93Shamir_heuristic

Silent Payments BIP: https://github.com/bitcoin/bips/blob/c55f80c53c98642357712c1839cfdc0551d531c4/bip-0352.mediawiki

The Saddest Moment:
https://scholar.harvard.edu/files/mickens/files/thesaddestmoment.pdf

**Comment by iglesiasbrandon** [comment]
Closing this issue since it's completed! Thanks @adiabat !
