### ISSUE TITLE
Taproot Assets Workshop

### ISSUE THREAD

**Issue by HannahMR** [TABConf/2023.tabconf.com#99]
# Taproot Assets Workshop
This workshop will help developers who are thinking about building with Taproot Assets to get hands-on experience using the daemon focusing on using the available API’s.

Specifically, here is what we will practice during the workshop:
* Installing tapd
* Understanding the LND <-> tapd connection
* What tapd handles
* Configuring and running tapd on testnet
* Running tapd on Polar
* Using tapd via REST and grpc
* Minting unique and fungible assets
* Minting assets in tranches
* The bulk minting of assets
* Connecting to Universes
* Working with proofs
* Understanding why and how vPSBT are used
 
### What would an attendee learn from this workshop?

Our goal is for attendees to leave the workshop having minted assets, some with metadata, minted assets in a batch, having pushed the proof up to one’s own universe, federated their universes together with other attendees universes, and to have synced proofs and then pulled down each other asset mint data. 

As this workshop is designed to assist people looking to build with the protocol, we will endeavor to customize the discussion and work to the audience in attendance and to take time to answer any questions attendees may have about the protocol.

### Relevant Links for Preparation

We will be using Polar and Python scripts for this workshop. Please prepare by installing Docker on your machine and downloading and running Polar to check for any Docker permissions issue prior to the workshop. 

* The Taproot Assets docs: https://docs.lightning.engineering/the-lightning-network/taproot-assets 
* The API docs: https://lightning.engineering/api-docs/api/lnd/ 
* The Taproot Assets Intro video: https://youtu.be/-yiTtO_p3Cw 
* The Taproot Assets Demo video: https://youtu.be/xtklaJHfKIY 
* The Taproot Assets v0.2 video: https://youtu.be/8Qi7VOvKe5o 
* Lightning Polar: https://lightningpolar.com/ 
* Example Python scripts: https://github.com/HannahMR/tapd-python-scripts 

# About the Speaker

Hannah Rosenberg is a Developer Advocate for Lightning Labs. Her journey with Bitcoin began in 2012, sparked by her interest in economics. With a strong technical background and years of experience as a web developer, Hannah founded Velas Commerce in 2014, focusing on Bitcoin integration and consulting services. Deeply rooted in the Bitcoin community, Hannah spent five years as the organizer of Chicago's Bitcoin and Open Blockchain meetup. Currently, she serves as the organizer of the San Juan BitDevs. In 2017, Hannah began sharing her knowledge of the technology through teaching. She has been an educator for various organizations, including non-profits, Saylor Academy, and her alma mater, UIC.

### Social Links
* Twitter: https://twitter.com/hmichellerose 
* LinkedIn: https://www.linkedin.com/in/hannahmr/ 
* Nostr: https://snort.social/p/npub1tv5j2h2742ht2a6490cdzypsxah5wlge5qyutadgphw884ynt8mqg4jlst 
* Github: https://github.com/HannahMR 

# Workshop Details
120 mins

**Comment by iglesiasbrandon** [comment]
Hey @HannahMR, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The workshops will be happening on September 6th and 7th; once we accept some more, we will assign the day, time, and location.

**Comment by iglesiasbrandon** [comment]
Hey @HannahMR , We have added a day, time slot, and length to this issue.
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/4

Please acknowledge by commenting 'ack'.

This will confirm your workshop for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by HannahMR** [comment]
ack

**Comment by miketwenty1** [comment]
@HannahMR 

We are about a week away from the start of the conference. I'm sending this to all accepted upcoming workshop. Please review and ensure you have a clear, up to date, high level, agenda on this GitHub issue. Please buffer in time to help with unexpected problems and questions.

TABConf workshops should aim to involve high levels participation. If you're planning to conduct a live demo, please consider that attendees will require clear instructions on how to prepare for following along, (all steps for setup should be double checked) and any presentation should be structured accordingly.
Participants should leave the workshop either with something built, (be it physical or digital), or with specific knowledge gained from the __hands on/interactive__ experience.

**Comment by HannahMR** [comment]
And confirming that I've got the info correct here, I will be at the Base58 Protocol Village room on Thursday the 7th, 1pm Atlanta time.

**Comment by iglesiasbrandon** [comment]
Hey @HannahMR , I am closing this issue since you have completed the workshop. Thank you for all of the effort you put into it!
